from scrapy import cmdline

# cmdline.execute("scrapy crawl SwanseaUniversityPrifysgolAbertawe_U".split())
# cmdline.execute("scrapy crawl SwanseaUniversityPrifysgolAbertawe_P".split())
# cmdline.execute('scray crawl gaokao'.split())
# cmdline.execute('scrapy crawl picture'.split())


# cmdline.execute('scrapy crawl UniversityOfSouthampton_P'.split())
# cmdline.execute('scrapy crawl UniversityOfStAndrews_P'.split())
# cmdline.execute('scrapy crawl UniversityOfGlasgow_P'.split())
cmdline.execute('scrapy crawl UniversityOfTheArtsLondon_P'.split())
# cmdline.execute('scrapy crawl UniversityOfOxford_P'.split())
# cmdline.execute('scrapy crawl DeMontfortUniversity_P'.split())
# cmdline.execute('scrapy crawl BrunelUniversityLondon_P'.split())
# cmdline.execute('scrapy crawl HarperAdamsUniveristy_P'.split())
# cmdline.execute('scrapy crawl UniversityOfStirling_P'.split())
# cmdline.execute('scrapy crawl CoventryUniversity_P'.split())
# cmdline.execute('scrapy crawl CityUniversityOfLondon_P'.split())
# cmdline.execute('scrapy crawl UniversityOfLiverpool_P'.split())
# cmdline.execute('scrapy crawl UniversityCollegeLondon_P'.split())
# cmdline.execute('scrapy crawl UniversityOfYork_P'.split())
# cmdline.execute('scrapy crawl DurhamUniversity_P'.split())

# cmdline.execute('scrapy crawl LondonSouthBankUniversity_P'.split())
# cmdline.execute('scrapy crawl ManchesterMetropolitanUniversity_P'.split())
# cmdline.execute('scrapy crawl MiddlesexUniversity_P'.split())
# cmdline.execute('scrapy crawl NewmanUniversity_P'.split())
# cmdline.execute('scrapy crawl NorthumbriaUniversity_P'.split())

# cmdline.execute('scrapy crawl NorwichUniversityoftheArts_P'.split())
# cmdline.execute('scrapy crawl OxfordBrookesUniversity_P'.split())
# cmdline.execute('scrapy crawl QueenMargaretUniversity_P'.split())
# cmdline.execute('scrapy crawl LiverpoolJohnMooresUniversity_P'.split())
# cmdline.execute('scrapy crawl LeedsBeckettUniversity_P'.split())
# cmdline.execute('scrapy crawl LeedsTrinityUniversity_P'.split())
# cmdline.execute('scrapy crawl StMaryUniversityTwickenham_P'.split())

# cmdline.execute('scrapy crawl StaffordshireUniversity_P'.split())
# cmdline.execute('scrapy crawl UlsterUniversity_P'.split())
# cmdline.execute('scrapy crawl UniversityForTheCreativeArts_P'.split())
# cmdline.execute('scrapy crawl AngliaRuskinUniversity_P'.split())
# cmdline.execute('scrapy crawl UniversityofBedfordshire_P'.split())

# cmdline.execute('scrapy crawl UniversityOfLeicester_P'.split())