# _*_ coding:utf-8 _*_
__author__ = 'zjl'
__date__ = '2018/10/15 11:45'
import datetime

# 2018/10/15    表tmp_school_major_ca_ben
# 初始化item字典
def get_item(itemClass):
    item = itemClass()
    item['school_name'] = None
    item['location'] = None
    item['campus'] = None
    item['major_type1'] = None
    item['department'] = None
    item['degree_name'] = None
    item['degree_cname'] = None
    item['degree_name_desc'] = None
    item['degree_overview_en'] = None
    item['degree_overview_cn'] = None
    item['major_name_en'] = None
    item['major_name_cn'] = None
    item['overview_en'] = None
    item['overview_cn'] = None
    item['start_date'] = None
    item['duration'] = None
    item['duration_per'] = None
    item['modules_en'] = None
    item['modules_cn'] = None
    item['career_en'] = None
    item['career_cn'] = None
    item['deadline'] = None
    item['apply_pre'] = None
    item['apply_fee'] = None
    item['tuition_fee_pre'] = None
    item['tuition_fee'] = None
    item['entry_requirements_en'] = None
    item['entry_requirements_cn'] = None
    item['require_chinese_en'] = None
    item['require_chinese_cn'] = None
    item['average_score'] = None
    item['current_state'] = None
    item['gaokao_desc'] = None
    item['gaokao_zs'] = None
    item['gaokao_score_wk'] = None
    item['gaokao_score_lk'] = None
    item['huikao_desc'] = None
    item['huikao_zs'] = None
    item['is_language'] = 0
    item['min_language_require'] = None
    item['ielts_desc'] = None
    item['ielts'] = None
    item['ielts_l'] = None
    item['ielts_s'] = None
    item['ielts_r'] = None
    item['ielts_w'] = None
    item['toefl_code'] = None
    item['toefl_desc'] = None
    item['toefl'] = None
    item['toefl_l'] = None
    item['toefl_s'] = None
    item['toefl_r'] = None
    item['toefl_w'] = None
    item['sat_code'] = None
    item['sat1_desc'] = None
    item['sat2_desc'] = None
    item['act_code'] = None
    item['act_desc'] = None
    item['alevel'] = None
    item['ib'] = None
    item['ap'] = None
    item['interview_desc_en'] = None
    item['interview_desc_cn'] = None
    item['portfolio_desc_en'] = None
    item['portfolio_desc_cn'] = None
    item['is_diploma_certification'] = 0
    item['is_graduation_card'] = 0
    item['is_report_code'] = 0
    item['is_gaokao_score'] = 0
    item['is_huikao_score'] = 0
    item['other'] = None
    item['url'] = None
    item['gatherer'] = "yangyaxia"
    item['batch_number'] = 1
    item['finishing'] = None
    item['update_time'] = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    item['import_status'] = None
    item['specific_requirement_en'] = None
    return item