key = ["https://www.realestate.com.au/agency/korn-real-estate-campbelltown-rla-255949-ZWYBTV",
"https://www.realestate.com.au/agency/jj-real-estate-sa-leabrook-KSFYVV",
"https://www.realestate.com.au/agency/jinsea-real-estate-kent-town-CVEZXX",
"https://www.realestate.com.au/agency/harcourts-beyond-holland-park-XRHSTR",
"https://www.realestate.com.au/agent/christina-cheng-1411522",
"https://www.realestate.com.au/agency/h-t-brisbane-pty-ltd-brisbane-DQLBQV",
"https://www.realestate.com.au/agency/position-property-services-pty-POTPAD",
"https://www.realestate.com.au/agency/raine-horne-coorparoo-camp-hill-LWMTYY",
"https://www.realestate.com.au/agency/joy-realty-sunnybank-MWJYOA",
"https://www.realestate.com.au/agency/auston-realty-EACHRR",
"https://www.realestate.com.au/agency/jenny-yang-realty-brisbane-city-OMWDMS",
"https://www.realestate.com.au/agency/dpg-property-group-melbourne-CVUSUP",
"https://www.realestate.com.au/agency/hamilton-finley-box-hill-IJMZNK",
"https://www.realestate.com.au/agency/ironfish-real-estate-melbourne-TJCDWC",
"https://www.realestate.com.au/agency/lj-hooker-city-residential-melbourne-RIZTKO",
"https://www.realestate.com.au/agency/aussie-home-real-estate-kew-FEHCRQ",
"https://www.realestate.com.au/agency/justin-james-blackburn-NMAKBJ",
"https://www.realestate.com.au/agency/harcourts-mitcham-LAZDKX",
"https://www.realestate.com.au/agency/ivy-real-estate-docklands-docklands-RIUNYL",
"https://www.realestate.com.au/agency/paragon-real-estate-carlton-RLJTFB",
"https://www.realestate.com.au/agency/royaland-real-estate-melbourne-IJQZJB",
"https://www.realestate.com.au/agency/sweeney-estate-agents-footscray-SWFFOO",
"https://www.realestate.com.au/agency/stockdale-leggo-glen-waverley-XSLGWY",
"https://www.realestate.com.au/agency/matrix-global-melbourne-carlton-LIFYVY",
"https://www.realestate.com.au/agency/harcourts-clayton-XRWCLB",
"https://www.realestate.com.au/agency/wise-earth-property-group-melbourne-QDMMTD",
"https://www.realestate.com.au/agency/paramount-residential-GSHAGI",
"https://www.realestate.com.au/agency/international-equities-carlton-IECCAR",
"https://www.realestate.com.au/agency/ray-white-oakleigh-XRWOAK",
"https://www.realestate.com.au/agency/sea-city-NTSONF",
"https://www.realestate.com.au/agency/stage-property-east-perth-JUPGAB",
"https://www.realestate.com.au/agency/augurum-property-mt-hawthorn-VPZEJJ",
"https://www.realestate.com.au/agency/century-21-grand-alliance-perth-XRWXND",
"https://www.realestate.com.au/agency/blue-ocean-real-estate-sydney-DVSWJR",
"https://www.realestate.com.au/agency/rma-eastwood-eastwood-RMGCGK",
"https://www.realestate.com.au/agency/callagher-estate-agents-annandale-CAZANN",
"https://www.realestate.com.au/agency/elanda-partners-real-estate-sydney-ZPCAPO",
"https://www.realestate.com.au/agency/everest-realty-pty-ltd-chatswood-ZPCAGW",
"https://www.realestate.com.au/agency/pw-realty-sydney-ODKSDL",
"https://www.realestate.com.au/agency/jif-realty-RCWWKA/",
"https://www.realestate.com.au/agency/anc-real-estate-pyrmont-AIKLIF",
"https://www.realestate.com.au/agency/noble-investment-group-QKQIKF",
"https://www.realestate.com.au/agency/pg-mode-realty-haymarket-PGMHAY",
"https://www.realestate.com.au/agency/ghk-real-estate-NOHFQX",
"https://www.realestate.com.au/agency/sec-property-group-sydney-VPCZGA",
"https://www.realestate.com.au/agency/perfect-living-realty-PYYJPB",
"https://www.realestate.com.au/agency/dragon-australia-sydney-VAZVIJ",
"https://www.realestate.com.au/agency/lj-hooker-chinatown-XLJSYF",
"https://www.realestate.com.au/agency/black-diamondz-property-concierge-sydney-KMXVVK",
"https://www.realestate.com.au/agency/ray-white-residential-sydney-cbd-SOMAZG",
"https://www.realestate.com.au/agency/greencliff-agency-sydney-ABCSYT",
"https://www.realestate.com.au/agency/boutique-property-agents-sydney-GOJVRX",
"https://www.realestate.com.au/agency/century-21-city-quarter-sydney-PXDSHF",
"https://www.realestate.com.au/agency/obsidian-property-sydney-FWTIVL",
"https://www.realestate.com.au/agency/sydney-residential-metro-pty-ltd-sydney-SYVSYD",
"https://www.realestate.com.au/agency/metro-realty-AQFNMV",
"https://www.realestate.com.au/agency/sydney-cove-property-the-rocks-PUHSYD",
"https://www.realestate.com.au/agency/chidiac-realty-wentworth-point-RMRTVE",
"https://www.realestate.com.au/agency/grand-sydney-realty-ultimo-FKKDTB",
"https://www.realestate.com.au/agency/laingsimmons-cbd-surry-hills-sydney-PKNMVT",
"https://www.realestate.com.au/agency/laing-real-estate-elizabeth-bay-XLSELI",
"https://www.realestate.com.au/agency/property-square-realty-sydney-LKUEQQ", ]
operatorvalue = ["Korn Real Estate",
"JJ Real Estate",
"Jin Sea Real Estate",
"Harcourts Beyond Sunnybank & Holland Park",
"Q&C Management Pty Ltd",
"H&T Brisbane Pty Ltd - Brisbane",
"New Techcom Marketing Enterprises Pty Ltd",
"Raine&Horne Coorparoo",
"Joy Realty",
"Auston Realty",
"Jenny Yang Realty",
"Dynasty Property",
"Hamilton Finley Box Hill",
"Ironfish Real Estate - MELBOURNE",
"LJ Hooker City Residential",
"Aussie Home",
"Justin James Real Estate",
"Harcourts - Mitcham（City&Boxhill)",
"Ivy Real Estate Docklands - DOCKLANDS",
"Paragon Real Estate",
"Royaland",
"Sweeney Estate",
"Stockdale & Leggo - Glen Waverley",
"Matrix Global- Carlton",
"Harcourts - Clayton",
"Wise Earth",
"Paramount Residential",
"International Equities - CARLTON",
"Ray White - Oakleigh",
"Sea & City Australia Investment Pty Ltd",
"Stage property",
"Augurum Property",
"Century 21 Grand Alliance - PERTH",
"Blue Ocean Real Estate - Sydney",
"RMA Real Estate",
"Callagher Estate Agents",
"Elanda Partners",
"Everest Realty",
"PW Realty",
"JIF Group",
"ANC Real Estate - Pyrmont",
"Noble Investment Group（Sydney）",
"P&G Mode Realty",
"GHK real estate P/L",
"SEC property group",
"Perfect Living Realty",
"Dragon Australia PTY Ltd.",
"LJ Hooker Chinatown",
"Black Diamondz Property Concierge",
"Ray White Residential Sydney CBD",
"Greencliff Realty",
"Boutique Property Agents",
"CENTURY 21 City Quarter",
"Obsidian Property",
"Sydney Residential Metro",
"Metro Realty",
"Sydney Cove Property",
"Chidiac Realty Sydney",
"Grand Sydney Realty",
"Laing+Simmons CBD Surry Hills",
"Laing Real Estate",
"Property Square",]
cityvalue = ["Adelaide",
"Adelaide",
"Adelaide",
"Brisbane",
"Brisbane",
"Brisbane",
"Brisbane",
"Brisbane",
"Brisbane",
"Brisbane",
"Brisbane",
"Melbourne",
"Melbourne",
"Melbourne",
"Melbourne",
"Melbourne",
"Melbourne",
"Melbourne",
"Melbourne",
"Melbourne",
"Melbourne",
"Melbourne",
"Melbourne",
"Melbourne",
"Melbourne",
"Melbourne",
"Melbourne",
"Melbourne",
"Melbourne",
"Melbourne&The gold coast",
"Perth",
"Perth",
"Perth",
"Sydney",
"Sydney",
"Sydney",
"Sydney",
"Sydney",
"Sydney",
"Sydney",
"Sydney",
"Sydney",
"Sydney",
"Sydney",
"Sydney",
"Sydney",
"Sydney",
"Sydney",
"Sydney",
"Sydney",
"Sydney",
"Sydney",
"Sydney",
"Sydney",
"Sydney",
"Sydney",
"Sydney",
"Sydney",
"Sydney",
"Sydney",
"Sydney",
"Sydney", ]

operatorDict = {}
cityDict = {}
for i in range(len(key)):
    operatorDict[key[i]] = operatorvalue[i]
    cityDict[key[i]] = cityvalue[i]

# print(operatorDict)
# print(cityDict)

start_urls = ["https://www.realestate.com.au/agency/korn-real-estate-campbelltown-rla-255949-ZWYBTV",
"https://www.realestate.com.au/agency/jj-real-estate-sa-leabrook-KSFYVV",
"https://www.realestate.com.au/agency/jinsea-real-estate-kent-town-CVEZXX",
"https://www.realestate.com.au/agency/harcourts-beyond-holland-park-XRHSTR",
"https://www.realestate.com.au/agent/christina-cheng-1411522",
"https://www.realestate.com.au/agency/h-t-brisbane-pty-ltd-brisbane-DQLBQV",
"https://www.realestate.com.au/agency/position-property-services-pty-POTPAD",
"https://www.realestate.com.au/agency/raine-horne-coorparoo-camp-hill-LWMTYY",
"https://www.realestate.com.au/agency/joy-realty-sunnybank-MWJYOA",
"https://www.realestate.com.au/agency/auston-realty-EACHRR",
"https://www.realestate.com.au/agency/jenny-yang-realty-brisbane-city-OMWDMS",
"https://www.realestate.com.au/agency/dpg-property-group-melbourne-CVUSUP",
"https://www.realestate.com.au/agency/hamilton-finley-box-hill-IJMZNK",
"https://www.realestate.com.au/agency/ironfish-real-estate-melbourne-TJCDWC",
"https://www.realestate.com.au/agency/lj-hooker-city-residential-melbourne-RIZTKO",
"https://www.realestate.com.au/agency/aussie-home-real-estate-kew-FEHCRQ",
"https://www.realestate.com.au/agency/justin-james-blackburn-NMAKBJ",
"https://www.realestate.com.au/agency/harcourts-mitcham-LAZDKX",
"https://www.realestate.com.au/agency/ivy-real-estate-docklands-docklands-RIUNYL",
"https://www.realestate.com.au/agency/paragon-real-estate-carlton-RLJTFB",
"https://www.realestate.com.au/agency/royaland-real-estate-melbourne-IJQZJB",
"https://www.realestate.com.au/agency/sweeney-estate-agents-footscray-SWFFOO",
"https://www.realestate.com.au/agency/stockdale-leggo-glen-waverley-XSLGWY",
"https://www.realestate.com.au/agency/matrix-global-melbourne-carlton-LIFYVY",
"https://www.realestate.com.au/agency/harcourts-clayton-XRWCLB",
"https://www.realestate.com.au/agency/wise-earth-property-group-melbourne-QDMMTD",
"https://www.realestate.com.au/agency/paramount-residential-GSHAGI",
"https://www.realestate.com.au/agency/international-equities-carlton-IECCAR",
"https://www.realestate.com.au/agency/ray-white-oakleigh-XRWOAK",
"https://www.realestate.com.au/agency/sea-city-NTSONF",
"https://www.realestate.com.au/agency/stage-property-east-perth-JUPGAB",
"https://www.realestate.com.au/agency/augurum-property-mt-hawthorn-VPZEJJ",
"https://www.realestate.com.au/agency/century-21-grand-alliance-perth-XRWXND",
"https://www.realestate.com.au/agency/blue-ocean-real-estate-sydney-DVSWJR",
"https://www.realestate.com.au/agency/rma-eastwood-eastwood-RMGCGK",
"https://www.realestate.com.au/agency/callagher-estate-agents-annandale-CAZANN",
"https://www.realestate.com.au/agency/elanda-partners-real-estate-sydney-ZPCAPO",
"https://www.realestate.com.au/agency/everest-realty-pty-ltd-chatswood-ZPCAGW",
"https://www.realestate.com.au/agency/pw-realty-sydney-ODKSDL",
"https://www.realestate.com.au/agency/jif-realty-RCWWKA/",
"https://www.realestate.com.au/agency/anc-real-estate-pyrmont-AIKLIF",
"https://www.realestate.com.au/agency/noble-investment-group-QKQIKF",
"https://www.realestate.com.au/agency/pg-mode-realty-haymarket-PGMHAY",
"https://www.realestate.com.au/agency/ghk-real-estate-NOHFQX",
"https://www.realestate.com.au/agency/sec-property-group-sydney-VPCZGA",
"https://www.realestate.com.au/agency/perfect-living-realty-PYYJPB",
"https://www.realestate.com.au/agency/dragon-australia-sydney-VAZVIJ",
"https://www.realestate.com.au/agency/lj-hooker-chinatown-XLJSYF",
"https://www.realestate.com.au/agency/black-diamondz-property-concierge-sydney-KMXVVK",
"https://www.realestate.com.au/agency/ray-white-residential-sydney-cbd-SOMAZG",
"https://www.realestate.com.au/agency/greencliff-agency-sydney-ABCSYT",
"https://www.realestate.com.au/agency/boutique-property-agents-sydney-GOJVRX",
"https://www.realestate.com.au/agency/century-21-city-quarter-sydney-PXDSHF",
"https://www.realestate.com.au/agency/obsidian-property-sydney-FWTIVL",
"https://www.realestate.com.au/agency/sydney-residential-metro-pty-ltd-sydney-SYVSYD",
"https://www.realestate.com.au/agency/metro-realty-AQFNMV",
"https://www.realestate.com.au/agency/sydney-cove-property-the-rocks-PUHSYD",
"https://www.realestate.com.au/agency/chidiac-realty-wentworth-point-RMRTVE",
"https://www.realestate.com.au/agency/grand-sydney-realty-ultimo-FKKDTB",
"https://www.realestate.com.au/agency/laingsimmons-cbd-surry-hills-sydney-PKNMVT",
"https://www.realestate.com.au/agency/laing-real-estate-elizabeth-bay-XLSELI",
"https://www.realestate.com.au/agency/property-square-realty-sydney-LKUEQQ", ]
# print(len(start_urls))
# start_urls = list(set(start_urls))
# print(len(start_urls))
operatorDict = {'https://www.realestate.com.au/agency/korn-real-estate-campbelltown-rla-255949-ZWYBTV': 'Korn Real Estate', 'https://www.realestate.com.au/agency/jj-real-estate-sa-leabrook-KSFYVV': 'JJ Real Estate', 'https://www.realestate.com.au/agency/jinsea-real-estate-kent-town-CVEZXX': 'Jin Sea Real Estate', 'https://www.realestate.com.au/agency/harcourts-beyond-holland-park-XRHSTR': 'Harcourts Beyond Sunnybank & Holland Park', 'https://www.realestate.com.au/agent/christina-cheng-1411522': 'Q&C Management Pty Ltd', 'https://www.realestate.com.au/agency/h-t-brisbane-pty-ltd-brisbane-DQLBQV': 'H&T Brisbane Pty Ltd - Brisbane', 'https://www.realestate.com.au/agency/position-property-services-pty-POTPAD': 'New Techcom Marketing Enterprises Pty Ltd', 'https://www.realestate.com.au/agency/raine-horne-coorparoo-camp-hill-LWMTYY': 'Raine&Horne Coorparoo', 'https://www.realestate.com.au/agency/joy-realty-sunnybank-MWJYOA': 'Joy Realty', 'https://www.realestate.com.au/agency/auston-realty-EACHRR': 'Auston Realty', 'https://www.realestate.com.au/agency/jenny-yang-realty-brisbane-city-OMWDMS': 'Jenny Yang Realty', 'https://www.realestate.com.au/agency/dpg-property-group-melbourne-CVUSUP': 'Dynasty Property', 'https://www.realestate.com.au/agency/hamilton-finley-box-hill-IJMZNK': 'Hamilton Finley Box Hill', 'https://www.realestate.com.au/agency/ironfish-real-estate-melbourne-TJCDWC': 'Ironfish Real Estate - MELBOURNE', 'https://www.realestate.com.au/agency/lj-hooker-city-residential-melbourne-RIZTKO': 'LJ Hooker City Residential', 'https://www.realestate.com.au/agency/aussie-home-real-estate-kew-FEHCRQ': 'Aussie Home', 'https://www.realestate.com.au/agency/justin-james-blackburn-NMAKBJ': 'Justin James Real Estate', 'https://www.realestate.com.au/agency/harcourts-mitcham-LAZDKX': 'Harcourts - Mitcham（City&Boxhill)', 'https://www.realestate.com.au/agency/ivy-real-estate-docklands-docklands-RIUNYL': 'Ivy Real Estate Docklands - DOCKLANDS', 'https://www.realestate.com.au/agency/paragon-real-estate-carlton-RLJTFB': 'Paragon Real Estate', 'https://www.realestate.com.au/agency/royaland-real-estate-melbourne-IJQZJB': 'Royaland', 'https://www.realestate.com.au/agency/sweeney-estate-agents-footscray-SWFFOO': 'Sweeney Estate', 'https://www.realestate.com.au/agency/stockdale-leggo-glen-waverley-XSLGWY': 'Stockdale & Leggo - Glen Waverley', 'https://www.realestate.com.au/agency/matrix-global-melbourne-carlton-LIFYVY': 'Matrix Global- Carlton', 'https://www.realestate.com.au/agency/harcourts-clayton-XRWCLB': 'Harcourts - Clayton', 'https://www.realestate.com.au/agency/wise-earth-property-group-melbourne-QDMMTD': 'Wise Earth', 'https://www.realestate.com.au/agency/paramount-residential-GSHAGI': 'Paramount Residential', 'https://www.realestate.com.au/agency/international-equities-carlton-IECCAR': 'International Equities - CARLTON', 'https://www.realestate.com.au/agency/ray-white-oakleigh-XRWOAK': 'Ray White - Oakleigh', 'https://www.realestate.com.au/agency/sea-city-NTSONF': 'Sea & City Australia Investment Pty Ltd', 'https://www.realestate.com.au/agency/stage-property-east-perth-JUPGAB': 'Stage property', 'https://www.realestate.com.au/agency/augurum-property-mt-hawthorn-VPZEJJ': 'Augurum Property', 'https://www.realestate.com.au/agency/century-21-grand-alliance-perth-XRWXND': 'Century 21 Grand Alliance - PERTH', 'https://www.realestate.com.au/agency/blue-ocean-real-estate-sydney-DVSWJR': 'Blue Ocean Real Estate - Sydney', 'https://www.realestate.com.au/agency/rma-eastwood-eastwood-RMGCGK': 'RMA Real Estate', 'https://www.realestate.com.au/agency/callagher-estate-agents-annandale-CAZANN': 'Callagher Estate Agents', 'https://www.realestate.com.au/agency/elanda-partners-real-estate-sydney-ZPCAPO': 'Elanda Partners', 'https://www.realestate.com.au/agency/everest-realty-pty-ltd-chatswood-ZPCAGW': 'Everest Realty', 'https://www.realestate.com.au/agency/pw-realty-sydney-ODKSDL': 'PW Realty', 'https://www.realestate.com.au/agency/jif-realty-RCWWKA': 'JIF Group', 'https://www.realestate.com.au/agency/anc-real-estate-pyrmont-AIKLIF': 'ANC Real Estate - Pyrmont', 'https://www.realestate.com.au/agency/noble-investment-group-QKQIKF': 'Noble Investment Group（Sydney）', 'https://www.realestate.com.au/agency/pg-mode-realty-haymarket-PGMHAY': 'P&G Mode Realty', 'https://www.realestate.com.au/agency/ghk-real-estate-NOHFQX': 'GHK real estate P/L', 'https://www.realestate.com.au/agency/sec-property-group-sydney-VPCZGA': 'SEC property group', 'https://www.realestate.com.au/agency/perfect-living-realty-PYYJPB': 'Perfect Living Realty', 'https://www.realestate.com.au/agency/dragon-australia-sydney-VAZVIJ': 'Dragon Australia PTY Ltd.', 'https://www.realestate.com.au/agency/lj-hooker-chinatown-XLJSYF': 'LJ Hooker Chinatown', 'https://www.realestate.com.au/agency/black-diamondz-property-concierge-sydney-KMXVVK': 'Black Diamondz Property Concierge', 'https://www.realestate.com.au/agency/ray-white-residential-sydney-cbd-SOMAZG': 'Ray White Residential Sydney CBD', 'https://www.realestate.com.au/agency/greencliff-agency-sydney-ABCSYT': 'Greencliff Realty', 'https://www.realestate.com.au/agency/boutique-property-agents-sydney-GOJVRX': 'Boutique Property Agents', 'https://www.realestate.com.au/agency/century-21-city-quarter-sydney-PXDSHF': 'CENTURY 21 City Quarter', 'https://www.realestate.com.au/agency/obsidian-property-sydney-FWTIVL': 'Obsidian Property', 'https://www.realestate.com.au/agency/sydney-residential-metro-pty-ltd-sydney-SYVSYD': 'Sydney Residential\xa0Metro', 'https://www.realestate.com.au/agency/metro-realty-AQFNMV': 'Metro Realty', 'https://www.realestate.com.au/agency/sydney-cove-property-the-rocks-PUHSYD': 'Sydney Cove Property', 'https://www.realestate.com.au/agency/chidiac-realty-wentworth-point-RMRTVE': 'Chidiac Realty Sydney', 'https://www.realestate.com.au/agency/grand-sydney-realty-ultimo-FKKDTB': 'Grand Sydney Realty', 'https://www.realestate.com.au/agency/laingsimmons-cbd-surry-hills-sydney-PKNMVT': 'Laing+Simmons CBD Surry Hills', 'https://www.realestate.com.au/agency/laing-real-estate-elizabeth-bay-XLSELI': 'Laing Real Estate', 'https://www.realestate.com.au/agency/property-square-realty-sydney-LKUEQQ': 'Property Square'}
cityDict = {'https://www.realestate.com.au/agency/korn-real-estate-campbelltown-rla-255949-ZWYBTV': 'Adelaide',
                'https://www.realestate.com.au/agency/jj-real-estate-sa-leabrook-KSFYVV': 'Adelaide',
                'https://www.realestate.com.au/agency/jinsea-real-estate-kent-town-CVEZXX': 'Adelaide',
                'https://www.realestate.com.au/agency/harcourts-beyond-holland-park-XRHSTR': 'Brisbane',
                'https://www.realestate.com.au/agent/christina-cheng-1411522': 'Brisbane',
                'https://www.realestate.com.au/agency/h-t-brisbane-pty-ltd-brisbane-DQLBQV': 'Brisbane',
                'https://www.realestate.com.au/agency/position-property-services-pty-POTPAD': 'Brisbane',
                'https://www.realestate.com.au/agency/raine-horne-coorparoo-camp-hill-LWMTYY': 'Brisbane',
                'https://www.realestate.com.au/agency/joy-realty-sunnybank-MWJYOA': 'Brisbane',
                'https://www.realestate.com.au/agency/auston-realty-EACHRR': 'Brisbane',
                'https://www.realestate.com.au/agency/jenny-yang-realty-brisbane-city-OMWDMS': 'Brisbane',
                'https://www.realestate.com.au/agency/dpg-property-group-melbourne-CVUSUP': 'Melbourne',
                'https://www.realestate.com.au/agency/hamilton-finley-box-hill-IJMZNK': 'Melbourne',
                'https://www.realestate.com.au/agency/ironfish-real-estate-melbourne-TJCDWC': 'Melbourne',
                'https://www.realestate.com.au/agency/lj-hooker-city-residential-melbourne-RIZTKO': 'Melbourne',
                'https://www.realestate.com.au/agency/aussie-home-real-estate-kew-FEHCRQ': 'Melbourne',
                'https://www.realestate.com.au/agency/justin-james-blackburn-NMAKBJ': 'Melbourne',
                'https://www.realestate.com.au/agency/harcourts-mitcham-LAZDKX': 'Melbourne',
                'https://www.realestate.com.au/agency/ivy-real-estate-docklands-docklands-RIUNYL': 'Melbourne',
                'https://www.realestate.com.au/agency/paragon-real-estate-carlton-RLJTFB': 'Melbourne',
                'https://www.realestate.com.au/agency/royaland-real-estate-melbourne-IJQZJB': 'Melbourne',
                'https://www.realestate.com.au/agency/sweeney-estate-agents-footscray-SWFFOO': 'Melbourne',
                'https://www.realestate.com.au/agency/stockdale-leggo-glen-waverley-XSLGWY': 'Melbourne',
                'https://www.realestate.com.au/agency/matrix-global-melbourne-carlton-LIFYVY': 'Melbourne',
                'https://www.realestate.com.au/agency/harcourts-clayton-XRWCLB': 'Melbourne',
                'https://www.realestate.com.au/agency/wise-earth-property-group-melbourne-QDMMTD': 'Melbourne',
                'https://www.realestate.com.au/agency/paramount-residential-GSHAGI': 'Melbourne',
                'https://www.realestate.com.au/agency/international-equities-carlton-IECCAR': 'Melbourne',
                'https://www.realestate.com.au/agency/ray-white-oakleigh-XRWOAK': 'Melbourne',
                'https://www.realestate.com.au/agency/sea-city-NTSONF': 'Melbourne&The gold coast',
                'https://www.realestate.com.au/agency/stage-property-east-perth-JUPGAB': 'Perth',
                'https://www.realestate.com.au/agency/augurum-property-mt-hawthorn-VPZEJJ': 'Perth',
                'https://www.realestate.com.au/agency/century-21-grand-alliance-perth-XRWXND': 'Perth',
                'https://www.realestate.com.au/agency/blue-ocean-real-estate-sydney-DVSWJR': 'Sydney',
                'https://www.realestate.com.au/agency/rma-eastwood-eastwood-RMGCGK': 'Sydney',
                'https://www.realestate.com.au/agency/callagher-estate-agents-annandale-CAZANN': 'Sydney',
                'https://www.realestate.com.au/agency/elanda-partners-real-estate-sydney-ZPCAPO': 'Sydney',
                'https://www.realestate.com.au/agency/everest-realty-pty-ltd-chatswood-ZPCAGW': 'Sydney',
                'https://www.realestate.com.au/agency/pw-realty-sydney-ODKSDL': 'Sydney',
                'https://www.realestate.com.au/agency/jif-realty-RCWWKA': 'Sydney',
                'https://www.realestate.com.au/agency/anc-real-estate-pyrmont-AIKLIF': 'Sydney',
                'https://www.realestate.com.au/agency/noble-investment-group-QKQIKF': 'Sydney',
                'https://www.realestate.com.au/agency/pg-mode-realty-haymarket-PGMHAY': 'Sydney',
                'https://www.realestate.com.au/agency/ghk-real-estate-NOHFQX': 'Sydney',
                'https://www.realestate.com.au/agency/sec-property-group-sydney-VPCZGA': 'Sydney',
                'https://www.realestate.com.au/agency/perfect-living-realty-PYYJPB': 'Sydney',
                'https://www.realestate.com.au/agency/dragon-australia-sydney-VAZVIJ': 'Sydney',
                'https://www.realestate.com.au/agency/lj-hooker-chinatown-XLJSYF': 'Sydney',
                'https://www.realestate.com.au/agency/black-diamondz-property-concierge-sydney-KMXVVK': 'Sydney',
                'https://www.realestate.com.au/agency/ray-white-residential-sydney-cbd-SOMAZG': 'Sydney',
                'https://www.realestate.com.au/agency/greencliff-agency-sydney-ABCSYT': 'Sydney',
                'https://www.realestate.com.au/agency/boutique-property-agents-sydney-GOJVRX': 'Sydney',
                'https://www.realestate.com.au/agency/century-21-city-quarter-sydney-PXDSHF': 'Sydney',
                'https://www.realestate.com.au/agency/obsidian-property-sydney-FWTIVL': 'Sydney',
                'https://www.realestate.com.au/agency/sydney-residential-metro-pty-ltd-sydney-SYVSYD': 'Sydney',
                'https://www.realestate.com.au/agency/metro-realty-AQFNMV': 'Sydney',
                'https://www.realestate.com.au/agency/sydney-cove-property-the-rocks-PUHSYD': 'Sydney',
                'https://www.realestate.com.au/agency/chidiac-realty-wentworth-point-RMRTVE': 'Sydney',
                'https://www.realestate.com.au/agency/grand-sydney-realty-ultimo-FKKDTB': 'Sydney',
                'https://www.realestate.com.au/agency/laingsimmons-cbd-surry-hills-sydney-PKNMVT': 'Sydney',
                'https://www.realestate.com.au/agency/laing-real-estate-elizabeth-bay-XLSELI': 'Sydney',
                'https://www.realestate.com.au/agency/property-square-realty-sydney-LKUEQQ': 'Sydney'}
print(start_urls[29])
print(operatorDict.get(start_urls[29]))
print(cityDict.get("https://www.realestate.com.au/agency/sea-city-NTSONF"))