import scrapy
import re
import json
from scrapy.spiders import CrawlSpider, Rule
from scrapy.linkextractors import LinkExtractor
from scrapySchool_England_Ben.clearSpace import clear_space, clear_lianxu_space
from scrapySchool_England_Ben.items import ScrapyschoolEnglandBenItem
from scrapySchool_England_Ben.getItem import get_item
from scrapySchool_England_Ben.getTuition_fee import getTuition_fee
from scrapySchool_England_Ben.getIELTS import get_ielts
from scrapySchool_England_Ben.getStartDate import getStartDate
from scrapySchool_England_Ben.remove_tags import remove_class
from scrapySchool_England_Ben.getDuration import getIntDuration, getTeachTime

class NottinghamTrentUniversity_USpider(scrapy.Spider):
    name = "NottinghamTrentUniversity_U"
    start_urls = ["https://www.ntu.ac.uk/_resources/funnelback/rests/course-collection-json?level-of-study=Undergraduate&year-of-study=2019&study-option=Full-time&sort=title&start_rank=1"]
    # print(len(start_urls))
    # start_urls = list(set(start_urls))
    # print(len(start_urls))

    def parse(self, response):
        links = ["https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/arts-humanities/ug/2019-20/english-and-tesol",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/arts-humanities/ug/2019-20/english-and-media",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/arts-humanities/ug/2019-20/philosophy-and-english",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/arts-humanities/ug/2019-20/english-and-linguistics",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/arts-humanities/ug/2019-20/english-and-history",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/arts-humanities/ug/2019-20/english-and-film-and-television",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/arts-humanities/ug/2019-20/english",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/arts-humanities/ug/2019-20/film-and-television-and-history",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/arts-humanities/ug/2019-20/film-and-television-and-philosophy",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/arts-humanities/ug/2019-20/linguistics-and-philosophy",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/arts-humanities/ug/2019-20/linguistics-and-media",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/arts-humanities/ug/2019-20/philosophy-and-media",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/arts-humanities/ug/2019-20/media-and-international-relations",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/arts-humanities/ug/2019-20/media",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/arts-humanities/ug/2019-20/media-and-film-and-television",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/arts-humanities/ug/2019-20/media-production",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/arts-humanities/ug/2019-20/philosophy-and-history",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/arts-humanities/ug/2019-20/linguistics-and-history",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/arts-humanities/ug/2019-20/history",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/arts-humanities/ug/2019-20/history",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/arts-humanities/ug/2019-20/history-and-international-relations",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/arts-humanities/ug/2019-20/politics-and-history",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/arts-humanities/ug/2019-20/global-studies-and-tesol",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/arts-humanities/ug/2019-20/global-studies-and-media",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/arts-humanities/ug/2019-20/global-studies-and-philosophy",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/arts-humanities/ug/2019-20/global-studies-and-history",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/arts-humanities/ug/2019-20/global-studies-and-international-relations",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/arts-humanities/ug/2019-20/communication-and-society-and-global-studies",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/arts-humanities/ug/2019-20/communication-and-society-and-film-and-television",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/arts-humanities/ug/2019-20/english-and-communication-and-society",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/arts-humanities/ug/2019-20/communication-and-society-and-philosophy",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/arts-humanities/ug/2019-20/communication-and-society-and-media",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/arts-humanities/ug/2019-20/communication-and-society-and-linguistics",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/arts-humanities/ug/2019-20/history-and-communication-and-society",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/arts-humanities/ug/2019-20/creative-writing",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/law/ug/2019-20/law-with-psychology",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/law/ug/2019-20/international-law",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/law/ug/2019-20/law-full-time",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/law/ug/2019-20/business-law",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/law/ug/2019-20/law-with-business",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/law/ug/2019-20/law-with-criminology",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/mbiol-pharmacology",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/mbiol-pharmacology",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/mbiol-microbiology",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/mbiol-microbiology",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/mbiol-biochemistry",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/mbiol-biochemistry",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/mchem-chemistry",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/mchem-chemistry",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/msci-forensic-science",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/business/ug/2019-20/business-management-1-year-in-company",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/business/ug/2019-20/business-management-2-year-in-company",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/mcomp-computer-systems-engineering",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/mcomp-computer-systems-engineering",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/mcomp-computer-science",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/mcomp-computer-science",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/architecture-design-built-environment/ug/2019-20/meng-civil-engineering-design-and-construction",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/architecture-design-built-environment/ug/2019-20/meng-civil-engineering-design-and-construction",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-sport-and-exercise-science",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-sport-and-exercise-science",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/art-design/ug/2019-20/ba-hons-fashion-management",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/art-design/ug/2019-20/ba-hons-fashion-communication-and-promotion",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/art-design/ug/2019-20/ba-hons-fashion-management",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/art-design/ug/2019-20/ba-hons-fashion-marketing-and-branding",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/social-sciences/ug/2019-20/psychology",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/architecture-design-built-environment/ug/2019-20/bsc-property-finance-and-investment",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/social-sciences/ug/2019-20/psychology",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/architecture-design-built-environment/ug/2019-20/bsc-property-finance-and-investment",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/architecture-design-built-environment/ug/2019-20/bsc-property-development-and-planning",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/education/ug/2019-20/primary-education",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/architecture-design-built-environment/ug/2019-20/ba-interior-architecture-and-design",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/architecture-design-built-environment/ug/2019-20/ba-interior-architecture-and-design",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/architecture-design-built-environment/ug/2019-20/bsc-real-estate",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/architecture-design-built-environment/ug/2019-20/bsc-real-estate",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/social-sciences/ug/2019-20/social-work",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/architecture-design-built-environment/ug/2019-20/architecture",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/architecture-design-built-environment/ug/2019-20/bsc-building-surveying",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/architecture-design-built-environment/ug/2019-20/bsc-building-surveying",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-computer-science-games-technology",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-computer-science-games-technology",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/business/ug/2019-20/international-business",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/business/ug/2019-20/international-business",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/business/ug/2019-20/management-and-leadership",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/business/ug/2019-20/international-business-with-german",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/business/ug/2019-20/marketing",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/business/ug/2019-20/marketing",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/business/ug/2019-20/business-management-and-entrepreneurship",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/business/ug/2019-20/business-management-and-entrepreneurship",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/business/ug/2019-20/business-management-and-human-resources",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/business/ug/2019-20/business-management-and-human-resources",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/business/ug/2019-20/business-management-and-economics",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/business/ug/2019-20/business-management-and-economics",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/business/ug/2019-20/business-management-and-marketing",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/business/ug/2019-20/business-management-and-marketing",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/business/ug/2019-20/business-management-and-accounting-and-finance",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/business/ug/2019-20/business-management-and-accounting-and-finance",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/business/ug/2019-20/business",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/business/ug/2019-20/business",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/business/ug/2019-20/accounting-and-finance",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/business/ug/2019-20/accounting-and-finance",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/business/ug/2019-20/economics-with-international-finance-and-banking",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/business/ug/2019-20/economics-with-international-finance-and-banking",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/business/ug/2019-20/economics-with-business",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/business/ug/2019-20/economics",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/business/ug/2019-20/economics-with-business",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/business/ug/2019-20/economics",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-software-engineering",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-software-engineering",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-computer-science",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-computer-science",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-pharmacology",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-pharmacology",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-microbiology",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-microbiology",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-biomedical-science",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-biochemistry",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-biomedical-science",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-biochemistry",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-forensic-science",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-forensic-science",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/animal-rural-environmental-sciences/ug/2019-20/MGeog-geography",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/animal-rural-environmental-sciences/ug/2019-20/MGeog-geography",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/architecture-design-built-environment/ug/2019-20/beng-civil-engineering",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/architecture-design-built-environment/ug/2019-20/beng-civil-engineering",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-sport-science-and-management",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-sport-science-and-management",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/art-design/ug/2019-20/ba-hons-costume-design-and-making",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/art-design/ug/2019-20/ba-hons-fashion-knitwear-design-and-knitted-textiles",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/art-design/ug/2019-20/ba-hons-fashion-design",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/art-design/ug/2019-20/ba-hons-fashion-knitwear-design-and-knitted-textiles",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/art-design/ug/2019-20/ba-hons-fashion-accessory-design",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/confetti/ug/2019-20/bsc-hons-film-production-technology-2019",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/architecture-design-built-environment/ug/2019-20/bsc-product-design",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/social-sciences/ug/2019-20/politics",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/social-sciences/ug/2019-20/policing",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/architecture-design-built-environment/ug/2019-20/ba-product-design",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/architecture-design-built-environment/ug/2019-20/ba-product-design",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/confetti/ug/2019-20/bsc-hons-television-production-technology-2019",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/confetti/ug/2019-20/bsc-hons-visual-effects-production-tech-2019",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/art-design/ug/2019-20/ba-hons-textile-design",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/art-design/ug/2019-20/ba-hons-theatre-design",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/art-design/ug/2019-20/ba-hons-photography",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/confetti/ug/2019-20/ba-hons-music-performance-2019",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/social-sciences/ug/2019-20/international-relations",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/arts-humanities/ug/2019-20/journalism",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/confetti/ug/2019-20/bsc-hons-live-and-technical-events-2019",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/architecture-design-built-environment/ug/2019-20/bsc-quantity-surveying-and-commercial-management",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/social-sciences/ug/2019-20/sociology",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/confetti/ug/2019-20/bsc-hons-games-production-2019",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/social-sciences/ug/2019-20/psychology-with-criminology",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/social-sciences/ug/2019-20/psychology-with-criminology",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/confetti/ug/2019-20/ba-hons-games-art-2019",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/art-design/ug/2019-20/ba-hons-graphic-design",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/confetti/ug/2019-20/bsc-hons-audio-and-music-technology-2019",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/arts-humanities/ug/2019-20/broadcast-journalism",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/architecture-design-built-environment/ug/2019-20/ba-furniture-and-product-design",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/art-design/ug/2019-20/ba-hons-animation",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/architecture-design-built-environment/ug/2019-20/ba-furniture-and-product-design",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/art-design/ug/2019-20/ba-hons-fine-art",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/art-design/ug/2019-20/ba-hons-filmmaking",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/animal-rural-environmental-sciences/ug/2019-20/BSc-ecology-and-conservation",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/art-design/ug/2019-20/ba-hons-design-for-film-and-television",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/art-design/ug/2019-20/ba-hons-decorative-arts",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/animal-rural-environmental-sciences/ug/2019-20/BSc-ecology-and-conservation",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/social-sciences/ug/2019-20/criminology",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-computer-systems-engineering",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-computer-systems-engineering",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-computer-systems-networks",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-computer-systems-forensic-and-security",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-computer-systems-networks",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-computer-systems-forensic-and-security",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-pharmaceutical-and-medicinal-chemistry",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-pharmaceutical-and-medicinal-chemistry",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-chemistry",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-chemistry",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/animal-rural-environmental-sciences/ug/2019-20/bsc-environmental-science",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/animal-rural-environmental-sciences/ug/2019-20/bsc-environmental-science",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/animal-rural-environmental-sciences/ug/2019-20/BSc-wildlife-conservation",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/animal-rural-environmental-sciences/ug/2019-20/BSc-wildlife-conservation",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-information-systems",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-information-systems",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-information-and-communications-technology",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-information-and-communications-technology",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-digital-media-technology",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-digital-media-technology",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/animal-rural-environmental-sciences/ug/2019-20/zoo-biology",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/animal-rural-environmental-sciences/ug/2019-20/zoo-biology",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/animal-rural-environmental-sciences/ug/2019-20/BSc-animal-biology",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/animal-rural-environmental-sciences/ug/2019-20/BSc-animal-biology",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/animal-rural-environmental-sciences/ug/2019-20/BSc-geography",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/animal-rural-environmental-sciences/ug/2019-20/BSc-geography",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/animal-rural-environmental-sciences/ug/2019-20/BSc-geography-physical",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/animal-rural-environmental-sciences/ug/2019-20/BSc-geography-physical",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-computing",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-computing",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-exercise,-nutrition-and-health",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-exercise,-nutrition-and-health",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-coaching-and-sport-science",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-coaching-and-sport-science",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/social-sciences/ug/2019-20/politics-and-international-relations",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/social-sciences/ug/2019-20/psychology-with-sociology",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/social-sciences/ug/2019-20/psychology-with-sociology",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/social-sciences/ug/2019-20/health-and-social-care",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/social-sciences/ug/2019-20/youth-studies",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/social-sciences/ug/2019-20/youth-justice",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/architecture-design-built-environment/ug/2019-20/bsc-architectural-technology",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/architecture-design-built-environment/ug/2019-20/bsc-architectural-technology",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/architecture-design-built-environment/ug/2019-20/bsc-civil-engineering",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/education/ug/2019-20/childhood-learning-and-development",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/architecture-design-built-environment/ug/2019-20/bsc-civil-engineering",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/education/ug/2019-20/childhood-psychology",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/education/ug/2019-20/childhood-special-educational-needs-and-inclusion",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/education/ug/2019-20/education-special-educational-needs-and-inclusion",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/education/ug/2019-20/education-psychology",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/education/ug/2019-20/education-early-years",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/education/ug/2019-20/education",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/education/ug/2019-20/early-years",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/animal-rural-environmental-sciences/ug/2019-20/bsc-hons-food-science-and-technology",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/animal-rural-environmental-sciences/ug/2019-20/bsc-hons-food-science-and-technology",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/animal-rural-environmental-sciences/ug/2019-20/bsc-equine-sports-science",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/animal-rural-environmental-sciences/ug/2019-20/BSc-equestrian-psychology-and-sports-science",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/animal-rural-environmental-sciences/ug/2019-20/bsc-equine-sports-science",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/animal-rural-environmental-sciences/ug/2019-20/BSc-equestrian-psychology-and-sports-science",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/biological-sciences",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/biological-sciences",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/architecture-design-built-environment/ug/2019-20/bsc-construction-management",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/architecture-design-built-environment/ug/2019-20/bsc-construction-management",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-physics-and-mathematics",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-physics-and-mathematics",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/meng-biomedical-engineering",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/beng-biomedical-engineering",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/meng-biomedical-engineering",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/beng-biomedical-engineering",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-sport-science-and-mathematics",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-sport-science-and-mathematics",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-mathematics",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-mathematics",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/mmaths-mathematics",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/mmaths-mathematics",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/meng-sport-engineering",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/meng-sport-engineering",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/beng-sport-engineering",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/beng-sport-engineering",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-financial-mathematics",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-financial-mathematics",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-computer-science-and-mathematics",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-computer-science-and-mathematics",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/beng-electronic-engineering",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/meng-electronic-engineering",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/meng-electronic-engineering",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/beng-electronic-engineering",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/beng-mechanical-engineering",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/meng-mechanical-engineering",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/beng-mechanical-engineering",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/meng-mechanical-engineering",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-data-science",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-data-science",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/msci-physics",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-physics",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-physics",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-physics-with-astrophysics",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-physics-with-astrophysics",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-physics-with-nuclear-technology",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-physics-with-nuclear-technology",
"https://www.ntu.ac.uk/study-and-courses/courses/find-your-course/science-technology/ug/2019-20/bsc-applied-physics", ]
        print(len(links))
        links = list(set(links))
        print(len(links))

        for url in links:
            yield scrapy.Request(url, callback=self.parse_data, meta={'url': url})

    def parse_data(self, response):
        item = get_item(ScrapyschoolEnglandBenItem)
        item['university'] = "Nottingham Trent University"
        item['url'] = response.meta['url']
        print("===========================")
        print(response.url)
        print(response.meta['url'])
        try:


            alevel = response.xpath(
                "//div[@id='entry-requirements-0']//li[contains(text(),'A-level')]//text()").extract()
            clear_space(alevel)
            # print(alevel)
            if len(alevel) > 0:
                item['alevel'] = ''.join(alevel[0]).strip()
            print("item['alevel'] = ", item['alevel'])

            if len(item['alevel']) > 160:
                item['alevel'] = ''.join(item['alevel'][:161])
            print("item['alevel']1 = ", item['alevel'])


            yield item
        except Exception as e:
            with open("scrapySchool_England_Ben/error/"+item['university']+str(item['degree_type'])+".txt", 'a', encoding="utf-8") as f:
                f.write(str(e) + "\n" + response.url + "\n========================")
            print("异常：", str(e))
            print("报错url：", response.url)

