# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# https://doc.scrapy.org/en/latest/topics/items.html

import scrapy

# 2018/06/12    表tmp_school_major_uk
class ScrapyschoolEnglandItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    university = scrapy.Field()
    country = scrapy.Field()
    location = scrapy.Field()
    website = scrapy.Field()
    department = scrapy.Field()
    programme = scrapy.Field()
    major_type = scrapy.Field()         # int
    degree_level = scrapy.Field()       # int
    degree_type = scrapy.Field()
    full_time = scrapy.Field()
    taught = scrapy.Field()
    ucas_code = scrapy.Field()
    application_date = scrapy.Field()
    deadline = scrapy.Field()
    start_date = scrapy.Field()
    overview = scrapy.Field()
    duration = scrapy.Field()
    modules = scrapy.Field()
    application_fee = scrapy.Field()
    tuition_fee = scrapy.Field()
    teaching_assessment = scrapy.Field()
    career = scrapy.Field()
    academic_requirements = scrapy.Field()
    entry_requirements = scrapy.Field()
    chinese_requirements = scrapy.Field()
    accredited_university = scrapy.Field()
    Alevel = scrapy.Field()
    IB = scrapy.Field()
    GRE = scrapy.Field()
    GMAT = scrapy.Field()
    IELTS = scrapy.Field()
    IELTS_L = scrapy.Field()
    IELTS_S = scrapy.Field()
    IELTS_R = scrapy.Field()
    IELTS_W = scrapy.Field()
    TOEFL_code = scrapy.Field()
    TOEFL = scrapy.Field()
    TOEFL_L = scrapy.Field()
    TOEFL_S = scrapy.Field()
    TOEFL_R = scrapy.Field()
    TOEFL_W = scrapy.Field()
    interview = scrapy.Field()
    portfolio = scrapy.Field()
    application_documents = scrapy.Field()
    how_to_apply = scrapy.Field()
    school_test = scrapy.Field()
    SATRelated = scrapy.Field()
    other = scrapy.Field()
    working_experience = scrapy.Field()
    url = scrapy.Field()
    teacher_name = scrapy.Field()
    create_time = scrapy.Field()
    create_person = scrapy.Field()
    # update_time = scrapy.Field()
    spiderman = scrapy.Field()
    update_person = scrapy.Field()
    status = scrapy.Field()     # int
    import_status = scrapy.Field()      # int
    sid = scrapy.Field()        # int
    did = scrapy.Field()        # int
    pid = scrapy.Field()        # int
    batch_number = scrapy.Field()       # int

# 2018/06/26    表tmp_school_uk_yan
class ScrapyschoolEnglandItem1(scrapy.Item):
    university = scrapy.Field()
    location = scrapy.Field()
    department = scrapy.Field()
    programme_en = scrapy.Field()
    degree_type = scrapy.Field()
    degree_name = scrapy.Field()
    start_date = scrapy.Field()
    overview_en = scrapy.Field()
    teach_time = scrapy.Field()
    teach_type = scrapy.Field()
    duration = scrapy.Field()
    duration_per = scrapy.Field()
    modules_en = scrapy.Field()
    assessment_en = scrapy.Field()
    career_en = scrapy.Field()
    tuition_fee_pre = scrapy.Field()
    tuition_fee = scrapy.Field()
    require_chinese_en = scrapy.Field()
    require_chinese_school_en = scrapy.Field()
    rntry_requirements = scrapy.Field()
    degree_requirements = scrapy.Field()
    major_requirements = scrapy.Field()
    professional_background = scrapy.Field()
    ielts_desc = scrapy.Field()
    ielts = scrapy.Field()
    ielts_l = scrapy.Field()
    ielts_s = scrapy.Field()
    ielts_r = scrapy.Field()
    ielts_w = scrapy.Field()
    toefl_code = scrapy.Field()
    toefl_desc = scrapy.Field()
    toefl = scrapy.Field()
    toefl_l = scrapy.Field()
    toefl_s = scrapy.Field()
    toefl_r = scrapy.Field()
    toefl_w = scrapy.Field()
    gre = scrapy.Field()
    gmat = scrapy.Field()
    gre_sub = scrapy.Field()
    lsat = scrapy.Field()
    mcat = scrapy.Field()
    work_experience_desc_en = scrapy.Field()
    application_open_date = scrapy.Field()
    deadline = scrapy.Field()
    apply_pre = scrapy.Field()
    apply_fee = scrapy.Field()
    interview_desc_en = scrapy.Field()
    portfolio_desc_en = scrapy.Field()
    apply_desc_en = scrapy.Field()
    apply_documents_en = scrapy.Field()
    apply_proces_en = scrapy.Field()
    other = scrapy.Field()
    url = scrapy.Field()
    gatherer = scrapy.Field()
    batch_number = scrapy.Field()
    # create_time = scrapy.Field()
    update_time = scrapy.Field()