# -*- coding: utf-8 -*-
import scrapy
import re
from scrapy.spiders import CrawlSpider, Rule
from scrapy.linkextractors import LinkExtractor
from scrapySchool_England_Ben.clearSpace import clear_space, clear_lianxu_space
from scrapySchool_England_Ben.getItem import get_item
from scrapySchool_England_Ben.getTuition_fee import getTuition_fee
from scrapySchool_England_Ben.items import ScrapyschoolEnglandBenItem
import requests
from lxml import etree
from scrapySchool_England_Ben.getIELTS import get_ielts, get_toefl
from scrapySchool_England_Ben.getStartDate import getStartDate
from scrapySchool_England_Ben.remove_tags import remove_class
from scrapySchool_England_Ben.getDuration import getIntDuration


class LoughboroughUniversity_USpider(scrapy.Spider):
    name = "LoughboroughUniversity_U"
    # 研究领域链接
    start_urls = ["http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-artificial-intelligence-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-artificial-intelligence-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-mathematics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/communication-and-media-studies/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-mathematics-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-artificial-intelligence-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-artificial-intelligence-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-mathematics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/civil-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/civil-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/user-centred-design/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computing-and-management-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/textiles-innovation-and-design/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/systems-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/systems-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sports-technology-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/user-centred-design/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computing-and-management-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/textiles-innovation-and-design/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/systems-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/systems-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sports-technology-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/transport-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-coaching-and-physical-education/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/transport-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-coaching-and-physical-education/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/robotics-mechatronics-and-control-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-and-exercise-psychology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sociology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/social-psychology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/robotics-mechatronics-and-control-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/robotics-mechatronics-and-control-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-and-exercise-psychology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sociology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/social-psychology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/robotics-mechatronics-and-control-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-and-exercise-science/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sociology-with-criminology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-and-exercise-science/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sociology-with-criminology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/psychology-with-communication/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/psychology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/product-design-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/product-design-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/psychology-with-communication/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/psychology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/product-design-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/product-design-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/retailing-marketing-and-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/psychology-with-criminology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/product-design-and-technology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-history-and-international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/psychology-with-criminology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/product-design-and-technology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-history-and-international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-and-international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-with-theoretical-physics-mphys/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-with-theoretical-physics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-with-international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-mphys/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-with-history/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-with-economics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-and-international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-with-theoretical-physics-mphys/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-with-theoretical-physics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-with-international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-mphys/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-with-history/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-with-economics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/natural-sciences-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/natural-sciences-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/medicinal-and-pharmaceutical-chemistry-mchem/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mechanical-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/medicinal-and-pharmaceutical-chemistry-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mechanical-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-with-statistics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/natural-sciences-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/natural-sciences-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/medicinal-and-pharmaceutical-chemistry-mchem/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mechanical-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/medicinal-and-pharmaceutical-chemistry-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mechanical-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-with-statistics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-with-economics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-with-economics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-and-sport-science/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-and-physics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-and-physics-mphys/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-accounting-and-financial-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/materials-science-and-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-and-sport-science/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-and-physics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-and-physics-mphys/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-accounting-and-financial-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/materials-science-and-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/manufacturing-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/manufacturing-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/management-sciences/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/information-technology-management-for-business/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/information-technology-management-for-business-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/manufacturing-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/manufacturing-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/information-technology-management-for-business/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/information-technology-management-for-business-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/materials-science-and-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/international-business/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/materials-science-and-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/history-and-international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/information-management-and-business/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/industrial-design-and-technology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/human-biology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/graphic-communication-and-illustration/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-with-economics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/history/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/history-and-politics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/history-and-international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/information-management-and-business/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/industrial-design-and-technology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/human-biology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/graphic-communication-and-illustration/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-with-economics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/history/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/history-and-politics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/finance-and-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-with-digital-humanities/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-with-digital-humanities/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-ba/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-and-sport-science/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/fine-art/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-and-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/financial-mathematics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-ba/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-and-sport-science/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/fine-art/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-and-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/financial-mathematics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-and-sport-science/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/engineering-physics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-with-creative-writing/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-with-business-studies/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-and-sport-science/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/engineering-physics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-with-creative-writing/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-with-business-studies/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-literature/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-and-drama/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/engineering-physics-mphys/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-literature/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-and-drama/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/engineering-physics-mphys/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/engineering-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-electrical-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/engineering-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/economics-and-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-electrical-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-electrical-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/economics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/drama-with-english/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-computer-systems-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-computer-systems-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/economics-and-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-electrical-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/economics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/drama-with-english/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-computer-systems-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-computer-systems-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/civil-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemistry-mchem/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/civil-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemistry-mchem/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemistry-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemical-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemical-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/business-psychology-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/business-economics-and-finance-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biomaterials-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemistry-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemical-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemical-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/business-psychology-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/business-economics-and-finance-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biomaterials-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biological-sciences-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biomaterials-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/bioengineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/bioengineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biological-sciences-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biological-sciences-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biomaterials-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/bioengineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/bioengineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biological-sciences-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biochemistry-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biochemistry-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-materials-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biochemistry-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biochemistry-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-materials-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-materials-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/architecture-barch/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/air-transport-management-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/architectural-engineering-and-design-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-materials-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/air-transport-management-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/architectural-engineering-and-design-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/aeronautical-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/aeronautical-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/aeronautical-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/aeronautical-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/accounting-and-financial-management-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/construction-engineering-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computing-and-management-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/criminology-and-social-policy/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/drama/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computing-and-management-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/drama-with-business-studies/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/criminology-and-social-policy/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/drama/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/drama-with-business-studies/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/communication-and-media-studies/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-mathematics-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/commercial-management-and-quantity-surveying/", ]
    # print(len(start_urls))
    start_urls = list(set(start_urls))
    # print(len(start_urls))

    def parse(self, response):
        links = ["http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-artificial-intelligence-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-artificial-intelligence-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-mathematics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/communication-and-media-studies/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-mathematics-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-artificial-intelligence-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-artificial-intelligence-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-mathematics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/civil-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/civil-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/user-centred-design/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computing-and-management-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/textiles-innovation-and-design/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/systems-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/systems-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sports-technology-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/user-centred-design/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computing-and-management-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/textiles-innovation-and-design/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/systems-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/systems-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sports-technology-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/transport-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-coaching-and-physical-education/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/transport-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-coaching-and-physical-education/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/robotics-mechatronics-and-control-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-and-exercise-psychology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sociology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/social-psychology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/robotics-mechatronics-and-control-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/robotics-mechatronics-and-control-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-and-exercise-psychology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sociology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/social-psychology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/robotics-mechatronics-and-control-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-and-exercise-science/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sociology-with-criminology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-and-exercise-science/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sociology-with-criminology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/psychology-with-communication/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/psychology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/product-design-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/product-design-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/psychology-with-communication/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/psychology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/product-design-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/product-design-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/retailing-marketing-and-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/psychology-with-criminology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/product-design-and-technology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-history-and-international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/psychology-with-criminology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/product-design-and-technology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-history-and-international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-and-international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-with-theoretical-physics-mphys/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-with-theoretical-physics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-with-international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-mphys/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-with-history/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-with-economics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-and-international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-with-theoretical-physics-mphys/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-with-theoretical-physics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-with-international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-mphys/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-with-history/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-with-economics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/natural-sciences-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/natural-sciences-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/medicinal-and-pharmaceutical-chemistry-mchem/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mechanical-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/medicinal-and-pharmaceutical-chemistry-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mechanical-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-with-statistics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/natural-sciences-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/natural-sciences-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/medicinal-and-pharmaceutical-chemistry-mchem/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mechanical-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/medicinal-and-pharmaceutical-chemistry-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mechanical-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-with-statistics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-with-economics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-with-economics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-and-sport-science/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-and-physics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-and-physics-mphys/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-accounting-and-financial-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/materials-science-and-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-and-sport-science/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-and-physics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-and-physics-mphys/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-accounting-and-financial-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/materials-science-and-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/manufacturing-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/manufacturing-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/management-sciences/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/information-technology-management-for-business/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/information-technology-management-for-business-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/manufacturing-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/manufacturing-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/information-technology-management-for-business/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/information-technology-management-for-business-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/materials-science-and-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/international-business/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/materials-science-and-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/history-and-international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/information-management-and-business/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/industrial-design-and-technology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/human-biology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/graphic-communication-and-illustration/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-with-economics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/history/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/history-and-politics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/history-and-international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/information-management-and-business/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/industrial-design-and-technology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/human-biology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/graphic-communication-and-illustration/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-with-economics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/history/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/history-and-politics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/finance-and-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-with-digital-humanities/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-with-digital-humanities/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-ba/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-and-sport-science/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/fine-art/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-and-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/financial-mathematics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-ba/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-and-sport-science/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/fine-art/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-and-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/financial-mathematics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-and-sport-science/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/engineering-physics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-with-creative-writing/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-with-business-studies/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-and-sport-science/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/engineering-physics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-with-creative-writing/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-with-business-studies/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-literature/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-and-drama/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/engineering-physics-mphys/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-literature/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-and-drama/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/engineering-physics-mphys/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/engineering-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-electrical-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/engineering-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/economics-and-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-electrical-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-electrical-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/economics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/drama-with-english/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-computer-systems-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-computer-systems-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/economics-and-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-electrical-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/economics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/drama-with-english/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-computer-systems-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-computer-systems-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/civil-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemistry-mchem/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/civil-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemistry-mchem/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemistry-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemical-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemical-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/business-psychology-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/business-economics-and-finance-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biomaterials-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemistry-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemical-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemical-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/business-psychology-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/business-economics-and-finance-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biomaterials-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biological-sciences-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biomaterials-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/bioengineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/bioengineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biological-sciences-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biological-sciences-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biomaterials-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/bioengineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/bioengineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biological-sciences-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biochemistry-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biochemistry-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-materials-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biochemistry-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biochemistry-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-materials-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-materials-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/architecture-barch/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/air-transport-management-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/architectural-engineering-and-design-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-materials-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/air-transport-management-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/architectural-engineering-and-design-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/aeronautical-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/aeronautical-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/aeronautical-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/aeronautical-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/accounting-and-financial-management-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/construction-engineering-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computing-and-management-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/criminology-and-social-policy/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/drama/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computing-and-management-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/drama-with-business-studies/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/criminology-and-social-policy/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/drama/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/drama-with-business-studies/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/communication-and-media-studies/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-mathematics-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/commercial-management-and-quantity-surveying/", ]

        for url in links:
            yield scrapy.Request(url, callback=self.parse_data, meta={'url': url})

    def parse_data(self, response):
        item = get_item(ScrapyschoolEnglandBenItem)
        item['university'] = "Loughborough University"
        item['url'] = response.meta['url']
        print("===========================")
        print(response.url)
        print(response.meta['url'])
        try:

            tuition_fee = response.xpath(
                "//span[@class='list__text'][contains(text(),'International fee')]/../following-sibling::dd//text()").extract()
            clear_space(tuition_fee)
            # print('tuition_fee: ', tuition_fee)
            if len(tuition_fee) > 0:
                item['tuition_fee_pre'] = '£'
                item['tuition_fee'] = getTuition_fee(''.join(tuition_fee))
            print("item['tuition_fee_pre']: ", item['tuition_fee_pre'])
            print("item['tuition_fee']: ", item['tuition_fee'])

            alevel = response.xpath(
                "//dt[@class='list__item list__item--term'][contains(text(),'A-Level')]/following-sibling::dd//text()").extract()
            # alevel = response.xpath(
            #     "//span[@class='list__text'][contains(text(),'Typical offer')]/../following-sibling::dd//text()").extract()
            clear_space(alevel)
            if len(alevel) > 0:
                item['alevel'] = ''.join(alevel[0]).strip()
            print("item['alevel'] = ", item['alevel'])

            ib = response.xpath(
                "//dt[@class='list__item list__item--term'][contains(text(),'IB')]/following-sibling::dd//text()").extract()
            item['ib'] = ''.join(ib).strip()
            print("item['ib'] = ", item['ib'])

            yield item
        except Exception as e:
            with open("scrapySchool_England_Ben/error/"+item['university']+str(item['degree_type'])+".txt", 'a', encoding="utf-8") as f:
                f.write(str(e) + "\n" + response.url + "\n========================\n")
            print("异常：", str(e))
            print("报错url：", response.url)