# _*_ coding:utf-8 _*_
__author__ = 'zjl'
__date__ = '2018/7/6 14:30'
import scrapy,json
import re
from scrapy.spiders import CrawlSpider,Rule
from scrapy.linkextractors import LinkExtractor
from scrapySchool_England.getItem import get_item1
from scrapySchool_England.getTuition_fee import getTuition_fee
from scrapySchool_England.items import ScrapyschoolEnglandItem1
from scrapySchool_England.remove_tags import remove_class
from scrapySchool_England.getIELTS import get_ielts, get_toefl
from w3lib.html import remove_tags
from scrapySchool_England.clearSpace import  clear_space_str
from scrapySchool_England.translate_date import  tracslateDate
from scrapySchool_England.TranslateMonth import translate_month
class UniversityofNottinghamSpider(scrapy.Spider):
    name = 'UniversityofNottingham_p'
    allowed_domains = ['nottingham.ac.uk/']
    start_urls = []
    C= [
        'https://www.nottingham.ac.uk/pgstudy/courses/psychology/brain-imaging-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/biosciences/brewing-science-and-practice-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/business/business-analytics-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/business/business-and-management-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/medicine/medical-sciences/cancer-immunology-and-biotechnology-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/chemical-and-environmental-engineering/chemical-engineering-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/chemical-and-environmental-engineering/chemical-engineering-mtech.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/chemistry/chemistry-msc-(by-research).aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/modern-languages/chineseenglish-translation--interpreting-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/civil-engineering/civil-engineering-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/classics-and-archaeology/classical-literature-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/molecular-medical-sciences/clinical-and-molecular-microbiology-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/biosciences/clinical-nutrition-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/english/communication-and-entrepreneurship-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/modern-languages/comparative-literature-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/computer-science/computer-science-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/english/creative-writing-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/law/criminal-justice-llm.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/sociology-and-social-policy/criminology-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/culture-film-and-media/critical-theory-and-cultural-studies-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/culture-film-and-media/critical-theory-and-politics-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/biosciences/crop-improvement-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/culture-film-and-media/cultural-industries-and-entrepreneurship-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/architecture-and-built-environment/design-march.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/psychology/developmental-disorders-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/architecture-and-built-environment/digitalarchitecturetectonics.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/politics-and-international-relations/diplomacy-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/pharmacy/drug-discovery-and-pharmaceutical-sciences-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/pharmacy/drug-discovery-and-pharmaceutical-sciences-with-industrial-training-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/economics/economic-development-and-policy-analysis-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/economics/economics-and-econometrics-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/economics/economics-and-financial-economics-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/economics/economics-and-international-economics-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/economics/economics-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/education/education-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/education/educational-leadership-and-management-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/electrical-and-electronic-engineering/electrical-and-electronic-engineering-and-entrepreneurship-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/economics/economics-of-monetary-and-financial-policy-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/electrical-and-electronic-engineering/electrical-engineering-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/electrical-and-electronic-engineering/electrical-engineering-for-sustainable-and-renewable-energy-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/electrical-and-electronic-engineering/electronic-communications-and-computer-engineering-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/architecture-and-built-environment/energy-conversion-and-management-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/chemical-and-environmental-engineering/energy-process-systems-engineering-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/civil-engineering/engineering-surveying-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/english/english-literature-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/english/english-studies-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/chemical-and-environmental-engineering/environmental-engineering-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/business/entrepreneurship-innovation-management-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/architecture-and-built-environment/environmental-design-march.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/law/environmental-law-llm.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/culture-film-and-media/film-television-and-screen-industries-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/geography/environmental-management-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/business/finance-and-investment-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/mathematical-sciences/financial-and-computational-mathematics.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/law/european-law-llm.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/chemical-and-environmental-engineering/food-process-engineering-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/civil-engineering/environmental-management-and-earth-observation-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/biosciences/food-production-management-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/biosciences/food-science-and-engineering-mres.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/medicine/applied-psychology/forensic-and-criminological-psychology-(by-research)-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/sociology-and-social-policy/global-citizenship-identities-and-human-rights-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/politics-and-international-relations/governance-and-political-development-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/mathematical-sciences/gravity,-particles-and-fields-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/chemistry/green-and-sustainable-chemistry-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/medicine/applied-psychology/health-psychology-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/history/history-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/computer-science/human-computer-interaction-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/mechanical-materials-and-manufacturing-engineering/human-factors-and-ergonomics-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/business/human-resource-management-organisation-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/law/human-rights-law-llm.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/molecular-medical-sciences/immunology-and-allergy-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/business/industrial-engineering-and-operations-management-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/business/information-systems-and-operations-management-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/business/international-business-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/law/international-commercial-law-llm.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/law/international-criminal-justice-and-armed-conflict-llm.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/law/international-law-and-development-llm.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/law/international-law-llm.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/law/international-law,-security-and-terrorism-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/culture-film-and-media/international-media-communication-studies-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/politics-and-international-relations/international-relations-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/politics-and-international-relations/international-security-and-terrorism-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/sociology-and-social-policy/international-social-policy-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/modern-languages/languages-and-intercultural-studies-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/mechanical-materials-and-manufacturing-engineering/additive-manufacturing-and-3d-printing-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/english/literary-linguistics-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/business/logistics-and-supply-chain-management-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/business/management-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/education/learning-technology-and-education-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/medicine/applied-psychology/management-psychology-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/mathematical-sciences/mathematical-medicine-and-biology-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/business/mba-master-of-business-administration.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/law/master-of-laws-llm.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/sociology-and-social-policy/public-administration-mpa.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/medicine/medical-sciences/master-of-public-health-mph.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/business/marketing-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/medicine/medical-sciences/medical-education-mmedsci.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/medicine/applied-psychology/mental-health-research-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/molecular-medical-sciences/microbiology-and-immunology-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/mechanical-materials-and-manufacturing-engineering/mechanical-engineering-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/electrical-and-electronic-engineering/modern-telecommunications-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/nursing-midwifery-and-physiotherapy/msc-midwifery-studies-maternal-and-newborn-health.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/biosciences/nutritional-sciences-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/medicine/applied-psychology/occupational-psychology-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/medicine/medical-sciences/oncology-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/education/person-centred-experiential-counselling--psychotherapy-practice-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/physics-and-astronomy/physics-msc-(by-research).aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/philosophy/philosophy-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/nursing-midwifery-and-physiotherapy/physiotherapy-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/molecular-medical-sciences/molecular-genetics-and-diagnostics-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/politics-and-international-relations/politics-and-contemporary-history-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/electrical-and-electronic-engineering/power-electronics-and-drives-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/psychology/psychology-(conversion)-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/psychology/psychology-research-methods-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/medicine/medical-sciences/public-health-global-health-mph.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/mathematical-sciences/pure-mathematics-msc.aspx/pgstudy/courses/nursing-midwifery-and-physiotherapy/',
        'https://www.nottingham.ac.uk/pgstudy/courses/law/public-international-law-llm.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/sociology-and-social-policy/public-policy-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/architecture-and-built-environment/renewable-energy-and-architecture-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/nursing-midwifery-and-physiotherapy/research-methods-(health)-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/medicine/applied-psychology/rehabilitation-psychology-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/business/risk-management-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/mathematical-sciences/scientific-computation-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/sociology-and-social-policy/social-science-research-social-policy-social-work-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/politics-and-international-relations/slavery-and-liberation-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/business/social-science-research-management-business-studies-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/politics-and-international-relations/social-science-research-political-science-and-international-relations-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/law/social-science-research-socio-legal-studies-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/sociology-and-social-policy/social-science-research-sociology-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/education/special-and-inclusive-education-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/mathematical-sciences/statistics-and-applied-probability-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/mathematical-sciences/statistics-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/medicine/medical-sciences/stem-cell-technology-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/medicine/medical-sciences/sports-and-exercise-medicine-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/sociology-and-social-policy/social-work-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/civil-engineering/structural-engineering-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/business/supply-chain-and-operations-management-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/architecture-and-built-environment/sustainable-building-technology-collaborative-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/architecture-and-built-environment/sustainable-building-technology-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/architecture-and-built-environment/sustainable-energy-and-entrepreneurship-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/faculty-of-engineering/sustainable-energy-engineering-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/electrical-and-electronic-engineering/sustainable-transportation-and-electrical-power-systems-erasmus-mundus-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/education/teaching-chinese-to-speakers-of-other-languages-(tcsol)-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/modern-languages/translation-studies-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/education/teaching-english-to-speakers-of-other-languages-(tesol)-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/classics-and-archaeology/the-visual-culture-of-classical-antiquity-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/civil-engineering/transportation-infrastructure-engineering-msc-sustainable-highways-sustainable-railways.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/architecture-and-built-environment/sustainable-urban-design-march.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/art-history/visual-culture-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/medicine/applied-psychology/work-and-organisational-psychology-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/english/viking-and-anglo-saxon-studies-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/business/accounting-and-finance-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/mechanical-materials-and-manufacturing-engineering/advanced-materials-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/biosciences/advanced-dietetic-practice-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/nursing-midwifery-and-physiotherapy/advanced-nursing-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/mechanical-materials-and-manufacturing-engineering/aerospace-technologies-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/american-and-canadian-studies/american-studies-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/classics-and-archaeology/ancient-history-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/biosciences/animal-nutrition-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/biosciences/applied-biomolecular-technology-in-the-pharmaceutical-biotechnology-and-food-industries-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/biosciences/applied-biopharmaceutical-biotechnology-and-entrepreneurship-(abbe)-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/english/applied-linguistics-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/medicine/medical-sciences/applied-sport-and-exercise-medicine-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/english/applied-linguistics-and-english-language-teaching-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/classics-and-archaeology/archaeological-science-msc-(by-research).aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/classics-and-archaeology/archaeology-ma-(by-research).aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/art-history/art-history-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/politics-and-international-relations/asian-and-international-studies-ma.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/medicine/medical-sciences/assisted-reproduction-technology-mmedsci.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/business/banking-and-finance-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/economics/behavioural-economics-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/faculty-of-engineering/bioengineering-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/faculty-of-engineering/bioengineering-biomaterials-and-biomechanics-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/biology/biological-photography-and-imaging-msc.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/electrical-and-electronic-engineering/biophotonics-msc-by-research.aspx',
        'https://www.nottingham.ac.uk/pgstudy/courses/biosciences/biotechnology-msc.aspx'
    ]
    for i in C:
        start_urls.append(i)
    def parse(self, response):
        pass
        item = get_item1(ScrapyschoolEnglandItem1)

        #1.university
        university = 'University of Nottingham'
        # print(university)

        #2.url
        url = response.url
        # print(url)

        #3.programme_en
        programme_en = response.xpath('//*[@id="pageTitle"]/h1').extract()
        programme_en = ''.join(programme_en)
        programme_en = remove_tags(programme_en)
        # print(programme_en)

        #4.degree_type
        degree_type = 2

        #5.degree_name
        if '(' in programme_en:
            try:
                programme_list = programme_en.replace('(Distance eLearning)','').replace('(by Research)','').replace('(Global Health)','').replace('(Distance-learning)','').replace(': Sustainable Highways / Sustainable Railways','')
            except:
                programme_list = programme_en
        else:
            programme_list = programme_en
        # degree_name = programme_list.split()[-1]
        # programme_en = programme_en.replace(degree_name,'').strip()
        # print(programme_en)
        # print(degree_name)

        #6.duration #7.duration_per #8.teach_time
        duration_list = response.xpath("//*[contains(text(),'Duration')]//following-sibling::*").extract()
        duration_list = ''.join(duration_list)
        duration_list = remove_tags(duration_list)
        # print(duration)
        try:
            duration = re.findall('\d+',duration_list)[0]
        except:
            duration = None
        if 'year' in duration_list:
            duration_per = 1
        elif 'month' in duration_list:
            duration_per = 3
        else:
            duration_per = 1
        if 'full-time' in duration_list:
            teach_time = 'Full time'
        else:
            teach_time = 'Part time'

        #9.rntry_requirements
        rntry_requirements = response.xpath("//*[contains(text(),'Entry requirements')]//following-sibling::*").extract()
        rntry_requirements = ''.join(rntry_requirements)
        rntry_requirements = remove_tags(rntry_requirements)
        # print(rntry_requirements)

        #10.ielts 11121314
        ielts_list = response.xpath("//*[contains(text(),'IELTS')]//following-sibling::*").extract()
        ielts_list = ''.join(ielts_list)
        ielts_list = remove_tags(ielts_list)
        try:
            ielts= re.findall('\d\.\d',ielts_list)
        except:
            ielts = None
        if len(ielts) == 2:
            a = ielts[0]
            b = ielts[1]
            ielts = a
            ielts_r = b
            ielts_w = b
            ielts_s = b
            ielts_l = b
        else:
            ielts = 6.5
            ielts_r =  6.0
            ielts_w =  6.0
            ielts_s =  6.0
            ielts_l =  6.0
        # print(ielts,ielts_r,ielts_w,ielts_s,ielts_l)

        #15.start_date
        start_date = response.xpath("//*[contains(text(),'Start date')]//following-sibling::*").extract()
        start_date = ''.join(start_date)
        start_date = remove_tags(start_date)
        # print(start_date)
        if 'September and February' in start_date:
            start_date = '2018-9,2019-2'
        elif 'September and January' in start_date:
            start_date = '2018-9,2019-1'
        elif 'September, January and April' in start_date:
            start_date = '2018-9,2019-1,2019-4'
        else:
            start_date = translate_month(start_date)
            start_date = '2018-'+ str(start_date)
        # print(start_date)

        #16.department
        department = response.xpath("//*[contains(text(),'School/department')]//following-sibling::*").extract()
        department = ''.join(department)
        department = remove_tags(department)
        department = clear_space_str(department)
        # print(department)

        #17.location
        location = response.xpath("//div[contains(text(),'Campus')]//following-sibling::*").extract()
        location = ''.join(location)
        location = remove_tags(location)
        location = clear_space_str(location)
        if len(location) > 100:
            location = 'Jubilee Campus'
        else:
            pass
        # print(location)

        #18.overview_en
        overview_en = response.xpath("//*[contains(text(),'Overview')]//following-sibling::*").extract()
        overview_en = ''.join(overview_en)
        overview_en = remove_class(overview_en)
        overview_en = clear_space_str(overview_en)
        # print(overview_en)

        #19.modules_en
        modules_en = response.xpath('//*[@id="Modules"]').extract()
        modules_en = ''.join(modules_en)
        modules_en = remove_class(modules_en)
        # print(modules_en)

        #20.career_en
        career_en = response.xpath("//*[contains(text(),'Careers')]/../following-sibling::*").extract()
        career_en = ''.join(career_en)
        career_en = remove_class(career_en)
        # print(career_en)

        #21.other
        other = 'https://www.nottingham.ac.uk/fees/tuitionfees/201819/pgt-courses-2018-19.aspx'

        #22.tuition_fee_pre
        tuition_fee_pre = '£'

        #23.tuition_fee
        list1 = ['Nutritional Sciences',
'Nutritional Sciences',
'Clinical Nutrition',
'Clinical Nutrition',
'Nutrition',
'Advanced Dietetic Practice',
'Advanced Dietetic Practice',
'Advanced Dietetic Practice',
'Plant Genetic Manipulation',
'Applied Biomolecular Technology',
'Animal Nutrition',
'Animal Nutrition',
'Crop Improvement',
'Crop Improvement',
'Agrifood^',
'Agrifood^',
'Agrifood^',
'Sensory Science^^',
'Food Process Engineering',
'Food Production Management',
'Food Production Management',
'Brewing Science',
'Brewing Science',
'Brewing Science and Practice',
'Brewing: Principles and Practice (E Learning)',
'Applied Biopharmaceutical Biotechnology and  Entrepreneurship   (ABBE)',
'Biotechnology',
'Social Science Research (Management and   Business Studies)',
'International Business',
'Corporate Social Responsibility',
'Business Administration',
'Executive MBA',
'Corporate Strategy and Governance',
'Entrepreneurship, Innovation and Management',
'Business Administration',
'Corporate Governance',
'Business Administration',
'Sustainable Business',
'Risk Management',
'Management',
'Business Analytics',
'Executive (Healthcare)',
'Industrial Engineering and Operations  Management    ',
'Operations Management',
'Supply Chain and Operations Management',
'Logistics and Supply Chain Management',
'Information Systems and Operations  Management',
'Management Science and Operations  Management',
'Banking and Finance',
'Finance and Investment',
'Marketing',
'Human Resources Management and Organisation',
'Business and Management',
'Accounting and Finance',
'Business and Economy of Contemporary China',
'Accounting and Finance for Contemporary China',
'Management in Contemporary China and Emerging   Markets',
'Management in Contemporary China and Emerging   Markets',
'Banking and Financial Markets in Contemporary   China',
'Green and Sustainable Chemistry',
'Digital Technologies for Language Teaching  (Distance  Learning)',
'Professional Communication',
'Professional Communication',
'Professional Communication',
'Comparative Literature',
'Classical Literature',
'The Visual Culture of classical Antiquity',
'Ancient History',
'Art History',
'Visual Culture',
'History',
'Russian and East European Studies (Research   Track)',
'Philosophy',
'Theology and Religious Studies',
'Church History',
'Systematic and Philosophical Theology (distance   learning)',
'Medieval Studies',
'Translation Studies',
'Languages and Intercultural Studies',
'Chinese/English Translation & Interpreting',
'Chinese/English Translation & Interpreting',
'Chinese/English Translation & Interpreting',
'American Studies',
'Cultural Industries and Entrepreneurship',
'Critical Theory and Politics',
'International Media & Communications Studies',
'International Media & Communications Studies',
'International Media & Communications Studies',
'Critical Theory',
'Critical Theory and Cultural Studies',
'Critical Theory and Cultural Studies',
'Film, Television & Screen Industries',
'Slovene',
'Computer Science',
'Computer Science (2 year)',
'Human Computer Interaction',
'Economics ',
'Economics',
'Economics and Development Economics',
'Economic Development and Policy Analysis',
'Applied Economics and Financial Economics',
'Economics of Monetary and Financial Policy',
'Economics and Financial Economics',
'Economics and Econometrics',
'Economics and International Economics',
'Behavioural Economics',
'Social Science Research (Economics)',
'Social Science Research (Education)',
'Trauma Studies',
'Combined Science',
'Education',
'Teaching English to Speakers of Other  Languages  (TESOL)',
'Teaching English for Academic Purposes ',
'Special and Inclusive Education',
'Special and Inclusive Education (by web-based  distance  learning)',
'Learning, Technology and Education',
'Educational Leadership and Management',
'TESOL by web-based distance learning',
'Educational Leadership and Management (by   distance  learning)',
'Learning, Technology and Education (online)',
'Mentoring and Coaching Beginning Teachers',
'Mentoring and Coaching Beginning Teachers  (Cohort  based)',
'Education (Cohort based)',
'Person-Centred Experiential Counselling &   Psychotherapy^^',
'Creativity, Arts, Literacies and Learning',
'Creativity, Arts, Literacies and Learning',
'Educational Studies by Cohort',
'Education Sciences and Learning Technology (PUAS)',
'Education Sciences and Learning Technology   (PUAS)',
'Education (flexible)',
'Education (flexible) Commonwealth Cohort',
'Education (International)',
'Education (International)',
'PGCE Secondary',
'PGCE Secondary (Teach First)',
'PGCE Secondary',
'PGCE Secondary (School Direct Salaried)',
'PGCE Primary',
'PGCE Primary',
'PGCE Primary',
'PGCE Primary (School Direct Salaried)',
'Secondary Physics with Mathematics',
'Primary Generalist',
'Secondary Mathematics',
'Teaching Chinese to Speakers of Other  Languages  (TCSOL)',
'International Student Advice and Support',
'Architecture (Conversion)^',
'Sustainable Energy and Entrepreneurship',
'Professional Practice in Architecture (Part 3)^',
'Sustainable Tall Buildings',
'Sustainable Urban Design',
'Design',
'Renewable Energy and Architecture',
'Renewable Energy and Architecture',
'Environmental Design',
'Digital Architecture and Tectonics',
'Sustainable Building Technology (Collaboration)',
'Sustainable Building Technology',
'Sustainable Building Technology',
'Sustainable Building Design^^',
'Sustainable Building Design ^^',
'Energy Conversion and Management',
'Additive Manufacturing & 3D Printing',
'Energy Conversion and Management',
'Chemical Engineering',
'Environmental and Resource Engineering',
'Environmental Engineering',
'Environmental Engineering',
'Chemical Engineering',
'Civil Engineering: Structural Engineering',
'Civil Engineering: Highways and Transportation',
'Transportation Infrastructure Engineering',
'Civil Engineering',
'Engineering Surveying with Geographical  Information  Science',
'Environmental Management and Earth Observation',
'Electrical and Electronic Engineering and   Entrepreneurship',
'Electrical and Electronic Engineering',
'Electrical and Electronic Engineering (pre-Masters)',
'Electrical Engineering',
'Power Electronics and Drives',
'Power Electronics and Drives',
'Sustainable Transportation and Electrical Power   Systems  (Erasmus Mundus)',
'Power Electronics and Drives (Talca)',
'Electronic Communications and Computer   Engineering',
'Electronic Communications and Computer   Engineering',
'Photonic and Optical Engineering',
'Photonic and Optical Engineering',
'Modern Telecommunications',
'Electrical Engineering for Sustainable and  Renewable  Energy',
'Electrical Engineering for Sustainable and  Renewable  Energy',
'Bioengineering',
'Bioengineering: Biomaterials and Biomechanics',
'Bioengineering',
'Sustainable Energy Engineering',
'Efficient Fossil Energy Technologies',
'Energy Process Systems Engineering',
'Usability and Human Computer Interaction ',
'Mechanical Engineering',
'Aerospace Technologies',
'Manufacturing Engineering and Management',
'Advanced Materials',
'Human Factors and Ergonomics',
'Applied Ergonomics and Human Factors (Distance  Learning)',
'Applied Ergonomics and Human Factors (Distance  Learning)',
'Social Science Research (Applied Linguistics)',
'Applied Linguistics',
'Applied Linguistics by Web Based Distance Learning',
'Applied Linguistics and English Language Teaching',
'Applied Linguistics & English Language Teaching by Web   Based  Learning',
'English Studies by Web Based Distance Learning',
'Viking and Anglo-Saxon Studies',
'English Studies',
'Literary Linguistics',
'Literary Linguistics by Web Based Learning',
'Modern English Language by Web Based Distance   Learning',
'Modern English Language',
'English Literature',
'Health Communication by Web Based Distance   Learning',
'Communication and Entrepreneurship',
'Creative Writing',
'Environmental Management',
'Environmental Management',
'Environmental Management ',
'Environmental Management',
'Human Geography',
'Human Geography',
'Landscape and Culture',
'Landscape and Culture',
'Physiotherapy',
'Physiotherapy',
'Physiotherapy',
'Research Methods (Health Studies)',
'Advanced Nursing',
'Advanced Nursing',
'Midwifery',
'Midwifery',
'Maternal and Newborn Health',
'Maternal and Newborn Health',
'Cognitive Behavioural Therapy',
'Cognitive Behavioural Therapy',
'Advanced Clinical Practice',
'Advanced Clinical Practice',
'Practice Teacher in Health and Social Care',
'Advanced Clinical Skills',
'Health and Social Care',
'Research Methods (Health)',
'Quality and Patient Safety Improvement',
'Quality and Patient Safety Improvement',
'Quality and Patient Safety Improvement',
'Social Science Research (Socio-Legal Studies)',
'Law',
'European Law',
'International Law',
'International Law and Development',
'Public International Law',
'International Commercial Law',
'International Criminal Justice and Armed Conflict',
'Environmental Law',
'International Human Rights law',
'Human Rights Law',
'Maritime Law',
'Criminal Justice',
'Public Procurement Law and Policy',
'Public Procurement Law and Policy',
'Public Procurement Law and Policy',
'Law and Environmental Science',
'International Law, Security and Terrorism',
'Integrated Physiology in Health and Disease',
'Immunology and Allergy',
'Molecular Genetics and Diagnostics',
'Clinical and Molecular Microbiology',
'Clinical and Molecular Microbiology',
'Clinical and Molecular Microbiology',
'Clinical Microbiology',
'Clinical Microbiology',
'Clinical Microbiology',
'Molecular Pathology (distance learning)',
'Molecular Medical Microbiology',
'Molecular Medical Microbiology',
'Clinical Microbiology (Distance Learning)',
'Clinical Microbiology (Distance Learning)',
'Clinical Microbiology (Distance Learning)',
'Microbiology and Immunology',
'Biological Photography and Imaging',
'Gravity, Particles and Fields',
'Pure Mathematics',
'Mathematical Medicine and Biology',
'Statistics',
'Statistics and Applied Probability',
'Scientific Computation',
'Financial and Computational Mathematics',
'Applied Sport and Exercise Medicine',
'Assisted Reproduction Technology',
'Applied Sport and Exercise Medicine',
'Applied Sport and Exercise Medicine',
'Cancer Immunology and Biotechnology',
'Sports and Exercise Medicine',
'Public Health',
'Oncology',
'Public Health',
'Public Health',
'Sports and Exercise Medicine',
'Oncology',
'Public Health (Global Health)',
'Public Health (Global Health)',
'Oncology^',
'Mental Health Research',
'Mental Health Research',
'Mental Health Research',
'Medical Education',
'Medical Education',
'Medical Education',
'Stem Cell Technology and Regenerative Medicine',
'Rehabilitation Psychology',
'Work and Organisational Psychology',
'Developmental Disorders',
'Rehabilitation Psychology',
'Work and Organsational Psychology',
'Occupational Psychology',
'Occupational Psychology',
'Workplace Health & Wellbeing ',
'Workplace Health & Wellbeing ',
'Workplace Health & Wellbeing ',
'Health Psychology',
'Health Psychology',
'Management Psychology',
'Management Psychology',
'Drug Discovery and Pharmaceutical Sciences',
'Drug Discovery and Pharmaceutical Sciences with   Industrial Training (2 years) ^ ',
'Asian and International Studies',
'International Security and Terrorism',
'International Relations',
'International Relations (Research Track)',
'Governance and Political Development',
'Governance and Political Development (2yr)',
'Slavery and Liberation',
'Slavery and Liberation',
'Slavery and Liberation',
'Diplomacy',
'Social Science Research (Political Science and   International  Relations)',
'Politics and Contemporary History',
'Psychology (Conversion)',
'Psychology (Conversion)',
'Psychology Research Methods',
'Brain Imaging',
'Social Science Research (Psychology)',
'Criminology',
'Criminology',
'Global Citizenship, Identities & Human Rights',
'Global Citizenship, Identities & Human Rights',
'International Social Policy',
'International Social Policy',
'Public Policy',
'Public Administration',
'Public Administration',
'Public Policy',
'Social Work',
'Social Work',
'Social Welfare',
'Social Welfare',
'Social Welfare',
'Research Methods (Social Work)',
'Social Science Research (Social Policy & Social  Work)',
'Social Science Research (Sociology)',
'Veterinary Education',
'Veterinary Medicine & Surgery',
'Veterinary Physiotherapy',
'Veterinary Physiotherapy',
'Veterinary Physiotherapy',
'Nursing (GEN - Adult)',
'Nursing (GEN - Child)',
'Nursing (GEN - Mental Health)']
        listvalue = [' £22,410',
' £14,940',
' £22,410',
' £14,940',
' £7,470',
' £22,410',
' £14,940',
' £7,470',
' £21,285',
' £22,410',
' £22,410',
' £14,940',
' £22,410',
' £14,190',
' n/a',
' n/a',
' n/a',
' £9,240',
' £21,285',
' £14,940',
' £22,410',
' £22,410',
' £14,190',
' £22,410',
' £7,470',
' £22,410',
' £22,410',
' £16,695',
' £19,800',
' £16,965',
' £8,325',
' £24,975',
' £16,965',
' £19,800',
' £24,975',
' £16,695',
' £16,650',
' £16,695',
' £19,800',
' £19,800',
' £22,500',
' £24,975',
' £19,800 ',
' £19,800',
' £19,800',
' £19,800',
' £19,800',
' £19,800',
' £22,500',
' £22,500',
' £22,500',
' £19,800',
' £19,800',
' £22,500',
' £20,160',
' £20,160',
' £20,160',
' £13,440',
' £20,160',
' £21,285 ',
' £7,290',
' £9000',
' £6000',
' £3000',
' £16,695',
' £16,695',
' £16,695',
' £16,695',
' £16,695',
' £16,695',
' £16,695',
' £16,695',
' £16,695',
' £11,130',
' £16,695',
' £16,695',
' £16,695',
' £16,695 ',
' £16,695 ',
' £16,695',
' £11,130',
' £5,565 ',
' £16,695 ',
' £16,695 ',
' £16,695',
' £16,695',
' £11,130',
' £5,565',
' £11,130',
' £16,695',
' £11,130',
' £16,695 ',
' £5,565',
' £21,285',
' £21,285',
' £21,285',
' £16,965',
' £16,965',
' £16,965',
' £16,965',
' £16,965',
' £22,500',
' £16,965',
' £16,965',
' £16,965',
' £16,965',
' £16,695',
' £16,695',
' £16,695',
' £16,695',
' £16,695',
' £16,695',
' £9,630',
' £16,695',
' £10,710',
' £16,695',
' £16,695',
' £9,630',
' £10,710',
' £10,710',
' £5,565',
' ^',
' ^',
' £16,695',
' £16,695',
' £5,565',
' ^',
' ^',
' ^',
' £10,710',
' ^',
' ^',
' £3,840',
' £16,695',
' ^',
' £16,695',
' ^',
' £16,695',
' £16,695',
' £16,695',
' ^',
' £16,695',
' £16,695',
' £16,695',
' £16,695 ',
' £5,565',
' £2,190',
' £20,160',
' £2,190',
' £16,695',
' £16,695 ',
' £16,695 ',
' £11,130',
' £16,695',
' £16,695 ',
' £16,695 ',
' £16,695 ',
' £16,695',
' £11,130',
' tba ',
' tba',
' £16,695 ',
' £21,285',
' £11,130',
' £21,285',
' £14,190',
' £21,285',
' £14,190',
' £14,190',
' £21,285',
' £21,285 ',
' £21,285',
' £21,285',
' £21,285',
' £21,285',
' £21,285',
' £21,285 ',
' £14,985',
' £21,285',
' £21,285',
' £14,190 ',
'^',
' £21,285',
' £21,285',
' £14,190',
' £21,285',
' £14,190 ',
' £21,285',
' £21,285',
' £13,500 ',
' £21,285',
' £21,285 ',
' £14,190',
' £21,285 ',
' £20,195',
' £20,195',
' £6,615 ',
' £21,285 ',
' £21,285 ',
' £14,190',
' £21,285',
' £21,285 ',
' £10,710',
'  £6,615',
'  £16,695',
' £16,695',
' £9,000',
' £16,695',
' £9,000',
' £9,000',
' £16,695 ',
' £16,695 ',
' £16,695 ',
' £9,000',
' £9,000',
' £16,695',
' £16,695 ',
' £9,000',
' £20,160',
' £16,695 ',
' £13,290',
' £19,935 ',
' £14,190',
' £21,285',
' £16,695 ',
' £11,130 ',
' £16,695',
' £11,130',
' £16,695',
' £11,130',
' £5,565',
' £16,695',
' £16,695',
' £11,130',
' £11,130',
' £16,695',
' £16,695',
' £11,130',
' n/a',
' n/a',
' n/a',
' n/a',
' n/a',
' n/a',
' £5,565',
' £16,695',
' £16,695',
' £11,130',
' £5,565',
' £16,695',
' £16,695',
' £16,695',
' £16,695',
' £16,695',
' £16,695',
' £16,695',
' £16,695',
' £16,695',
' £3,225',
' £16,695',
' £16,695',
' £16,695',
' £9,675',
' £6,450',
' £3,225',
' £16,695',
' £17,415',
' £22,410',
' £21,285',
' £21,285',
' £21,285',
'£14,190',
' £7,095',
' £21,285',
' £14,190',
' £7,095',
' £7,830',
' £21,285',
' £14,190',
' £21,285',
' £14,190',
' £7,095',
' £21,285',
' £23,490',
' £16,695',
' £16,695',
' £16,695',
' £17,415',
' £17,415',
' £16,695',
' £21,285',
' £19,935',
' £29,250',
' £13,290',
' £6,645',
' £23,490',
' £23,490',
' £19,935',
' £23,490',
' £6,645',
' £13,920',
' £15,660',
' £15,660',
' £13,920',
' £19,935',
' £7,830',
' £19,935',
' £13,290',
' £6,645',
' £18,270',
' £12,180',
' £6,090',
' £26,550',
' £19,935',
' £13,290',
' £19,935',
' £13,290',
' £19,935',
' £13,290',
' £19,935',
' £8,820',
' £5,880',
' £2,940',
' £19,935',
' £13,290',
' £19,935',
' £13,290',
' £23,490',
' £18,792',
' £17,415',
' £17,415',
' £17,415 ',
' £17,415',
' £17,415',
' £11,610',
' £7,290',
' £4,860',
' £2,430',
' £17,415',
' £16,695',
' £17,415',
' £21,285',
' £21,285',
' £19,935',
' £19,935',
' £16,695',
' £16,695',
'£11,130',
' £16,695',
' £11,130',
' £16,695 ',
' £11,130',
' £21,285',
' £21,285',
'£14,190',
'£14,190',
' £16,695',
' £16,695',
' £16,695',
' £11,130',
' £5,565',
' £16,695',
' £16,695',
' £16,695',
' £2,280',
' £12,975',
' £21,285',
' £17,028',
' £8,514',
' £16,695',
' £16,695',
' £16,695']
        dd = {}
        for i in range(len(list1)):
            dd[list1[i]] = listvalue[i]
            # print(dd)
        tuition_fee = dd.get(programme_en)
        try:tuition_fee = getTuition_fee(tuition_fee)
        except:tuition_fee = 0
        # print(tuition_fee)


        #24.apply_proces_en
        apply_proces_en = 'https://www.nottingham.ac.uk/pgstudy/how-to-apply/apply-online.aspx'

        #25.deadline
        deadline = '2018-8-9'

        #26.require_chinese_en
        require_chinese_en = '  <p>Masters applicants should hold a good bachelors degree from a recognised university. Minimum requirements from Chinese universities range from 70% to 88%, depending on the institution you have studied with in China and the programme you are applying to study at Nottingham. For more information on postgraduate courses and entry requirements, please see our postgraduate prospectus.</p>'
        #27.apply_fee
        apply_fee = 40

        item['apply_proces_en'] =apply_proces_en
        item['deadline'] = deadline
        item['require_chinese_en'] = require_chinese_en
        item['apply_fee'] = apply_fee
        item['tuition_fee'] = tuition_fee
        item['university'] = university
        item['url'] = url
        # item['programme_en'] = programme_en
        item['degree_type'] = degree_type
        # item['degree_name'] = degree_name
        item['duration'] = duration
        item['duration_per'] = duration_per
        item['teach_time'] = teach_time
        item['rntry_requirements'] = rntry_requirements
        item['ielts'] = ielts
        item['ielts_r'] = ielts_r
        item['ielts_s'] = ielts_s
        item['ielts_l'] = ielts_l
        item['ielts_w'] = ielts_w
        item['start_date'] = start_date
        item['department'] = department
        item['location'] = location
        item['overview_en'] = overview_en
        item['modules_en'] = modules_en
        item['career_en'] = career_en
        item['other'] = other
        item['tuition_fee_pre'] = tuition_fee_pre
        yield item