from scrapy import cmdline

# 2018.7.16
# cmdline.execute("scrapy crawl SwanseaUniversity_U".split())
# cmdline.execute("scrapy crawl LoughboroughUniversity_U".split())
# cmdline.execute("scrapy crawl TheUniversityOfSheffield_U".split())
# cmdline.execute("scrapy crawl QueensUniversityBelfast_U".split())
# cmdline.execute("scrapy crawl TheUniversityofEdinburgh_U".split())


# 2018.7.17
# cmdline.execute("scrapy crawl UniversityofBristol_U".split())
# cmdline.execute("scrapy crawl KingsCollegeLondon_U".split())
# cmdline.execute("scrapy crawl TheUniversityofManchester_U".split())
# cmdline.execute("scrapy crawl UniversityOfStrathclyde_U".split())
# cmdline.execute("scrapy crawl NottinghamTrentUniversity_U".split())


# 2018.7.24
# cmdline.execute("scrapy crawl UniversityOfPlymouth_U".split())
# cmdline.execute("scrapy crawl UniversityOfCambridge_U".split())
# cmdline.execute("scrapy crawl UniversityOfSurrey_U".split())
# cmdline.execute("scrapy crawl UniversityOfReading_U".split())


# 2018.7.25
# cmdline.execute("scrapy crawl NewcastleUniversity_U".split())
# cmdline.execute("scrapy crawl AstonUniversity_U".split())

# 2018.8.6
# cmdline.execute("scrapy crawl LiverpoolHopeUniversity_U".split())
# cmdline.execute("scrapy crawl UniversityOfPortsmouth_U".split())

# 2018.8.7
# cmdline.execute("scrapy crawl UniversityOfLincoln_U".split())
# cmdline.execute("scrapy crawl UniversityOfWestLondon_U".split())
# cmdline.execute("scrapy crawl UniversityOfChester_U".split())
# cmdline.execute("scrapy crawl UniversityOfChichester_U".split())
# cmdline.execute("scrapy crawl UniversityOfBradford_U".split())

# 2018.8.8
# cmdline.execute("scrapy crawl StGeorgesUniversityOfLondon_U".split())
# cmdline.execute("scrapy crawl UniversityOfSalford_U".split())
# cmdline.execute("scrapy crawl UniversityOfHertfordshire_U".split())
# cmdline.execute("scrapy crawl HeriotWattUniversity_U".split())
# cmdline.execute("scrapy crawl AberystwythUniversity_U".split())
# cmdline.execute("scrapy crawl CardiffMetropolitanUniversity_U".split())


# 2018.8.9
# cmdline.execute("scrapy crawl BathSpaUniversity_U".split())
# cmdline.execute("scrapy crawl UniversityOfCentralLancashire_U".split())
# cmdline.execute("scrapy crawl SouthamptonSolentUniversity_U".split())
# cmdline.execute("scrapy crawl UniversityOfBolton_U".split())
# cmdline.execute("scrapy crawl stl".split())


import os
print(os.listdir(r"D:\pycharm\hooli_scrapy_project\scrapySchool_England_Ben\scrapySchool_England_Ben\spiders"))


list1 = ["北京  BEIJING BJ",
"东城区  DONGCHENG  DCQ",
"西城区  XICHENG  XCQ",
"朝阳区  CHAOYANG  CYQ",
"海淀区  HAIDIAN  HDN",
"石景山  SHIJINGSHAN  SJS",
"门头沟  MENTOUGOU  MTG",
"丰台区  FENGTAI  FTQ",
"房山区  FANGSHAN  FSQ",
"大兴区  DAXING  DXQ",
"通州区  TONGZHOU  TZQ",
"顺义区  SHUNYI  SYI",
"平谷区  PINGGU  PGU",
"昌平区  CHANGPING  CPX",
"怀柔区  HUAIROU  HRX",
"延庆县  YANQING  YQX",
"密云县  MIYUN  MYN",
"上海  SHANGHAI  SH",
"浦东新区  PUDONGXINQU  PDX",
"徐汇区  XUHUI  XHI",
"长宁区  CHANGNING",
"普陀区  PUTUO  PTO",
"闸北区  ZHABEI  ZBE",
"虹口区  HONGKOU  HKQ",
"杨浦区  YANGPU  YPU",
"黄浦区  HUANGPU  HGP",
"静安区  JINGAN  JAQ",
"宝山区  BAOSHAN  BAO",
"闵行区  MINHANG  MHQ",
"嘉定区  JIADING  JDG",
"金山区  JINSHAN",
"松江区  SONGJIANG  SOJ",
"青浦区  QINGPU  QPU",
"奉贤区  FENGXIAN  FXI",
"崇明县  CHONGMING  CMI",
"天津  TIANJIN  TJ",
"和平区  HEPING  HPQ",
"河东区  HEDONG  HDL",
"河西区  HEXI HXQ",
"南开区  NANKAI NKQ",
"河北区  HEBEI HBQ",
"红桥区  HONGQIAO HQO",
"塘沽区  TANGKU TGA",
"汉沽区  HANKU HGQ",
"大港区  DAGANG DGJ",
"东丽区  DONGLI DLI",
"西青区  XIQING XQG",
"津南区  JINNAN JNQ",
"北辰区  BEICHEN BCQ",
"武清区  WUQING WQX",
"宝坻区  BAODI BDI",
"宁河县  NINGHE NHE",
"静海县  JINGHAI JHT",
"蓟　县  JIXIAN JXI",
"开发区  JINGJIKAIFAQU KFQ",
"滨海区  BINHAIXINQU BHI",
"重庆 CHONGQING CQ",
"渝中区  YUZHONG YZQ",
"江北区  JIANGBEI JBE",
"南岸区  NANAN NAQ",
"沙坪坝  SHAPINGVA SPB",
"九龙坡  JIULONGPO JLP",
"大渡口  DADUKOU DDK",
"北碚区  BEIBEI BBE",
"巴南区  BANAN BNN",
"渝北区  YUBEI YBE",
"永川区  YONGCHUAN YCP",
"涪陵区  FULING FLG",
"合川区  HECHUAN HEC",
"江津区  JIANGJIN JJY",
"长寿区  CHANGSHOU CSO",
"南川区  NANCHUAN NCU",
"万州区  WANZHOU WZO",
"黔江区  QIANJIANG QJX",
"綦江区  QIJIANG QJG",
"潼南县  TONGNANXIAN TNN",
"铜梁区  TONGLIANG TGL",
"大足区  DAZU DZX",
"荣昌县  RONGCHANGXIAN RGC",
"璧山区  BISHAN BSY",
"垫江县  DIANJIANGXIAN DJG",
"武隆县  WULONGXIAN WLG",
"丰都县  FENGDOUXIAN FDU",
"城口县  CHENGKOUXIAN CKO",
"梁平县  LIANGPINGXIAN LGP",
"开县 KAIXIAN KAI",
"巫溪县 WUXIXIAN WXX",
"巫山县 WUSHANXIAN WSN",
"奉节县 FENGJIEXIAN FJE",
"云阳县 YUNYANGXIAN YNY",
"忠县 ZHONGXIAN ZHX",
"石柱 SHIZHU SZY",
"彭水县  PENGSHUI PSU",
"酉阳县  YOUYANG YUY",
"石柱县  SHIZHUTUJIAZUZIZHIXIAN SZY",
"秀山县  XIUSHAN XUS",
"广东省  GUANGDONG GD",
"广州 GUANGZHOU CAN",
"白云区  BAIYUN",
"天河区  TIANHE THQ",
"越秀区  YUEXIU YXU",
"海珠区  ZHUHAI HZU",
"黄埔区  HUANGPU HPU",
"荔湾区  LIWAN LWQ",
"番禺区  FANYU PNY",
"花都区  HUADU HDU",
"萝岗区  LUOGANG",
"南沙区  NANSHA NSA",
"从化区  CONGHUA CNH",
"增城区  ZENGCHENG ZEC",
"潮州 CHAOZHOU CZY",
"东莞 DONGGUAN DGG",
"南城区  NANCHENGQU NCE",
"东城区  DONGCHENGQU DCQ",
"万江区  WANJIANGQU",
"莞城区  WANCHENGQU",
"石龙镇  SHILONGZHEN SIL",
"虎门镇  HUMENZHEN",
"麻涌镇  MAYONGZHEN",
"道滘镇  DAOJIAOZHEN",
"石碣镇  SHIJIEZHEN",
"沙田镇  SHATIANZHEN",
"望牛墩  WANGNIUDUNZHEN",
"洪梅镇  HONGMEIZHEN",
"茶山镇  CHASHANZHEN",
"寮步镇  LIAOBUZHEN",
"大岭山  DALINGSHANZHEN",
"大朗镇  DALANGZHEN",
"黄江镇  HUANGJIANGZHEN",
"樟木头  ZHANGMUTOUZHEN",
"凤岗镇  FENGGANGZHEN",
"塘厦镇  TANGXIAZHEN",
"谢岗镇  XIEGANGZHEN",
"厚街镇  HOUJIEZHEN",
"清溪镇  QINGXIZHEN",
"常平镇  CHANGPINGZHEN",
"桥头镇  QIAOTOUZHEN",
"横沥镇  HENGLIZHEN",
"东坑镇  DONGKENGZHEN",
"企石镇  QISHIZHEN",
"石排镇  SHIPAIZHEN",
"长安镇  CHANGANZHEN",
"中堂镇  ZHONGTANGZHEN",
"高埗镇  GAOBUZHEN",
"松山湖  SONGSHANHUGAOXINQU SSQ",
"佛山 FOSHAN FOS",
"禅城区  CHANCHENGQU",
"南海区  NANHAIQU NAH",
"顺德区  SHUNDEQU SUD",
"三水区  SANSHUIQU SJQ",
"高明区  GAOMINGQU GOM",
"新城区  DONGPINGXINCHENG",
"大沥  DALI",
"黄岐  HUANGQI",
"西樵  XIQIAO",
"南庄  NANZHUANG",
"惠州  HUIZHOU HUI",
"清远  QINGYUAN QYN",
"汕头  SHANTOU SWA",
"深圳  SHENZHEN SZX",
"罗湖区  LUOHU LHQ",
"福田区  FUTIAN FTN",
"南山区  NANSHAN",
"宝安区  ANBAO BAQ",
"龙岗区  LONGGANG LGG",
"盐田区  YANTIAN YTQ",
"光明新区  GUANGMINGXINQU",
"坪山新区  PINGSHANXINQU",
"大鹏新区  DAPENGXINQU",
"龙华新区  LONGHUAXINQU",
"顺德  SHUNDE SUD",
"湛江  ZHANJIANG ZHA",
"肇庆  ZHAOQING ZQG",
"中山  ZHONGSHAN",
"珠海  ZHUHAI ZUH",
"香洲区 XIANGZHOUQU XZQ",
"斗门区 DOUMENQU DOU",
"金湾区 JINWANQU",
"横琴新区 HENGQINXINQU",
"江门 JIANGMEN JMN",
"阳江 YANGJIANG YJI",
"韶关 SHAOGUAN HSC",
"茂名 MAOMING MMI",
"梅州 MEIZHOU MXZ",
"汕尾 SHANWEI SWE",
"河源 HEYUAN HEY",
"揭阳 JIEYANG JIY",
"云浮 YUNFU YFS",
"开平 KAIPING",
"台山 TAISHAN TSS",
"普宁 PUNING PNG",
"南沙 NANSHA NSA",
"龙川 LONGCHUAN LCY",
"鹤山 HESHAN",
"江苏省 JIANGSU JS",
"南京 NANJING NKG",
"玄武区 XUANWU XWU",
"白下区 BAIXIA BXQ",
"秦淮区 QINHUAI QHU",
"建邺区 JIANYE JYQ",
"鼓楼区 GULOU GLK",
"下关区 XIAGUAN XGQ",
"浦口区 PUKOU PKO",
"六合区 LIUHE LHE",
"栖霞区 QIXIA",
"雨花台 YUHUATAI",
"江宁区 JIANGNING JNX",
"溧水县 LISHUI LIS",
"高淳县 GAOCHUN GCN",
"大厂区 DACHANGQU",
"常熟 CHANGSHU CGS",
"常州 CHANGZHOU CZX",
"天宁区 TIANNINGQU TNQ",
"钟楼区 ZHONGLOUQU ZLQ",
"戚墅堰 QISHUYANQU QSY",
"郊区 JIAOQU JQC",
"新北区 XINBEIQU",
"武进区 WUJINQU WJN",
"溧阳市 LIYANGSHI LYR",
"金坛市 JINTANSHI JTS",
"昆山 KUNSHAN KUS",
"连云港 LIANYUNGANG",
"南通 NANTONG NTG",
"苏州 SUZHOU SZH",
"金阊区 JINCHANG JCA",
"沧浪区 CANGLANG CLQ",
"平江区 PINGJIANG",
"工业园 GONGYEYUAN",
"高新区 GAOXIN",
"吴中区 WUZHONG",
"相城区 XIANGCHENG",
"张家港 ZHANGJIAGANG ZJG",
"常熟市 CHANGSHU CGS",
"太仓市 TAICANG TAC",
"昆山市 KUNSHAN KUS",
"吴江市 WUJIANG WUJ",
"虎丘区 HUQIUQU",
"玉山镇 YUSHANZHEN YUS",
"巴城镇 BACHENGZHEN",
"周市镇 ZHOUSHIZHEN",
"陆家镇 LUJIAZHEN",
"花桥镇 HUAQIAOZHEN",
"淀山湖 DIANSHANHUZHEN",
"张浦镇 ZHANGPUZHEN",
"周庄镇 ZHOUZHUANGZHEN",
"千灯镇 QIANDENGZHEN",
"锦溪镇 JINXIZHEN",
"开发区 KAIFAQU",
"太仓 TAICANG TAC",
"无锡 WUXI WUX",
"崇安区 CHONGANQU CGA",
"北塘区 BEITANGQU BTQ",
"南长区 NANCHANGQU NCG",
"锡山区 XISHANQU XSS",
"惠山区 HUISHANQU",
"滨湖区 BINHUQU",
"新区 XINQU XNQ",
"宜兴市 YIXINGSHI  YIX",
"江阴市  JIANGYINSHI  JIA",
"徐州  XUZHOU  XUZ",
"扬州  YANGZHOU  YZH",
"镇江  ZHENJIANG  ZHE",
"淮安  HUAIAN  HAS",
"盐城  YANCHENG  YCK",
"泰州  TAI_ZHOU  TZS",
"宿迁  SUQIAN  SUQ",
"张家港  ZHANGJIAGANG  ZJG",
"江阴  JIANGYIN  JIA",
"丹阳  DANYANG  DNY",
"溧阳  LIYANG  LYR",
"泰兴  TAIXING  TXG",
"宜兴  YIXING  YIX",
"靖江  JINGJIANG  JGJ",
"句容  JURONG  JRG",
"如皋  RUGAO  RGO",
"扬中  YANGZHONG  YZG",
"高邮  GAOYOU  GYO",
"启东  QIDONG  QID",
"盱眙  XUYI  XUY",
"通州  TONGZHOU",
"金湖  JINHU  JHU",
"浙江省  ZHEJIANG  ZJ",
"杭州  HANGZHOU  HGH",
"上城区  SHANGCHENG  SCQ",
"下城区  XAICHENG  XCG",
"拱墅区  GONGSHU  GSQ",
"西湖区  XIHU  XHQ",
"江干区  JIANGGAN  JGQ",
"滨江区  BINJIANG  BJQ",
"萧山区  XIAOSHAN  XIS",
"余杭区  YUHANG  YHS",
"临安市  LINAN  LNA",
"富阳区  FUYANG  FYZ",
"建德市  JIANDE  JDS",
"桐庐县  TONGLU  TLU",
"淳安县  CUNAN  CAZ",
"市郊  SHIJIAO  SWZ",
"宁波  NINGBO  NGB",
"海曙区  HAISHUQU  HNB",
"江东区  JIANGDONGQU  JDH",
"江北区  JIANGBEIQU  JBE",
"镇海区  ZHENHAIQU  ZHF",
"北仑区  BEILUNQU  BLN",
"鄞州区  YINZHOUQU",
"余姚市  YUYAOSHI  YYO",
"慈溪市  CIXISHI  CXI",
"奉化市  FENGHUASHI  FHU",
"象山县  XIANGSHANXIAN",
"宁海县  NINGHAIXIAN  NHI",
"温州  WENZHOU  WNZ",
"鹿城区  LUCHENGQU  LUW",
"龙湾区  LONGWANQU  LWW",
"瓯海区  OUHAIQU  OHQ",
"瑞安市  RUIANSHI  RAS",
"乐清市  LEQINGSHI  YQZ",
"洞头县  DONGTOUXIAN  DTO",
"永嘉县  YONGJIAXIAN  YJX",
"平阳县  PINGYANGXIAN  PYG",
"苍南县  CANGNANXIAN  CAN",
"文成县  WENCHENGXIAN  WCZ",
"泰顺县  TAISHUNXIAN  TSZ",
"绍兴  SHAOXING",
"金华  JINHUA",
"台州  TAIZHOU  TZZ",
"湖州  HUZHOU  HZH",
"嘉兴  JIAXING  JIX",
"衢州  QUZHOU  QUZ",
"丽水  LISHUI",
"舟山  ZHOUSHAN  ZOS",
"义乌  YIWU  YWS",
"海宁  HAINING  HNG",
"玉环县  YUHUANXIAN  YHN",
"平湖  PINGHU  PHU",
"永康  YONGKANG  YKG",
"东阳  DONGYANG  DGY",
"嘉善  JIASHAN  JSK",
"余姚  YUYAO  YYO",
"慈溪  CIXI  CXI",
"乐清  LEQING  YQZ",
"永嘉  YONGJIA  YJX",
"桐乡  TONGXIANG  TXZ",
"瑞安  RUIAN  RAS",
"温岭  WENLING  WLS",
"上虞  SHANGYU  SYZ",
"诸暨  ZHUJI  ZHJ",
"宁海  NINGHAI  NHI",
"三门  SANMEN",
"德清  DEQING  DQX",
"象山  XIANGSHAN",
"方家山  FANGJIASHAN",
"龙泉  LONGQUAN",
"安徽省  ANHUI  AH",
"合肥  HEFEI  HFE",
"庐阳区  LUYANGQU",
"瑶海区  YAOHAIQU",
"蜀山区  SHUSHANQU",
"包河区  BAOHEQU",
"长丰县  CHANGFENGXIAN  CFG",
"肥东县  FEIDONGXIAN  FDO",
"肥西县  FEIXIXIAN  FIX",
"新站区  XINZHANQU",
"经开区  JINGKAIQU",
"高新区  GAOXINQU",
"滨湖区  BINHUXINQU",
"北城区  BEICHENGXINQU",
"政务区  ZHENGWUXINQU",
"安庆  ANQING  AQG",
"蚌埠  BENGBU  BBU",
"芜湖  WUHU",
"淮南  HUAINAN  HNS",
"马鞍山  MAANSHAN  MAA",
"淮北  HUAIBEI  HBE",
"铜陵  TONGLING",
"黄山  HUANGSHAN",
"滁州  CHUZHOU  CUZ",
"阜阳  FUYANG  FYS",
"宿州  SU_ZHOU  SUZ",
"六安  LIUAN",
"亳州  BOZHOU  BOZ",
"池州  CHIZHOU  CZD",
"宣城  XUANCHENG  XCD",
"巢湖  CHAOHU",
"凤阳  FENGYANG  FYG",
"广德  GUANGDE  GGD",
"宿松  SUSONG  SUS",
"福建省  FUJIAN  FJ",
"福州  FUZHOU  FOC",
"鼓楼区  GULOUQU  GLK",
"台江区  TAIJIANGQU",
"仓山区  CANGSHANQU  CSQ",
"马尾区  MAWEIQU  MWQ",
"晋安区  JINANQU  JAF",
"福清市  FUQINGSHI  FQS",
"长乐市  CHANGLESHI  CLS",
"闽侯县  MINHOUXIAN  MHO",
"连江县  LIANJIANGXIAN  LJF",
"罗源县  LUOYUANXIAN  LOY",
"闽清县  MINQINGXIAN  MQG",
"永泰县  YONGTAIXIAN  YTX",
"平潭县  PINGTANXIAN  PTN",
"泉州  QUANZHOU  QZJ",
"厦门  XIAMEN  XMN",
"思明区  SIMINGQU  SMQ",
"海沧区  HAICANGQU",
"湖里区  HULIQU  HLQ",
"集美区  JIMEIQU  JMQ",
"同安区  TONGANQU  TAQ",
"翔安区  XIANGANQU",
"漳州  ZHANGZHOU  ZZU",
"莆田  PUTIAN",
"三明  SANMING  SMS",
"南平  NANPING  NPS",
"龙岩  LONGYAN  LYF",
"宁德  NINGDE",
"泉港区  QUANGANGQU",
"福安  FUAN  FAS",
"晋江  JINJIANG  JJG",
"甘肃省  GANSU  GS",
"兰州  LANZHOU  LHW",
"皋兰县  GAOLANXIAN  GAL",
"城关区  CHENGGUANQU  CLZ",
"七里河  QILIHEQU  QLH",
"西固区  XIGUQU  XGU",
"安宁区  ANNINGQU",
"红古区  HONGGUQU  HOG",
"永登县  YONGDENGXIAN  YDG",
"榆中县  YUZHONGXIAN  YZX",
"嘉峪关  JIAYUGUAN  JYG",
"酒泉  JIUQUAN",
"金昌  JINCHANG  JCS",
"白银  BAIYIN",
"天水  TIANSHUI  TSU",
"张掖  ZHANGYE",
"武威  WUWEI",
"定西  DINGXI",
"陇南  LONGNAN  LND",
"平凉  PINGLIANG",
"庆阳  QINGYANG",
"临夏  LINXIA",
"甘南  GANNAN",
"广西  GUANGXI  GX",
"南宁  NANNING",
"邕宁区  YONGNINGQU  YNG",
"青秀区  QINGXIUQU",
"兴宁区  XINGNINGQU",
"良庆区  LIANGQINGQU",
"西乡塘  XIXIANGTANGQU  XXA",
"江南区  JIANGNANQU  JNA",
"武鸣县  WUMINGXIAN  WMG",
"隆安县  LONGANXIAN  LGA",
"马山县  MASHANXIAN",
"上林县  SHANGLINXIAN  SLX",
"宾阳县  BINYANGXIAN  BYX",
"横县  HENGXIAN  HEN",
"北海  BEIHAI  BHY",
"桂林  GUILIN  KWL",
"柳州  LIUZHOU  LZ",
"玉林  YULIN  YUL",
"梧州  WUZHOU  WUZ",
"崇左  CHONGZUO  CZU",
"来宾  LAIBIN  LBN",
"防城港  FANGCHENGGANG  FCG",
"百色  BAISE  BS",
"钦州  QINZHOU  QZH",
"贺州  HEZHOU  HZ",
"河池  HECHI  HC",
"贵港  GUIGANG  GUG",
"贵州省  GUIZHOU  GZ",
"贵阳  GUIYANG  KWE",
"南明区  NANMINGQU  NMQ",
"云岩区  YUNYANQU  YYQ",
"花溪区  HUAXIQU  HXI",
"乌当区  WUDANGQU  WDQ",
"白云区  BAIYUNQU  BY",
"小河区  XIAOHEQU  XH",
"金阳区  JINYANGXINQU  JYW",
"新天园  XINTIANYUANQU  XTY",
"清镇市  QINGZHENSHI  QZN",
"开阳县  KAIYANGXIAN  KYG",
"修文县  XIUWENXIAN  XWX",
"息烽县  XIFENGXIAN  XFX",
"遵义  ZUNYI  ZY",
"六盘水  LIUPANSHUI  LPS",
"安顺  ANSHUN  AS",
"毕节  BIJIE  BIJ",
"铜仁  TONGREN  TR",
"黔西南  QIANXINAN  QXN",
"黔东南  QIANDONGNAN  QNDN",
"黔南  QIANNAN  QNZ",
"海南省  HAINAN  HN",
"海口  HAIKOU  HAK",
"秀英区  XIUYINGQU  XYH",
"龙华区  LONGHUAQU  LH",
"琼山区  QIONGSHANQU  QSS",
"美兰区  MEILANQU  ML",
"澄迈县  CHENGMAIXIAN  CMA",
"万宁市  WANNINGSHI  WNN",
"文昌市  WENCHANGSHI  WEC",
"儋州市  DANZHOUSHI  DNZ",
"屯昌县  TUNCHANGXIAN  TCG",
"东方市  DONGFANGSHI  DFG",
"昌江县  CHANGJIANGXIAN  CJX",
"乐东黎  LEDONGLIMIAOZIZHIXIAN  LED",
"临高县  LINGAOXIAN  LGO",
"琼海市  QIONGHAISHI  QHA",
"府城  FUCHENG  FC",
"三亚  SANYA  SYX",
"三沙  SANSHA  SS",
"文昌  WENCHANG  WEC",
"琼海  QIONGHAI  QHA",
"万宁  WANNING  WNN",
"儋州  DANZHOU  DNZ",
"东方  DONGFANG  DFG",
"五指山  WUZHISHAN  WZS",
"定安  DINGAN  DIA",
"屯昌  TUNCHANG  TCG",
"澄迈  CHENGMAI  CMA",
"临高  LINGAO  LGO",
"琼中  QIONGZHONG  QZG",
"保亭  BAOTING  BTG",
"白沙  BAISHA  BSX",
"昌江  CHANGJIANG  CJ",
"乐东  LEDONG  LED",
"陵水  LINGSHUI  LSL",
"河北省  HEBEI",
"石家庄  SHIJIAZHUANG  SJW",
"长安区  CHANGANQU  CAQ",
"桥东区  QIAODONGQU  QDZ",
"桥西区  QIAOXIQU  QXI",
"新华区  XINHUAQU  XHH",
"裕华区  YUHUAQU  YHQ",
"井陉矿  JINGXINGKUANGQU  JXG",
"高新区  GAOXINQU  GXQ",
"辛集市  XINJISHI  XJS",
"藁城市  GAOCHENGSHI  GCS",
"晋州市  JINZHOUSHI  JZJ",
"新乐市  XINLESHI  XLE",
"鹿泉市  LUQUANSHI  LUQ",
"井陉县  JINGXINGXIAN  JJX",
"正定县  ZHENGDINGXIAN  ZDJ",
"栾城县  LUANCHENGXIAN  LCG",
"行唐县  XINGTANGXIAN  XTG",
"灵寿县  LINGSHOUXIAN  LSO",
"高邑县  GAOYIXIAN  GYJ",
"深泽县  SHENZEXIAN  SZX",
"赞皇县  ZANHUANGXIAN  ZHG",
"无极县  WUJIXIAN  WJI",
"平山县  PINGSHANXIAN",
"元氏县  YUANSHIXIAN  YSI",
"赵县  ZHAOXIAN  ZAO",
"保定  BAODING  BDS",
"承德  CHENGDE  CD",
"邯郸  HANDAN  HD",
"廊坊  LANGFANG  LFS",
"秦皇岛  QINHUANGDAO  SHP",
"唐山  TANGSHAN  TGS",
"张家口  ZHANGJIAKOU  ZJK",
"邢台  XINGTAI  XT",
"沧州  CANGZHOU  CGZ",
"衡水  HENGSHUI  HGS",
"燕郊  YANJIAO  YJ",
"固安  GUAN  GUA",
"遵化  ZUNHUA  ZNH",
"香河  XIANGHE  XGH",
"三河  SANHE  SNH",
"河南省  HENAN  HEN",
"郑州  ZHENGZHOU  CGO",
"金水区  JINSHUIQU  JSU",
"邙山区  MANGSHANQU  MSQ",
"二七区  ERQIQU  EQQ",
"管城区  GUANCHENGQU  GCH",
"中原区  ZHONGYUANQU  ZYQ",
"上街区  SHANGJIEQU  SJE",
"惠济区  HUIJIQU  HJQ",
"郑东区  ZHENGDONGXINQU  ZDQ",
"经济区  JINGJIJISHUKAIFAQU  JJQ",
"高新区  GAOXINKAIFAQU  GXQ",
"加工区  CHUKOUJIAGONGQU  JGQ",
"巩义市  GONGYISHI  GYI",
"荥阳市  YINGYANGSHI  XYK",
"新密市  XINMISHI  XMI",
"新郑市  XINZHENGSHI  XZG",
"登封市  DENGFENGSHI",
"中牟县  ZHONGMOUXIAN  ZMO",
"开封  KAIFENG  KF",
"洛阳  LUOYANG  LYA",
"商丘  SHANGQIU  SQS",
"安阳  ANYANG  AY",
"平顶山  PINGDINGSHAN  PDS",
"新乡  XINXIANG  XXA",
"焦作  JIAOZUO  JZY",
"濮阳  PUYANG  PY",
"许昌  XUCHANG  XC",
"漯河  LUOHE  LHS",
"三门峡  SHANMENXIA  SMX",
"鹤壁  HEBI  HBS",
"周口  ZHOUKOU  ZK",
"驻马店  ZHUMADIAN  ZMD",
"南阳  NANYANG  NYS",
"信阳  XINYANG  XYG",
"济源  JIYUAN  JYY",
"西平  XIPING  XIP",
"长葛  CHANGGE  CGE",
"黑龙江省  HEILONGJIANG  HL",
"哈尔滨  HAERBIN  HRB",
"道里区  DAOLIQU  DLH",
"南岗区  NANGANGQU  NGQ",
"动力区  DONGLIQU  DGL",
"平房区  PINGFANGQU  PFQ",
"香坊区  XIANGFANGQU  XFQ",
"太平区  TAIPINGQU  TPQ",
"道外区  DAOWAIQU  DWQ",
"阿城市  ACHENGSHI  ACG",
"呼兰区  HULANQU  HLH",
"松北区  SONGBEIQU",
"尚志市  SHANGZHISHI  SZI",
"双城市  SHUANGCHENGSHI  SCS",
"五常市  WUCHANGSHI  WCA",
"方正县  FANGZHENGXIAN  FZH",
"宾县  BINXIAN  BNX",
"依兰县  YILANXIAN  YLH",
"巴彦县  BAYANXIAN",
"通河县  TONGHEXIAN  TOH",
"木兰县  MULANXIAN  MUL",
"延寿县  YANSHOUXIAN  YSU",
"大庆  DAQING  DQG",
"佳木斯  JIAMUSI  JMU",
"牡丹江  MUDANJIANG  MDG",
"齐齐哈尔  QIQIHAER  NDG",
"鸡西  JIXI  JXI",
"鹤岗  HEGANG  HEG",
"双鸭山  SHUANGYASHAN  SYS",
"伊春  YICHUN",
"七台河  QITAIHE  QTH",
"黑河  HEIHE  HEK",
"绥化  SUIHUA",
"大兴安岭  DAXINGANLING",
"安达  ANDA  ADA",
"双城  SHUANGCHENG  SCS",
"尚志  SHANGZHI  SZI",
"绥芬河  SUIFENGHE  SFE",
"肇东  ZHAODONG  ZDS",
"湖北省  HUBEI  HB",
"武汉  WUHAN  WUH",
"江岸区  JIANGAN  JAA",
"江汉区  JIANGHAN  JHN",
"硚口区  QIAOKOU  QKQ",
"汉阳区  HANYANG  HYA",
"武昌区  WUCHANG  WCQ",
"青山区  QINGSHAN  QSN",
"洪山区  HONGSHAN  HSQ",
"蔡甸区  CAIDIAN  CDN",
"江夏区  JIANGXIA  JXQ",
"黄陂区  HUANGPI  HPI",
"新洲区  XINZHOU  XNZ",
"东西湖  DONGXIHU  DXH",
"汉南区  HANNAN  HNQ",
"开发区  JINGJIKAIFAQU",
"十堰  SHIYAN  SYE",
"襄阳  XIANGYANG  XYA",
"宜昌  YICHANG",
"潜江  QIANJIANG  QNJ",
"荆门  JINGMEN  JMS",
"荆州  JINGZHOU",
"黄石  HUANGSHI",
"鄂州  EZHOU  EZS",
"黄冈  HUANGGANG  HE",
"孝感  XIAOGAN  XGE",
"咸宁  XIANNING  XNS",
"随州  SUIZHOU  SZR",
"仙桃  XIANTAO  XNT",
"天门  TIANMEN  TMS",
"神农架  SHENNONGJIA  SNJ",
"恩施  ENSHI",
"公安  GONGAN  GGA",
"武穴  WUXUE  WXE",
"宜城  YICHENG  YCW",
"湖南省  HUNAN  HN",
"长沙  CHANGSHA",
"岳麓区  YUELUQU  YLU",
"芙蓉区  FURONGQU  FRQ",
"天心区  TIANXINQU  TXQ",
"开福区  KAIFUQU  KFQ",
"雨花区  YUHUAQU",
"开发区  KAIFAQU",
"浏阳市  LIUYANGSHI  LYS",
"长沙县  CHANGSHAXIAN",
"望城区  WANGCHENGQU  WCH",
"宁乡县  NINGXIANGXIAN  NXX",
"湘潭  XIANGTAN",
"株洲  ZHUZHOU",
"常德  CHANGDE  CDE",
"衡阳  HENGYANG",
"益阳  YIYANG  YYS",
"郴州  CHENZHOU  CNZ",
"岳阳  YUEYANG",
"邵阳  SHAOYANG",
"张家界  ZHANGJIAJIE  ZJJ",
"娄底  LOUDI",
"永州  YONGZHOU  YZS",
"怀化  HUAIHUA  HHS",
"湘西  XIANGXI  XXZ",
"吉林省  JILIN",
"长春  CHANGCHUN  CGQ",
"朝阳区  CHAOYANGQU",
"宽城区  KUANCHENGQU",
"二道区  ERDAOQU",
"南关区  NANGUANQU  NGK",
"绿园区  LVYUANQU  LYQ",
"双阳区  SHUANGYANGQU  SYQ",
"净月区  JINGYUETANKAIFAQU",
"高新区  GAOXINQU",
"经开区  JINGKAIQU",
"汽开区  QICHECHANYEKAIFAQU",
"德惠市  DEHUISHI  DEH",
"九台市  JIUTAISHI  JUT",
"榆树市  YUSHUSHI  YSS",
"农安县  NONGANXIAN  NAJ",
"高新区  GAOXINKAIFAQU",
"经济区  JINGJIKAIFAQU",
"净月区  JINGYUEKAIFAQU",
"吉林市  JINLINSHI",
"四平  SIPING  SPS",
"辽源  LIAOYUAN  LYH",
"通化  TONGHUAN",
"白山  BAISHAN  BSN",
"松原  SONGYUAN  SYU",
"白城  BAICHENG  BCS",
"延吉  YANJI  YNJ",
"延边  YANBIAN  YBZ",
"公主岭  GONGZHULING  GZL",
"江西省  JIANGXI  JX",
"南昌  NANCHANG",
"东湖区  DONGHUQU  DHU",
"西湖区  XIHUQU  XHQ",
"青云谱  QINGYUNPUQU  QYP",
"湾里区  WANLIQU  WLI",
"青山湖  QINGSHANHUQU  QSN",
"红谷滩  HONGGUTANXINQU",
"昌北区  CHANGBEIQU",
"高新区  GAOXINQU",
"南昌县  NANCHANGXIAN",
"新建县  XINJIANXIAN  XJN",
"安义县  ANYIXIAN  AYI",
"进贤县  JINXIANXIAN  JXX",
"桑海区  SANGHAIKAIFAQU",
"九江  JIUJIANG",
"赣州  GANZHOU  GZH",
"宜春  YI_CHUN",
"吉安  JIAN",
"上饶  SHANGRAO",
"抚州  FU_ZHOU  FZD",
"景德镇  JINGDEZHEN  JDZ",
"萍乡  PINGXIANG  PXS",
"新余  XINYU  XYU",
"鹰潭  YINGTAN  YTS",
"辽宁省  LIAONING  LN",
"沈阳  SHENYANG  SHE",
"沈河区  SHENHEQU  SHQ",
"皇姑区  HUANGGUQU  HGU",
"和平区  HEPINGQU",
"大东区  DADONGQU  DDQ",
"铁西区  TIEXIQU  TXA",
"苏家屯  SUJIATUNQU  SJT",
"东陵区  DONGLINGQU  DLQ",
"沈北区  SHENBEIXINQU",
"于洪区  YUHONGQU  YHQ",
"浑南区  HUNNANXINQU",
"新民市  XINMINSHI  XMS",
"辽中县  LIAOZHONGXIAN  LZL",
"康平县  KANGPINGXIAN  KPG",
"法库县  FAKUXIAN  FKU",
"鞍山  ANSHAN  ASN",
"大连  DALIAN  DLC",
"西岗区  XIGANG  XGD",
"中山区  ZHONGSHAN",
"沙河口  SHAHEQU",
"甘井子  GANJINGZI  GJZ",
"旅顺口  LVSHUNKOU  LSK",
"金州区  JINZHOU  JZH",
"瓦房店  WAFANGDIAN  WFD",
"普兰店  PULANDIAN",
"庄河市  ZHUANGHE  ZHH",
"普湾区  PUWANXINQU",
"长海县  CHANGHAIXIAN  CHX",
"新区  XINQU  XNQ",
"开发区  KAIFAQU",
"葫芦岛  HULUDAO  HLD",
"抚顺  FUSHUN",
"本溪  BENXI",
"丹东  DANDONG  DDG",
"锦州  JINZHOU  JNZ",
"营口  YINGKOU  YIK",
"阜新  FUXIN",
"辽阳  LIAOYANG",
"盘锦  PANJIN  PJS",
"铁岭  TIELING",
"朝阳  CHAOYANG",
"兴城  XINGCHENG  XCL",
"海城  HAICHENG",
"昌图  CHANGTU  CTX",
"开原  KAIYUAN  KYS",
"内蒙古  NEIMENGGU  NM",
"呼和浩特  HUHEHAOTE  Hhht",
"回民区  HUIMINQU  HMQ",
"玉泉区  YUQUANQU  YQN",
"新城区  XINCHENGQU",
"赛罕区  SAIHANQU",
"清水河  QINGSHUIHEXIAN",
"土左旗  TUMOTEZUOQI",
"托克托  TUOKETUOXIAN  TOG",
"格尔县  HELINGEERXIAN  GOS",
"武川县  WUCHUANXIAN  WCX",
"包头  BAOTOU  BTS",
"赤峰  CHIFENG  CFS",
"鄂尔多斯  EERDUOSI",
"乌海  WUHAI  WHM",
"通辽  TONGLIAO  TLO",
"呼伦贝尔  HULUNBEIER  HBM",
"巴彦淖尔  BAYANNAOER",
"乌兰察布  WULANCHABU",
"兴安盟  XINGANMENG",
"锡林郭勒盟  XILINGUOLEMENG  XGO",
"阿拉善盟  ALASHANMENG  ALM",
"乌审旗  WUSHENQI  UXI",
"满洲里  MANZHOULI  MLX",
"宁夏  NINGXIA  NX",
"银川  YINCHUAN  INC",
"西夏区  XIXIAQU",
"金凤区  JINFENGQU",
"兴庆区  XINGQINGQU",
"灵武市  LINGWUSHI  LWU",
"永宁县  YONGNINGXIAN  YGN",
"贺兰县  HELANXIAN  HLN",
"中卫  ZHONGWEI  ZWE",
"石嘴山  SHIZUISHAN",
"吴忠  WUZHONG  WZS",
"青铜峡  QINGTONGXIA  QTX",
"石嘴山  SHIZUISHAN",
"吴忠  WUZHONG  WZS",
"固原  GUYUAN",
"中卫  ZHONGWEI  ZWE",
"青海省  QINGHAI  QH",
"西宁  XINING  XNN",
"城中区  CHENGZHONGQU  CZQ",
"城东区  CHENGDONGQU  CDQ",
"城西区  CHENGXIQU  CXQ",
"城北区  CHENGBEIQU  CBE",
"湟中县  HUANGZHONGXIAN  HZX",
"湟源县  HUANGYUANXIAN  HYU",
"大通  DATONG",
"城南区  CHENGNANXINQU  CNN",
"海湖区  HAIHUXINQU",
"海东  HAIDONG  HDD",
"海西  HAIXI  HXZ",
"海北  HAIBEI  HBZ",
"黄南  HUANGNAN  HNZ",
"海南  HAINAN",
"果洛  GUOLUO  GOL",
"玉树  YUSHU",
"山东省  SHANDONG  SD",
"济南  JINAN  JNA",
"市中区  SHIZHONGQU  SZP",
"历下区  LIXIAQU  LXQ",
"天桥区  TIANQIAOQU  TQQ",
"槐荫区  HUAIYINQU  HYF",
"历城区  LICHENGQU  LCZ",
"长清区  CHANGQINGQU  CQG",
"章丘市  ZHANGQIUSHI  ZQS",
"平阴县  PINGYINXIAN  PYL",
"济阳县  JIYANGXIAN  JYL",
"商河县  SHANGHEXIAN  SGH",
"高新区  GAOXINQU",
"近郊  JINJIAO",
"德州  DEZHOU  DZS",
"东营  DONGYING",
"济宁  JINING  JNG",
"临沂  LINYI  LYI",
"青岛  QINGDAO  TAO",
"市南区  SHINANQU  SNQ",
"市北区  SHIBEIQU  SBQ",
"城阳区  CHENGYANGQU  CEY",
"四方区  SIFANGQU",
"李沧区  LICANGQU  LCT",
"黄岛区  HUANGDAOQU  HDO",
"崂山区  LAOSHANQU  LQD",
"胶州市  JIAOZHOUSHI  JZS",
"即墨市  JIMOSHI  JMO",
"平度市  PINGDUSHI  PDU",
"胶南市  JIAONANSHI  JNS",
"莱西市  LAIXISHI  LXE",
"日照  RIZHAO  RZH",
"泰安  TAIAN  TAI",
"威海  WEIHAI  WEH",
"潍坊  WEIFANG  WEF",
"烟台  YANTAI  YNT",
"淄博  ZIBO  ZBO",
"枣庄  ZAOZHUANG  ZZG",
"滨州  BINZHOU",
"聊城  LIAOCHENG  LCH",
"菏泽  HEZE  HZS",
"莱芜  LAIWU  LWS",
"荣成  RONGCHENG",
"黄岛  HUANGDAO  HDO",
"乳山  RUSHAN  RSN",
"城阳  CHENGYANG  CEY",
"即墨  JIMO  JMO",
"肥城  FEICHENG  FEC",
"兖州  YANZHOU  YZL",
"海阳  HAIYANG  HYL",
"胶州  JIAOZHOU  JZS",
"胶南  JIAONAN  JNS",
"平度  PINGDU  PDU",
"莱西  LAIXI  LXE",
"山西省  SHANXI  SX",
"太原  TAIYUAN  TYN",
"杏花岭  XINGHUALINGQU  XHL",
"小店区  XIAODIANQU  XDQ",
"迎泽区  YINGZEQU  YZT",
"尖草坪  JIANCAOPINGQU  JCP",
"万柏林  WANBAILINQU  WBL",
"晋源区  JINYUANQU  JYM",
"高新区  GAOXINQU",
"开发区  JINGJIKAIFAQU",
"工业园  GONGYEYUANQU",
"清徐县  QINGXUXIAN  QXU",
"阳曲县  YANGQUXIAN  YGQ",
"娄烦县  LOUFANXIAN  LFA",
"古交市  GUJIAOSHI  GUJ",
"大同  DATONG",
"临汾  LINFEN",
"运城  YUNCHENG",
"长治  CHANGZHI",
"阳泉  YANGQUAN  YQS",
"晋城  JINCHENG  JCG",
"朔州  SHUOZHOU  SZJ",
"晋中  JINZHONG  JZD",
"忻州  XINZHOU",
"吕梁  LVLIANG  LLD",
"永济  YONGJI  YJJ",
"和顺  HESHUN  HSJ",
"陕西省  SHANXI  SN",
"西安  XIAN",
"宝鸡  BAOJI",
"咸阳  XIANYANG  XYS",
"铜川  TONGCHUAN  TCN",
"渭南  WEINAN  WNA",
"汉中  HANZHONG  HZJ",
"安康  ANKANG",
"商洛  SHANGLUO  SLD",
"延安  YANAN  YNA",
"榆林  YU_LIN",
"杨凌  YANGLING",
"兴平  XINGPING  XPG",
"四川省  SICHUAN  SC",
"成都  CHENGDU  CTU",
"成华区  CHENGHUA  CHQ",
"武侯区  WUHOU  WHQ",
"青羊区  QINGYANG  QYQ",
"锦江区  JINJIANG  JJQ",
"金牛区  JINNIU  JNU",
"龙泉驿  LONGQUANYI",
"青白江  QINGBAIJIANG  QBJ",
"新都区  XINDU  XDU",
"双流县  SHUANGLIU  SLU",
"郫县  PIXIAN  PIX",
"温江区  WENJIANG  WNJ",
"大邑县  DAYI  DYI",
"金堂县  JINTANG  JNT",
"蒲江县  PUJIANG  PJX",
"新津县  XINJIN  XJC",
"温江区  WENJIANGQU  WNJ",
"高新区  GAOXINQU",
"高新西  GAOXINXIQU",
"都江堰  DOUJIANGYANSHI  DJY",
"彭州市  PENGZHOUSHI  PZS",
"邛崃市  QIONGLAISHI  QLA",
"崇州市  CHONGZHOUSHI  CZO",
"乐山  LESHAN  LES",
"泸州  LUZHOU  LUZ",
"绵阳  MIANYANG  MYG",
"内江  NEIJIANG  NJS",
"宜宾  YIBIN",
"自贡  ZIGONG  ZGS",
"攀枝花  PANZHIHUA  PZH",
"德阳  DEYANG  DEY",
"广元  GUANGYUAN  GYC",
"遂宁  SUINING  SNS",
"南充  NANCHONG  NCO",
"眉山  MEISHAN",
"广安  GUANGAN",
"达州  DAZHOU",
"雅安  YAAN",
"巴中  BAZHONG",
"资阳  ZIYANG",
"西昌  XICHANG  XCA",
"甘孜  GANZI",
"阿坝  ABEI",
"凉山  LIANGSHAN  LSY",
"峨眉  EMEI  EMS",
"简阳  JIANYANG  JYC",
"西藏  XIZANG  XZ",
"拉萨  LASA  LXA",
"城关区  CHENGGUANQU  CLZ",
"林周县  LINZHOUXIAN  LZB",
"当雄县  DANGXIONGXIAN  DAM",
"尼木县  NIMUXIAN  NYE",
"曲水县  QUSHUIXIAN  QUX",
"龙德庆  DUILONGDEQINGXIAN",
"达孜县  DAZIXIAN  DAG",
"工卡县  MOZHUGONGKAXIAN",
"日喀则  RIKAZE",
"林芝  LINZHI",
"山南  SHANNAN  SND",
"昌都  CHANGDU",
"那曲  NAQU",
"阿里  ALI  NGD",
"新疆  XINJIANG  XJ",
"乌鲁木齐  WULUMUQI",
"天山区  TIANSHANQU  TSL",
"巴克区  SHAYIBAKEQU",
"新市区  XINSHIQU  XSU",
"水磨沟  SHUIMOGOUQU  SMG",
"头屯河  TOUTUNHEQU  TTH",
"达坂城  DABANCHENGQU",
"米东区  MIDONGQU",
"乌县  WULUMUQIXIAN",
"昌吉市  CHANGJISHI",
"五家渠  WUJIAQUSHI",
"阜康市  FUKANGSHI  FKG",
"喀什  KASHI",
"克拉玛依  KELAMAYI",
"伊犁  YILI",
"阿克苏  AKESU",
"哈密  HAMI",
"石河子  SHIHEZI  SHZ",
"阿拉尔  ALAER",
"五家渠  WUJIAQU",
"图木舒克  TUMUSHUKE",
"昌吉  CHANGJI",
"阿勒泰  ALETAI",
"吐鲁番  TULUFAN",
"塔城  TACHENG",
"和田  HETIAN",
"巴音郭楞  BAYINGUOLENG  BAG",
"博尔塔拉  BOERTALA  BOR",
"奎屯市  KUITUNSHI  KUY",
"乌苏  WUSU  USU",
"克州  KEZILESUKEERKEZI",
"云南省  YUNNAN  YN",
"昆明  KUNMING  KMG",
"盘龙区  PANLONGQU  PLQ",
"五华区  WUHUAQU",
"官渡区  GUANDUQU  GDU",
"西山区  XISHANQU  XSN",
"东川区  DONGCHUANQU  DCU",
"安宁市  ANNINGSHI",
"呈贡新  CHENGGONGXINQU  CGD",
"晋宁新  JINNINGXINQU  JND",
"富民区  FUMINQU  FMN",
"宜良区  YILIANGQU  YIL",
"嵩明区  SONGMINGQU  SMI",
"石林县  SHILINXIAN  SLY",
"禄劝  LUQUAN  LUC",
"寻甸  XUNDIAN  XDN",
"大理  DALI",
"丽江  LIJIANG",
"玉溪  YUXI  YXS",
"曲靖  QUJING  QJS",
"保山  BAOSHAN",
"昭通  ZHAOTONG",
"普洱  PUER  PER",
"临沧  LINCANG",
"红河  HONGHE",
"文山  WENSHAN",
"西双版纳  XISHUANGBANNA  XSB",
"德宏  DEHONG  DHG",
"楚雄  CHUXIONG",
"怒江  NUJIANG  NUJ",
"迪庆  DIQING  DEZ",
"思茅  SIMAO",
"香港  HONGKONG  HK",
"沙田区  SHATIANQU",
"东区  DONGQU  DQP",
"观塘区  GUANTANGQU",
"黄大仙  HUANGDAXIANQU",
"九龙城  JIULONGCHENGQU  JLC",
"屯门区  TUNMENQU",
"葵青区  KUIQINGQU",
"元朗区  YUANLANGQU",
"深水埗  SHENSHUIBUQU",
"西贡区  XIGONGQU",
"大埔区  DAPUQU  DBX",
"湾仔区  WANZIQU",
"油尖旺  YOUJIANWANGQU",
"北区  BEIQU",
"南区  NANQU",
"荃湾区  QUANWANQU",
"中西区  ZHONGXIQU",
"离岛区  LIDAOQU",
"澳门  MACAO",
"台湾  TAIWAN  TW",
"台北  TAIBEI",
"高雄  GAOXIONG",
"基隆  JILONG",
"台中  TAIZHONG",
"台南  TAINAN",
"新竹  XINZHU",
"嘉义  JIAYI",
"宜兰县  YILANXIAN",
"桃园县  TAOYUANXIAN",
"苗栗县  MIAOLIXIAN",
"彰化县  ZHANGHUAXIAN",
"南投县  NANTOUXIAN",
"云林县  YUNLINXIAN",
"屏东县  PINGDONGXIAN",
"台东县  TAIDONGXIAN",
"花莲县  HUALIANXIAN",
"澎湖县  PENGHUXIAN",
"亚洲  Asia",
"蒙古  Mongolia",
"朝鲜  North Korea",
"韩国  Korea",
"日本  Japan",
"菲律宾  Philippines",
"越南  Vietnam",
"老挝  Laos",
"柬埔寨  Cambodia",
"缅甸  Burma",
"泰国  Thailand",
"马来西亚  Malaysia",
"文莱  Brunei",
"新加坡  Singapore",
"印度尼西亚  Indonesia",
"东帝汶  east Timor",
"尼泊尔  Nepal",
"不丹  Bhutan",
"孟加拉  Bangladesh",
"印度  India",
"巴基斯坦  Pakistan",
"斯里兰卡  Sri Lanka",
"马尔代夫  Maldives",
"哈萨克斯坦  Kazakhstan",
"吉尔吉斯  Kyrghyzstan",
"塔吉克斯坦  Tajikistan",
"乌兹别克  Uzbekistan",
"土库曼斯坦  Turkmenistan",
"阿富汗  Afghanistan",
"伊拉克  Iraq",
"伊朗  Iran",
"叙利亚  Syria",
"约旦  Jordan",
"黎巴嫩  Lebanon",
"以色列  Israel",
"巴勒斯坦  Palestine",
"沙特阿拉伯  Saudi Arabia",
"巴林  Bahrain",
"卡塔尔  Qatar",
"科威特  Kuwait",
"阿联酋  United Arab Emirates",
"阿曼  Oman",
"也门  Yemen",
"格鲁吉亚  Georgia",
"亚美尼亚  Armenia",
"阿塞拜疆  Azerbaijan",
"土耳其  Turkey",
"塞浦路斯  Cyprus",
"北美洲  North America",
"加拿大  Canada",
"阿尔伯塔省  Alberta",
"卡尔加里  Calgary",
"埃德蒙顿  Edmonton",
"不列颠哥伦比亚省  British Columbia",
"温哥华  Vancouver",
"素里  Surrey",
"本拿比  Burnaby",
"列治文  Richmond",
"曼尼托巴省  Manitoba",
"温尼伯  Winnipeg",
"纽芬兰与拉布拉多省  Newfoundland and Labrador",
"新不伦瑞克省  New Brunswick",
"新斯科舍省  Nova Scotia",
"哈利法克斯  Halifax",
"安大略省  Ontario",
"多伦多  Toronto  DLM",
"渥太华  Ottawa",
"密西沙加  Mississauga",
"宾顿  Brampton",
"汉密尔顿  Hamilton",
"伦敦  London",
"万锦  Markham",
"旺市  Vaughan",
"基奇纳  Kitchener",
"温莎  Windsor",
"列治文山  Richmond Hill",
"奥克维尔  Okville",
"伯灵顿  Burlington",
"萨德伯里  Greater Sudbury",
"爱德华王子岛省  Prince Edward Island",
"魁北克省  Quebec",
"蒙特利尔  Montreal",
"魁北克城  Quebec City",
"拉瓦尔  Laval",
"加蒂诺  Gatineau",
"朗基尔  Longueuil",
"舍布鲁克  Sherbrooke",
"萨斯喀彻温省  Saskatchewan",
"萨斯卡通  Saskatoon",
"里贾纳  Regina",
"努纳武特地区  Nunavut",
"西北地区  Northwest Territories",
"育空地区  Yukon",
"美国  America",
"亚拉巴马州  Alabama",
"伯明翰  Birmingham",
"蒙哥马利  Montgomery",
"亨次维尔  Huntsville",
"塔斯卡卢萨  Tuscaloosa",
"莫比尔港  Mobile",
"阿拉斯加州  Alaska",
"朱诺  Juneau",
"安克拉奇  Anchorage",
"亚利桑那州  Arizona",
"菲尼克斯 凤凰城   Phoenix",
"图森  Tucson",
"阿肯色州  Arkansas",
"小石城  Little Rock",
"加利福尼亚州  California",
"萨克拉门托  Sacramento",
"索诺马  Sonoma",
"圣荷西  San Jose",
"洛杉矶  Los Angeles",
"圣地亚哥  San Diego",
"科罗拉多州  Colorado",
"丹佛  Denver",
"波尔德  Boulder",
"康涅狄格州  Connecticut",
"特拉华州  Delaware",
"多佛  Dover",
"维明顿  Wilmington",
"纽华克  Newark",
"佛罗里达州  Florida",
"塔拉赫西  Tallahassee",
"坦帕  Tampa",
"杰克逊维尔  Jacksonville",
"迈阿密  Miami",
"乔治亚州  Georgia",
"亚特兰大  Atlanta",
"哥伦布  Columbus",
"夏威夷州  Hawaii",
"爱达荷州  Boise",
"波夕  Atlanta",
"波卡特洛  Pocatello",
"伊利诺伊州  Illinois",
"春田  Springfield",
"芝加哥  Chicago",
"印第安那州  Indiana",
"印第安纳波利斯  Indianapolis",
"韦恩堡  Fort Wayne",
"伯明顿  Bloomington",
"爱荷华州  Iowa",
"得梅因  Des Moines",
"锡达拉皮兹  Cedar Rapids",
"丹芬堡特  Daven Port",
"堪萨斯州  Kansas",
"托皮卡  Topeka",
"威奇托  Wichita",
"堪萨斯城  Kansas City",
"肯塔基州  Kentucky",
"路易斯维尔  Louisville",
"列克星敦  Lexington",
"路易斯安那州  Louisiana",
"新奥尔良  New Orleans",
"缅因州  Maine",
"奥古斯塔  Augusta",
"马里兰州  Maryland",
"安纳波利斯  Annapolis",
"巴尔的摩  Baltimore",
"麻萨诸塞州  Massachusetts",
"波士顿  Boston",
"密歇根州  Michigan",
"兰辛  Lansing",
"底特律  Detroit",
"大溪城  Grand Rapids",
"明尼苏达州  Minnesota",
"圣保罗  Saint Paul",
"明尼阿波利斯  Minneapolis",
"密西西比州  Mississippi",
"杰克逊  Jackson",
"密苏里州  Missouri",
"杰佛逊城  Jefferson City",
"圣路易斯  Saint Louis",
"堪萨斯城  Kansas City",
"洛拉  Rolla",
"蒙大拿州  Montana",
"海伦娜  Heldna  HLU",
"比林斯  Billings",
"密苏拉  Missoula",
"内布拉斯加州  Nebraska",
"林肯  Lincoln",
"内华达州  Nevada",
"卡森城  Carson City",
"拉斯维加斯  Las Vegas",
"里诺  Reno",
"新罕布什尔州  New Hampshire",
"曼彻斯特  Manchester",
"南雪  Nashua",
"朴次茅斯  Portsmouth",
"新泽西州  New Jersey",
"纽瓦克  Newark",
"泽西市  Jersey City",
"大西洋城  Atlantic City",
"依丽沙白  Elizabeth",
"新墨西哥州  New Mexico",
"圣达菲  Santa Fe",
"阿尔布开克  Albuquerque",
"纽约州  New York",
"奥尔巴尼 水牛城   Albany",
"布法罗  Buffalo",
"长岛  Long Island  CDO",
"纽约  New York City",
"罗彻斯特市  Rochester",
"绮色佳  Ithaca",
"北卡罗莱纳州  North Carolina",
"洛利  Raleigh",
"夏洛特  Charlotte",
"格林斯堡  Greensboro",
"查伯山  Chapel Hill",
"阿什维尔  Asheville",
"北达科他州  North Dakota",
"俾斯麦  Bismark",
"法戈  Fargo",
"俄亥俄州  Ohio",
"哥伦布  Columbus",
"克利夫兰  Cleveland",
"辛辛那提  Cincinnati",
"俄克拉何马州  Oklahoma",
"俄克拉何马城  OklahomaCity",
"塔尔萨  Tulsa",
"劳顿  Lawton",
"诺曼城  Norman",
"俄勒冈州  Oregon",
"塞伦  Salem",
"波特兰  Portland",
"尤金  Eugene",
"科瓦利  Corvallis",
"宾夕法尼亚州  Pennsylvania",
"哈里斯堡  Harrisburg",
"南卡罗来纳州  South Carolina",
"哥伦比亚  Columbia",
"查理斯敦  North Charleston",
"格林威尔  Greenville",
"阿干  Aiken",
"美特尔沙滨  Myrtle Beach",
"克伦孙  Clemson",
"南达科他州  South Dakota",
"苏瀑市  Sioux Falls",
"拉皮特城  Rapid City",
"田纳西州  Tennessee",
"那什维尔  Nemphis",
"孟斐斯  Memphis",
"诺克斯维尔  Knoxville",
"橡树岭  Oak Ridge",
"德克萨斯州  Texas",
"奧斯汀  Austin",
"休斯顿  Houston",
"达拉斯  Dallas",
"犹他州  Utah",
"盐湖城  Salt Lake City",
"奥格登  Ogden",
"普罗沃  Provo",
"佛蒙特州  Vermont",
"拉特兰  Rutland",
"弗吉尼亚州  Virginia",
"里齐蒙得  Richmond",
"诺福克  Norfolk",
"弗吉尼亚滩  Virginia Beach",
"华盛顿州  Washington",
"奥林匹亚  Olympia",
"罗得岛州  Rhode Island",
"普洛威顿斯  Providence",
"纽波特  Newport",
"西佛吉尼亚州  West Virginia",
"查理斯敦  Charleston",
"亨丁顿  Huntington",
"摩根敦  Morgantown",
"威斯康星州  Wisconsin",
"麦迪逊  Madison",
"密尔沃基  Milwaukee",
"拉辛  Racine",
"怀俄明州  Wyoming",
"夏延  Cheyenne",
"卡斯柏  Casper",
"拉阿密  Laramie",
"华盛顿哥伦比亚特区  Washington DC",
"墨西哥  Mexico",
"格陵兰  Greenland",
"危地马拉  Guatemala",
"伯利兹  Belize",
"萨尔瓦多  Salvador",
"洪都拉斯  Honduras",
"尼加拉瓜  Nicaragua",
"哥斯达黎加  Costa Rica",
"巴拿马  Panama",
"巴哈马  Bahamas",
"古巴  Cuba",
"牙买加  Jamaica",
"海地  Haiti",
"多米尼加  Dominican Republic",
"安提瓜  Antigua and Barbuda",
"圣基茨  St. Kitts and Nevis",
"多米尼克  Dominica",
"圣卢西亚  Saint Lucia",
"圣文森特  Saint Vincent and the Grenadines",
"格林纳达  Grenada",
"巴巴多斯  Barbados",
"特立尼达  Trinidad and Tobago",
"波多黎各  Puerto Rico",
"英属维尔京  British Virgin Islands",
"美属维尔京  Virgin Islands",
"安圭拉  Anguilla",
"蒙特塞拉特  Montserrat",
"瓜德罗普  Guadeloupe",
"马提尼克  martinique",
"安的列斯  Nederlandse Antillen",
"阿鲁巴  Aruba",
"特克斯  The turks and caicos islands  TEK",
"开曼群岛  Cayman Islands",
"百慕大  Bermuda",
"南美洲  South America",
"哥伦比亚  Columbia",
"委内瑞拉  Venezuela",
"圭亚那  Guyana",
"法属圭亚那  French Guiana",
"苏里南  Surinam",
"厄瓜多尔  Ecuador",
"秘鲁  Peru",
"玻利维亚  Bolivia",
"巴西  Brazil",
"智利  Chile",
"阿根廷  Argentina",
"乌拉圭  Uruguay",
"巴拉圭  Paraguay",
"大洋洲  Oceania",
"澳大利亚  Australia",
"新西兰  New Zealand",
"巴布亚  Papua New Guinea",
"所罗门群岛  Solomon Islands",
"瓦努阿图  Vanuatu",
"马绍尔群岛  Marshall Islands",
"帕劳群岛  Palau",
"瑙鲁  Nauru",
"基里巴斯  Kiribati",
"图瓦卢  Tuvalu",
"萨摩亚  Samoa",
"斐济群岛  Fiji Islands",
"汤加  Tonga",
"库克群岛  Cook Islands",
"关岛  Guam",
"波利尼西亚  Polynesia",
"皮特凯恩岛  Pitcairn Island",
"瓦利斯  Wallis and Futuna",
"纽埃  Niue",
"托克劳  Tokelau",
"美属萨摩亚  American Samoa",
"北马里亚纳  Northern Marianas",
"密克罗尼西亚  Micronesia",
"新喀里多尼亚  New Caledonia",
"欧洲  Europe",
"芬兰  Finland",
"瑞典  Sweden",
"挪威  Norway",
"冰岛  Iceland",
"丹麦  Denmark",
"法罗群岛  Faroe islands",
"爱沙尼亚  Estonia",
"拉脱维亚  Latvia",
"立陶宛  Lithuania",
"白俄罗斯  The Republic of Belarus",
"俄罗斯  Russia",
"乌克兰  Ukraine",
"摩尔多瓦  Moldova",
"波兰  Poland",
"捷克  Czechoslovakia",
"斯洛伐克  The Slovak Republic",
"匈牙利  Hungary",
"德国  Germany",
"奥地利  Austria",
"瑞士  Switzerland",
"列支敦士登  Liechtenstein",
"英国  United Kingdom",
"爱尔兰  Ireland",
"荷兰  Netherlands",
"比利时  Belgium",
"卢森堡  Luxembourg",
"法国  France",
"摩纳哥  Monaco",
"罗马尼亚  Roumania",
"保加利亚  Bulgaria",
"塞尔维亚  Serbia",
"马其顿  Macedonia",
"阿尔巴尼亚  Albania",
"希腊  Greece",
"斯洛文尼亚  Slovenia",
"克罗地亚  Croatia",
"波墨  Bosnia and ink plug elder brother d that",
"意大利  Italy",
"梵蒂冈  Vatican",
"圣马力诺  San Marino",
"马耳他  Malta",
"西班牙  Spain",
"葡萄牙  Portugal",
"安道尔  Andorra",
"非洲  Africa",
"埃及  Egypt",
"利比亚  Libya",
"苏丹  Sultan",
"突尼斯  Tunisia",
"阿尔及利亚  Algeria",
"摩洛哥  Morocco",
"亚速尔群岛  Azores",
"马德拉群岛  Madeira",
"埃塞俄比亚  Ethiopia",
"厄立特里亚  Eritrea",
"索马里  Somalia",
"吉布提  Djibouti",
"肯尼亚  Kenya",
"坦桑尼亚  Tanzania",
"乌干达  Uganda",
"卢旺达  Rwanda",
"布隆迪  Burundi",
"塞舌尔  Seychelles",
"乍得  Chad",
"中非  Central Africa",
"喀麦隆  Cameroon",
"赤道几内亚  Equatorial Guinea",
"加蓬  Gabon",
"刚果  Congo",
"圣普  Sao Tome and Principe",
"毛里塔尼亚  Mauritania",
"西撒哈拉  EH West Sahara",
"塞内加尔  Senegal",
"冈比亚  Gambia",
"马里  Mali",
"布基纳法索  Burkina faso",
"几内亚  Guinea",
"几内亚比绍  Guinea-Bissau",
"佛得角  Cape Verde",
"塞拉利昂  Sierra leone",
"利比里亚  Liberia",
"科特迪瓦  Cote d'ivoire",
"加纳  Ghana",
"多哥  Togo",
"贝宁  Benin",
"尼日尔  The Niger",
"加那利群岛  Canary Islands",
"赞比亚  Zambia",
"安哥拉  Angola",
"津巴布韦  Zimbabwe",
"马拉维  Malawi",
"莫桑比克  Mozambique",
"博茨瓦纳  Botswana",
"纳米比亚  Namibia",
"南非  South Africa",
"斯威士兰  Swaziland",
"莱索托  Lesotho",
"马达加斯加  Madagascar",
"科摩罗  Comorin",
"毛里求斯  Mauritius",
"留尼旺  Reunion",
"圣赫勒拿  Saint Helena",
"尼日利亚  Federal Republic of Nigeria",
"海外及港澳台  海外及港澳台",]
value_list = ["北京",
"东城区",
"西城区",
"朝阳区",
"海淀区",
"石景山",
"门头沟",
"丰台区",
"房山区",
"大兴区",
"通州区",
"顺义区",
"平谷区",
"昌平区",
"怀柔区",
"延庆县",
"密云县",
"上海",
"浦东新区",
"徐汇区",
"长宁区",
"普陀区",
"闸北区",
"虹口区",
"杨浦区",
"黄浦区",
"静安区",
"宝山区",
"闵行区",
"嘉定区",
"金山区",
"松江区",
"青浦区",
"奉贤区",
"崇明县",
"天津",
"和平区",
"河东区",
"河西区",
"南开区",
"河北区",
"红桥区",
"塘沽区",
"汉沽区",
"大港区",
"东丽区",
"西青区",
"津南区",
"北辰区",
"武清区",
"宝坻区",
"宁河县",
"静海县",
"蓟　县",
"开发区",
"滨海区",
"重庆",
"渝中区",
"江北区",
"南岸区",
"沙坪坝",
"九龙坡",
"大渡口",
"北碚区",
"巴南区",
"渝北区",
"永川区",
"涪陵区",
"合川区",
"江津区",
"长寿区",
"南川区",
"万州区",
"黔江区",
"綦江区",
"潼南县",
"铜梁区",
"大足区",
"荣昌县",
"璧山区",
"垫江县",
"武隆县",
"丰都县",
"城口县",
"梁平县",
"开县",
"巫溪县",
"巫山县",
"奉节县",
"云阳县",
"忠县",
"石柱",
"彭水县",
"酉阳县",
"石柱县",
"秀山县",
"广东省",
"广州",
"白云区",
"天河区",
"越秀区",
"海珠区",
"黄埔区",
"荔湾区",
"番禺区",
"花都区",
"萝岗区",
"南沙区",
"从化区",
"增城区",
"潮州",
"东莞",
"南城区",
"东城区",
"万江区",
"莞城区",
"石龙镇",
"虎门镇",
"麻涌镇",
"道滘镇",
"石碣镇",
"沙田镇",
"望牛墩",
"洪梅镇",
"茶山镇",
"寮步镇",
"大岭山",
"大朗镇",
"黄江镇",
"樟木头",
"凤岗镇",
"塘厦镇",
"谢岗镇",
"厚街镇",
"清溪镇",
"常平镇",
"桥头镇",
"横沥镇",
"东坑镇",
"企石镇",
"石排镇",
"长安镇",
"中堂镇",
"高埗镇",
"松山湖",
"佛山",
"禅城区",
"南海区",
"顺德区",
"三水区",
"高明区",
"新城区",
"大沥",
"黄岐",
"西樵",
"南庄",
"惠州",
"清远",
"汕头",
"深圳",
"罗湖区",
"福田区",
"南山区",
"宝安区",
"龙岗区",
"盐田区",
"光明新区",
"坪山新区",
"大鹏新区",
"龙华新区",
"顺德",
"湛江",
"肇庆",
"中山",
"珠海",
"香洲区",
"斗门区",
"金湾区",
"横琴新区",
"江门",
"阳江",
"韶关",
"茂名",
"梅州",
"汕尾",
"河源",
"揭阳",
"云浮",
"开平",
"台山",
"普宁",
"南沙",
"龙川",
"鹤山",
"江苏省",
"南京",
"玄武区",
"白下区",
"秦淮区",
"建邺区",
"鼓楼区",
"下关区",
"浦口区",
"六合区",
"栖霞区",
"雨花台",
"江宁区",
"溧水县",
"高淳县",
"大厂区",
"常熟",
"常州",
"天宁区",
"钟楼区",
"戚墅堰",
"郊区",
"新北区",
"武进区",
"溧阳市",
"金坛市",
"昆山",
"连云港",
"南通",
"苏州",
"金阊区",
"沧浪区",
"平江区",
"工业园",
"高新区",
"吴中区",
"相城区",
"张家港",
"常熟市",
"太仓市",
"昆山市",
"吴江市",
"虎丘区",
"玉山镇",
"巴城镇",
"周市镇",
"陆家镇",
"花桥镇",
"淀山湖",
"张浦镇",
"周庄镇",
"千灯镇",
"锦溪镇",
"开发区",
"太仓",
"无锡",
"崇安区",
"北塘区",
"南长区",
"锡山区",
"惠山区",
"滨湖区",
"新区",
"宜兴市",
"江阴市",
"徐州",
"扬州",
"镇江",
"淮安",
"盐城",
"泰州  TAI_",
"宿迁",
"张家港",
"江阴",
"丹阳",
"溧阳",
"泰兴",
"宜兴",
"靖江",
"句容",
"如皋",
"扬中",
"高邮",
"启东",
"盱眙",
"通州",
"金湖",
"浙江省",
"杭州",
"上城区",
"下城区",
"拱墅区",
"西湖区",
"江干区",
"滨江区",
"萧山区",
"余杭区",
"临安市",
"富阳区",
"建德市",
"桐庐县",
"淳安县",
"市郊",
"宁波",
"海曙区",
"江东区",
"江北区",
"镇海区",
"北仑区",
"鄞州区",
"余姚市",
"慈溪市",
"奉化市",
"象山县",
"宁海县",
"温州",
"鹿城区",
"龙湾区",
"瓯海区",
"瑞安市",
"乐清市",
"洞头县",
"永嘉县",
"平阳县",
"苍南县",
"文成县",
"泰顺县",
"绍兴",
"金华",
"台州",
"湖州",
"嘉兴",
"衢州",
"丽水",
"舟山",
"义乌",
"海宁",
"玉环县",
"平湖",
"永康",
"东阳",
"嘉善",
"余姚",
"慈溪",
"乐清",
"永嘉",
"桐乡",
"瑞安",
"温岭",
"上虞",
"诸暨",
"宁海",
"三门",
"德清",
"象山",
"方家山",
"龙泉",
"安徽省",
"合肥",
"庐阳区",
"瑶海区",
"蜀山区",
"包河区",
"长丰县",
"肥东县",
"肥西县",
"新站区",
"经开区",
"高新区",
"滨湖区",
"北城区",
"政务区",
"安庆",
"蚌埠",
"芜湖",
"淮南",
"马鞍山",
"淮北",
"铜陵",
"黄山",
"滁州",
"阜阳",
"宿州  SU_",
"六安",
"亳州",
"池州",
"宣城",
"巢湖",
"凤阳",
"广德",
"宿松",
"福建省",
"福州",
"鼓楼区",
"台江区",
"仓山区",
"马尾区",
"晋安区",
"福清市",
"长乐市",
"闽侯县",
"连江县",
"罗源县",
"闽清县",
"永泰县",
"平潭县",
"泉州",
"厦门",
"思明区",
"海沧区",
"湖里区",
"集美区",
"同安区",
"翔安区",
"漳州",
"莆田",
"三明",
"南平",
"龙岩",
"宁德",
"泉港区",
"福安",
"晋江",
"甘肃省",
"兰州",
"皋兰县",
"城关区",
"七里河",
"西固区",
"安宁区",
"红古区",
"永登县",
"榆中县",
"嘉峪关",
"酒泉",
"金昌",
"白银",
"天水",
"张掖",
"武威",
"定西",
"陇南",
"平凉",
"庆阳",
"临夏",
"甘南",
"广西",
"南宁",
"邕宁区",
"青秀区",
"兴宁区",
"良庆区",
"西乡塘",
"江南区",
"武鸣县",
"隆安县",
"马山县",
"上林县",
"宾阳县",
"横县",
"北海",
"桂林",
"柳州",
"玉林",
"梧州",
"崇左",
"来宾",
"防城港",
"百色",
"钦州",
"贺州",
"河池",
"贵港",
"贵州省",
"贵阳",
"南明区",
"云岩区",
"花溪区",
"乌当区",
"白云区",
"小河区",
"金阳区",
"新天园",
"清镇市",
"开阳县",
"修文县",
"息烽县",
"遵义",
"六盘水",
"安顺",
"毕节",
"铜仁",
"黔西南",
"黔东南",
"黔南",
"海南省",
"海口",
"秀英区",
"龙华区",
"琼山区",
"美兰区",
"澄迈县",
"万宁市",
"文昌市",
"儋州市",
"屯昌县",
"东方市",
"昌江县",
"乐东黎",
"临高县",
"琼海市",
"府城",
"三亚",
"三沙",
"文昌",
"琼海",
"万宁",
"儋州",
"东方",
"五指山",
"定安",
"屯昌",
"澄迈",
"临高",
"琼中",
"保亭",
"白沙",
"昌江",
"乐东",
"陵水",
"河北省",
"石家庄",
"长安区",
"桥东区",
"桥西区",
"新华区",
"裕华区",
"井陉矿",
"高新区",
"辛集市",
"藁城市",
"晋州市",
"新乐市",
"鹿泉市",
"井陉县",
"正定县",
"栾城县",
"行唐县",
"灵寿县",
"高邑县",
"深泽县",
"赞皇县",
"无极县",
"平山县",
"元氏县",
"赵县",
"保定",
"承德",
"邯郸",
"廊坊",
"秦皇岛",
"唐山",
"张家口",
"邢台",
"沧州",
"衡水",
"燕郊",
"固安",
"遵化",
"香河",
"三河",
"河南省",
"郑州",
"金水区",
"邙山区",
"二七区",
"管城区",
"中原区",
"上街区",
"惠济区",
"郑东区",
"经济区",
"高新区",
"加工区",
"巩义市",
"荥阳市",
"新密市",
"新郑市",
"登封市",
"中牟县",
"开封",
"洛阳",
"商丘",
"安阳",
"平顶山",
"新乡",
"焦作",
"濮阳",
"许昌",
"漯河",
"三门峡",
"鹤壁",
"周口",
"驻马店",
"南阳",
"信阳",
"济源",
"西平",
"长葛",
"黑龙江省",
"哈尔滨",
"道里区",
"南岗区",
"动力区",
"平房区",
"香坊区",
"太平区",
"道外区",
"阿城市",
"呼兰区",
"松北区",
"尚志市",
"双城市",
"五常市",
"方正县",
"宾县",
"依兰县",
"巴彦县",
"通河县",
"木兰县",
"延寿县",
"大庆",
"佳木斯",
"牡丹江",
"齐齐哈尔",
"鸡西",
"鹤岗",
"双鸭山",
"伊春",
"七台河",
"黑河",
"绥化",
"大兴安岭",
"安达",
"双城",
"尚志",
"绥芬河",
"肇东",
"湖北省",
"武汉",
"江岸区",
"江汉区",
"硚口区",
"汉阳区",
"武昌区",
"青山区",
"洪山区",
"蔡甸区",
"江夏区",
"黄陂区",
"新洲区",
"东西湖",
"汉南区",
"开发区",
"十堰",
"襄阳",
"宜昌",
"潜江",
"荆门",
"荆州",
"黄石",
"鄂州",
"黄冈",
"孝感",
"咸宁",
"随州",
"仙桃",
"天门",
"神农架",
"恩施",
"公安",
"武穴",
"宜城",
"湖南省",
"长沙",
"岳麓区",
"芙蓉区",
"天心区",
"开福区",
"雨花区",
"开发区",
"浏阳市",
"长沙县",
"望城区",
"宁乡县",
"湘潭",
"株洲",
"常德",
"衡阳",
"益阳",
"郴州",
"岳阳",
"邵阳",
"张家界",
"娄底",
"永州",
"怀化",
"湘西",
"吉林省",
"长春",
"朝阳区",
"宽城区",
"二道区",
"南关区",
"绿园区",
"双阳区",
"净月区",
"高新区",
"经开区",
"汽开区",
"德惠市",
"九台市",
"榆树市",
"农安县",
"高新区",
"经济区",
"净月区",
"吉林市",
"四平",
"辽源",
"通化",
"白山",
"松原",
"白城",
"延吉",
"延边",
"公主岭",
"江西省",
"南昌",
"东湖区",
"西湖区",
"青云谱",
"湾里区",
"青山湖",
"红谷滩",
"昌北区",
"高新区",
"南昌县",
"新建县",
"安义县",
"进贤县",
"桑海区",
"九江",
"赣州",
"宜春  YI_",
"吉安",
"上饶",
"抚州  FU_",
"景德镇",
"萍乡",
"新余",
"鹰潭",
"辽宁省",
"沈阳",
"沈河区",
"皇姑区",
"和平区",
"大东区",
"铁西区",
"苏家屯",
"东陵区",
"沈北区",
"于洪区",
"浑南区",
"新民市",
"辽中县",
"康平县",
"法库县",
"鞍山",
"大连",
"西岗区",
"中山区",
"沙河口",
"甘井子",
"旅顺口",
"金州区",
"瓦房店",
"普兰店",
"庄河市",
"普湾区",
"长海县",
"新区",
"开发区",
"葫芦岛",
"抚顺",
"本溪",
"丹东",
"锦州",
"营口",
"阜新",
"辽阳",
"盘锦",
"铁岭",
"朝阳",
"兴城",
"海城",
"昌图",
"开原",
"内蒙古",
"呼和浩特",
"回民区",
"玉泉区",
"新城区",
"赛罕区",
"清水河",
"土左旗",
"托克托",
"格尔县",
"武川县",
"包头",
"赤峰",
"鄂尔多斯",
"乌海",
"通辽",
"呼伦贝尔",
"巴彦淖尔",
"乌兰察布",
"兴安盟",
"锡林郭勒盟",
"阿拉善盟",
"乌审旗",
"满洲里",
"宁夏",
"银川",
"西夏区",
"金凤区",
"兴庆区",
"灵武市",
"永宁县",
"贺兰县",
"中卫",
"石嘴山",
"吴忠",
"青铜峡",
"石嘴山",
"吴忠",
"固原",
"中卫",
"青海省",
"西宁",
"城中区",
"城东区",
"城西区",
"城北区",
"湟中县",
"湟源县",
"大通",
"城南区",
"海湖区",
"海东",
"海西",
"海北",
"黄南",
"海南",
"果洛",
"玉树",
"山东省",
"济南",
"市中区",
"历下区",
"天桥区",
"槐荫区",
"历城区",
"长清区",
"章丘市",
"平阴县",
"济阳县",
"商河县",
"高新区",
"近郊",
"德州",
"东营",
"济宁",
"临沂",
"青岛",
"市南区",
"市北区",
"城阳区",
"四方区",
"李沧区",
"黄岛区",
"崂山区",
"胶州市",
"即墨市",
"平度市",
"胶南市",
"莱西市",
"日照",
"泰安",
"威海",
"潍坊",
"烟台",
"淄博",
"枣庄",
"滨州",
"聊城",
"菏泽",
"莱芜",
"荣成",
"黄岛",
"乳山",
"城阳",
"即墨",
"肥城",
"兖州",
"海阳",
"胶州",
"胶南",
"平度",
"莱西",
"山西省",
"太原",
"杏花岭",
"小店区",
"迎泽区",
"尖草坪",
"万柏林",
"晋源区",
"高新区",
"开发区",
"工业园",
"清徐县",
"阳曲县",
"娄烦县",
"古交市",
"大同",
"临汾",
"运城",
"长治",
"阳泉",
"晋城",
"朔州",
"晋中",
"忻州",
"吕梁",
"永济",
"和顺",
"陕西省",
"西安",
"宝鸡",
"咸阳",
"铜川",
"渭南",
"汉中",
"安康",
"商洛",
"延安",
"榆林  YU_",
"杨凌",
"兴平",
"四川省",
"成都",
"成华区",
"武侯区",
"青羊区",
"锦江区",
"金牛区",
"龙泉驿",
"青白江",
"新都区",
"双流县",
"郫县",
"温江区",
"大邑县",
"金堂县",
"蒲江县",
"新津县",
"温江区",
"高新区",
"高新西",
"都江堰",
"彭州市",
"邛崃市",
"崇州市",
"乐山",
"泸州",
"绵阳",
"内江",
"宜宾",
"自贡",
"攀枝花",
"德阳",
"广元",
"遂宁",
"南充",
"眉山",
"广安",
"达州",
"雅安",
"巴中",
"资阳",
"西昌",
"甘孜",
"阿坝",
"凉山",
"峨眉",
"简阳",
"西藏",
"拉萨",
"城关区",
"林周县",
"当雄县",
"尼木县",
"曲水县",
"龙德庆",
"达孜县",
"工卡县",
"日喀则",
"林芝",
"山南",
"昌都",
"那曲",
"阿里",
"新疆",
"乌鲁木齐",
"天山区",
"巴克区",
"新市区",
"水磨沟",
"头屯河",
"达坂城",
"米东区",
"乌县",
"昌吉市",
"五家渠",
"阜康市",
"喀什",
"克拉玛依",
"伊犁",
"阿克苏",
"哈密",
"石河子",
"阿拉尔",
"五家渠",
"图木舒克",
"昌吉",
"阿勒泰",
"吐鲁番",
"塔城",
"和田",
"巴音郭楞",
"博尔塔拉",
"奎屯市",
"乌苏",
"克州",
"云南省",
"昆明",
"盘龙区",
"五华区",
"官渡区",
"西山区",
"东川区",
"安宁市",
"呈贡新",
"晋宁新",
"富民区",
"宜良区",
"嵩明区",
"石林县",
"禄劝",
"寻甸",
"大理",
"丽江",
"玉溪",
"曲靖",
"保山",
"昭通",
"普洱",
"临沧",
"红河",
"文山",
"西双版纳",
"德宏",
"楚雄",
"怒江",
"迪庆",
"思茅",
"香港",
"沙田区",
"东区",
"观塘区",
"黄大仙",
"九龙城",
"屯门区",
"葵青区",
"元朗区",
"深水埗",
"西贡区",
"大埔区",
"湾仔区",
"油尖旺",
"北区",
"南区",
"荃湾区",
"中西区",
"离岛区",
"澳门",
"台湾",
"台北",
"高雄",
"基隆",
"台中",
"台南",
"新竹",
"嘉义",
"宜兰县",
"桃园县",
"苗栗县",
"彰化县",
"南投县",
"云林县",
"屏东县",
"台东县",
"花莲县",
"澎湖县",
"亚洲",
"蒙古",
"朝鲜",
"韩国",
"日本",
"菲律宾",
"越南",
"老挝",
"柬埔寨",
"缅甸",
"泰国",
"马来西亚",
"文莱",
"新加坡",
"印度尼西亚",
"东帝汶",
"尼泊尔",
"不丹",
"孟加拉",
"印度",
"巴基斯坦",
"斯里兰卡",
"马尔代夫",
"哈萨克斯坦",
"吉尔吉斯",
"塔吉克斯坦",
"乌兹别克",
"土库曼斯坦",
"阿富汗",
"伊拉克",
"伊朗",
"叙利亚",
"约旦",
"黎巴嫩",
"以色列",
"巴勒斯坦",
"沙特阿拉伯",
"巴林",
"卡塔尔",
"科威特",
"阿联酋",
"阿曼",
"也门",
"格鲁吉亚",
"亚美尼亚",
"阿塞拜疆",
"土耳其",
"塞浦路斯",
"北美洲",
"加拿大",
"阿尔伯塔省",
"卡尔加里",
"埃德蒙顿",
"不列颠哥伦比亚省",
"温哥华",
"素里",
"本拿比",
"列治文",
"曼尼托巴省",
"温尼伯",
"纽芬兰与拉布拉多省",
"新不伦瑞克省",
"新斯科舍省",
"哈利法克斯",
"安大略省",
"多伦多",
"渥太华",
"密西沙加",
"宾顿",
"汉密尔顿",
"伦敦",
"万锦",
"旺市",
"基奇纳",
"温莎",
"列治文山",
"奥克维尔",
"伯灵顿",
"萨德伯里",
"爱德华王子岛省",
"魁北克省",
"蒙特利尔",
"魁北克城",
"拉瓦尔",
"加蒂诺",
"朗基尔",
"舍布鲁克",
"萨斯喀彻温省",
"萨斯卡通",
"里贾纳",
"努纳武特地区",
"西北地区",
"育空地区",
"美国",
"亚拉巴马州",
"伯明翰",
"蒙哥马利",
"亨次维尔",
"塔斯卡卢萨",
"莫比尔港",
"阿拉斯加州",
"朱诺",
"安克拉奇",
"亚利桑那州",
"菲尼克斯 凤凰城",
"图森",
"阿肯色州",
"小石城",
"加利福尼亚州",
"萨克拉门托",
"索诺马",
"圣荷西",
"洛杉矶",
"圣地亚哥",
"科罗拉多州",
"丹佛",
"波尔德",
"康涅狄格州",
"特拉华州",
"多佛",
"维明顿",
"纽华克",
"佛罗里达州",
"塔拉赫西",
"坦帕",
"杰克逊维尔",
"迈阿密",
"乔治亚州",
"亚特兰大",
"哥伦布",
"夏威夷州",
"爱达荷州",
"波夕",
"波卡特洛",
"伊利诺伊州",
"春田",
"芝加哥",
"印第安那州",
"印第安纳波利斯",
"韦恩堡",
"伯明顿",
"爱荷华州",
"得梅因",
"锡达拉皮兹",
"丹芬堡特",
"堪萨斯州",
"托皮卡",
"威奇托",
"堪萨斯城",
"肯塔基州",
"路易斯维尔",
"列克星敦",
"路易斯安那州",
"新奥尔良",
"缅因州",
"奥古斯塔",
"马里兰州",
"安纳波利斯",
"巴尔的摩",
"麻萨诸塞州",
"波士顿",
"密歇根州",
"兰辛",
"底特律",
"大溪城",
"明尼苏达州",
"圣保罗",
"明尼阿波利斯",
"密西西比州",
"杰克逊",
"密苏里州",
"杰佛逊城",
"圣路易斯",
"堪萨斯城",
"洛拉",
"蒙大拿州",
"海伦娜",
"比林斯",
"密苏拉",
"内布拉斯加州",
"林肯",
"内华达州",
"卡森城",
"拉斯维加斯",
"里诺",
"新罕布什尔州",
"曼彻斯特",
"南雪",
"朴次茅斯",
"新泽西州",
"纽瓦克",
"泽西市",
"大西洋城",
"依丽沙白",
"新墨西哥州",
"圣达菲",
"阿尔布开克",
"纽约州",
"奥尔巴尼 水牛城",
"布法罗",
"长岛",
"纽约",
"罗彻斯特市",
"绮色佳",
"北卡罗莱纳州",
"洛利",
"夏洛特",
"格林斯堡",
"查伯山",
"阿什维尔",
"北达科他州",
"俾斯麦",
"法戈",
"俄亥俄州",
"哥伦布",
"克利夫兰",
"辛辛那提",
"俄克拉何马州",
"俄克拉何马城",
"塔尔萨",
"劳顿",
"诺曼城",
"俄勒冈州",
"塞伦",
"波特兰",
"尤金",
"科瓦利",
"宾夕法尼亚州",
"哈里斯堡",
"南卡罗来纳州",
"哥伦比亚",
"查理斯敦",
"格林威尔",
"阿干",
"美特尔沙滨",
"克伦孙",
"南达科他州",
"苏瀑市",
"拉皮特城",
"田纳西州",
"那什维尔",
"孟斐斯",
"诺克斯维尔",
"橡树岭",
"德克萨斯州",
"奧斯汀",
"休斯顿",
"达拉斯",
"犹他州",
"盐湖城",
"奥格登",
"普罗沃",
"佛蒙特州",
"拉特兰",
"弗吉尼亚州",
"里齐蒙得",
"诺福克",
"弗吉尼亚滩",
"华盛顿州",
"奥林匹亚",
"罗得岛州",
"普洛威顿斯",
"纽波特",
"西佛吉尼亚州",
"查理斯敦",
"亨丁顿",
"摩根敦",
"威斯康星州",
"麦迪逊",
"密尔沃基",
"拉辛",
"怀俄明州",
"夏延",
"卡斯柏",
"拉阿密",
"华盛顿哥伦比亚特区",
"墨西哥",
"格陵兰",
"危地马拉",
"伯利兹",
"萨尔瓦多",
"洪都拉斯",
"尼加拉瓜",
"哥斯达黎加",
"巴拿马",
"巴哈马",
"古巴",
"牙买加",
"海地",
"多米尼加",
"安提瓜",
"圣基茨  St.",
"多米尼克",
"圣卢西亚",
"圣文森特",
"格林纳达",
"巴巴多斯",
"特立尼达",
"波多黎各",
"英属维尔京",
"美属维尔京",
"安圭拉",
"蒙特塞拉特",
"瓜德罗普",
"马提尼克",
"安的列斯",
"阿鲁巴",
"特克斯",
"开曼群岛",
"百慕大",
"南美洲",
"哥伦比亚",
"委内瑞拉",
"圭亚那",
"法属圭亚那",
"苏里南",
"厄瓜多尔",
"秘鲁",
"玻利维亚",
"巴西",
"智利",
"阿根廷",
"乌拉圭",
"巴拉圭",
"大洋洲",
"澳大利亚",
"新西兰",
"巴布亚",
"所罗门群岛",
"瓦努阿图",
"马绍尔群岛",
"帕劳群岛",
"瑙鲁",
"基里巴斯",
"图瓦卢",
"萨摩亚",
"斐济群岛",
"汤加",
"库克群岛",
"关岛",
"波利尼西亚",
"皮特凯恩岛",
"瓦利斯",
"纽埃",
"托克劳",
"美属萨摩亚",
"北马里亚纳",
"密克罗尼西亚",
"新喀里多尼亚",
"欧洲",
"芬兰",
"瑞典",
"挪威",
"冰岛",
"丹麦",
"法罗群岛",
"爱沙尼亚",
"拉脱维亚",
"立陶宛",
"白俄罗斯",
"俄罗斯",
"乌克兰",
"摩尔多瓦",
"波兰",
"捷克",
"斯洛伐克",
"匈牙利",
"德国",
"奥地利",
"瑞士",
"列支敦士登",
"英国",
"爱尔兰",
"荷兰",
"比利时",
"卢森堡",
"法国",
"摩纳哥",
"罗马尼亚",
"保加利亚",
"塞尔维亚",
"马其顿",
"阿尔巴尼亚",
"希腊",
"斯洛文尼亚",
"克罗地亚",
"波墨",
"意大利",
"梵蒂冈",
"圣马力诺",
"马耳他",
"西班牙",
"葡萄牙",
"安道尔",
"非洲",
"埃及",
"利比亚",
"苏丹",
"突尼斯",
"阿尔及利亚",
"摩洛哥",
"亚速尔群岛",
"马德拉群岛",
"埃塞俄比亚",
"厄立特里亚",
"索马里",
"吉布提",
"肯尼亚",
"坦桑尼亚",
"乌干达",
"卢旺达",
"布隆迪",
"塞舌尔",
"乍得",
"中非",
"喀麦隆",
"赤道几内亚",
"加蓬",
"刚果",
"圣普",
"毛里塔尼亚",
"西撒哈拉",
"塞内加尔",
"冈比亚",
"马里",
"布基纳法索",
"几内亚",
"几内亚比绍  Guinea-",
"佛得角",
"塞拉利昂",
"利比里亚",
"科特迪瓦  Cote d'",
"加纳",
"多哥",
"贝宁",
"尼日尔",
"加那利群岛",
"赞比亚",
"安哥拉",
"津巴布韦",
"马拉维",
"莫桑比克",
"博茨瓦纳",
"纳米比亚",
"南非",
"斯威士兰",
"莱索托",
"马达加斯加",
"科摩罗",
"毛里求斯",
"留尼旺",
"圣赫勒拿",
"尼日利亚",
"海外及港澳台",]
# print(len(list1))
# print(len(value_list))

objects_l = []
objects = {}
for i in range(len(list1)):
    # print(list1[i])
    objects = {}
    objects['name'] = list1[i]
    objects['value'] = value_list[i]
    objects_l.append(objects)
# print(objects_l)


lis = ["/courses/info/?id=11799&title=Accounting+and+Finance&code=NN43&type=BA&year=2019",
"/courses/info/?id=12464&title=Accounting+and+Finance+with+Business+Placement&code=N302&type=BA&year=2019",
"/courses/info/?id=11868&title=Accounting+and+Finance+with+Foundation&code=NN4H&type=BA&year=2019",
"/courses/info/?id=12226&title=Accounting+and+Finance+with+Study+Abroad&code=N304&type=BA&year=2019",
"/courses/info/?id=12202&title=Accounting+and+Management&code=NN42&type=BA&year=2019",
"/courses/info/?id=12470&title=Accounting+and+Management+with+Business+Placement&code=N204&type=BA&year=2019",
"/courses/info/?id=12316&title=Accounting+and+Management+with+Foundation&code=N209&type=BA&year=2019",
"/courses/info/?id=12222&title=Accounting+and+Management+with+Study+Abroad&code=N206&type=BA&year=2019",
"/courses/info/?id=11528&title=Ancient+History&code=V110&type=BA&year=2019",
"/courses/info/?id=11533&title=Ancient+History+and+Archaeology&code=VF14&type=BA&year=2019",
"/courses/info/?id=11533&title=Ancient+History+and+Archaeology&code=VF14&type=BA&year=2019",
"/courses/info/?id=11525&title=Ancient%2C+Medieval+and+Modern+History&code=V101&type=BA&year=2019",
"/courses/info/?id=11576&title=Anthropology&code=L602&type=BA&year=2019",
"/courses/info/?id=12204&title=Anthropology&code=L601&type=BSC&year=2019",
"/courses/info/?id=11537&title=Anthropology+and+Archaeology&code=LF64&type=BA&year=2019",
"/courses/info/?id=11537&title=Anthropology+and+Archaeology&code=LF64&type=BA&year=2019",
"/courses/info/?id=11540&title=Anthropology+and+Sociology&code=LL36&type=BA&year=2019",
"/courses/info/?id=12207&title=Anthropology+with+Foundation&code=L603&type=BSC&year=2019",
"/courses/info/?id=12355&title=Anthropology+with+Foundation&code=L608&type=BA&year=2019",
"/courses/info/?id=11603&title=Archaeology&code=F400&type=BA&year=2019",
"/courses/info/?id=11607&title=Archaeology&code=F402&type=BSC&year=2019",
"/courses/info/?id=11671&title=Archaeology+and+Ancient+Civilisations&code=VQ48&type=BA&year=2019",
"/courses/info/?id=11671&title=Archaeology+and+Ancient+Civilisations&code=VQ48&type=BA&year=2019",
"/courses/info/?id=11879&title=Archaeology+with+Foundation&code=V400&type=BA&year=2019",
"/courses/info/?id=12302&title=Archaeology+with+Foundation&code=F403&type=BSC&year=2019",
"/courses/info/?id=11725&title=Anthropology+and+Biology&code=CFG0&type=BSC&year=2019",
"/courses/info/?id=11725&title=Anthropology+and+Psychology&code=CFG0&type=BSC&year=2019",
"/courses/info/?id=11816&title=Physics+and+Astronomy&code=FF3N&type=MPHYS&year=2019",
"/courses/info/?id=25474&title=Behavioural+Science&code=C803&type=BSC&year=2019",
"/courses/info/?id=12240&title=Biological+Sciences&code=C103&type=BSC&year=2019",
"/courses/info/?id=12293&title=Biological+Sciences+with+Foundation&code=C104&type=BSC&year=2019",
"/courses/info/?id=12309&title=Biosciences&code=C107&type=MBIOL&year=2019",
"/courses/info/?id=12331&title=Business+and+Management&code=N201&type=BA&year=2019",
"/courses/info/?id=12479&title=Business+and+Management+with+Business+Placement&code=N203&type=BA&year=2019",
"/courses/info/?id=12292&title=Business+and+Management+with+Foundation&code=NN21&type=BA&year=2019",
"/courses/info/?id=12220&title=Business+and+Management+with+Study+Abroad&code=N207&type=BA&year=2019",
"/courses/info/?id=11725&title=Biology+and+Chemistry&code=CFG0&type=BSC&year=2019",
"/courses/info/?id=11725&title=Biology+and+Geography&code=CFG0&type=BSC&year=2019",
"/courses/info/?id=11725&title=Biology+and+Earth+Sciences&code=CFG0&type=BSC&year=2019",
"/courses/info/?id=11725&title=Biology+and+Mathematics&code=CFG0&type=BSC&year=2019",
"/courses/info/?id=11725&title=Biology+and+Physics&code=CFG0&type=BSC&year=2019",
"/courses/info/?id=11725&title=Biology+and+Psychology&code=CFG0&type=BSC&year=2019",
"/courses/info/?id=11725&title=Business+and+Computer+Science&code=CFG0&type=BSC&year=2019",
"/courses/info/?id=11745&title=Biology+and+Chemistry&code=FGC0&type=MSCI&year=2019",
"/courses/info/?id=11745&title=Biology+and+Physics&code=FGC0&type=MSCI&year=2019",
"/courses/info/?id=11598&title=Chemistry&code=F100&type=BSC&year=2019",
"/courses/info/?id=11759&title=Chemistry&code=F105&type=MCHEM&year=2019",
"/courses/info/?id=11714&title=Chemistry+%28Industrial+Route%29&code=F111&type=MCHEM&year=2019",
"/courses/info/?id=11764&title=Chemistry+%28International+Route%29&code=F102&type=MCHEM&year=2019",
"/courses/info/?id=11997&title=Chemistry+with+Foundation&code=F103&type=BSC&year=2019",
"/courses/info/?id=12274&title=Chinese+Studies+%28with+Year+Abroad%29+with+Foundation&code=T103&type=BA&year=2019",
"/courses/info/?id=12259&title=Chinese+Studies+with+Year+Abroad&code=T102&type=BA&year=2019",
"/courses/info/?id=16174&title=Classical+Civilisation&code=Q820&type=BA&year=2019",
"/courses/info/?id=11787&title=Classics&code=Q801&type=BA&year=2019",
"/courses/info/?id=12407&title=Classics+with+Foundation&code=Q805&type=BA&year=2019",
"/courses/info/?id=11627&title=Combined+Honours+in+Social+Sciences&code=LMV0&type=BA&year=2019",
"/courses/info/?id=11995&title=Combined+Honours+in+Social+Sciences+with+Foundation&code=LV00&type=BA&year=2019",
"/courses/info/?id=11508&title=Computer+Science&code=G400&type=BSC&year=2019",
"/courses/info/?id=12412&title=Computer+Science&code=G406&type=MENG&year=2019",
"/courses/info/?id=11886&title=Computer+Science+with+Foundation&code=G402&type=BSC&year=2019",
"/courses/info/?id=11821&title=Criminology&code=L370&type=BA&year=2019",
"/courses/info/?id=11882&title=Criminology+with+Foundation&code=L372&type=BA&year=2019",
"/courses/info/?id=11725&title=Chemistry+and+Earth+Sciences&code=CFG0&type=BSC&year=2019",
"/courses/info/?id=11725&title=Chemistry+and+Physics&code=CFG0&type=BSC&year=2019",
"/courses/info/?id=11725&title=Chemistry+and+Mathematics&code=CFG0&type=BSC&year=2019",
"/courses/info/?id=11725&title=Computer+Science+and+Mathematics&code=CFG0&type=BSC&year=2019",
"/courses/info/?id=11725&title=Computer+Science+and+Physics&code=CFG0&type=BSC&year=2019",
"/courses/info/?id=11745&title=Chemistry+and+Maths&code=FGC0&type=MSCI&year=2019",
"/courses/info/?id=11745&title=Chemistry+and+Physics&code=FGC0&type=MSCI&year=2019",
"/courses/info/?id=12213&title=Earth+Sciences&code=F644&type=MSCI&year=2019",
"/courses/info/?id=11562&title=Economics&code=L100&type=BA&year=2019",
"/courses/info/?id=11740&title=Economics+and+Politics&code=LL12&type=BA&year=2019",
"/courses/info/?id=12487&title=Economics+with+Business+Placement&code=L106&type=BA&year=2019",
"/courses/info/?id=11649&title=Economics+with+Foundation&code=L101&type=BA&year=2019",
"/courses/info/?id=11568&title=Economics+with+French&code=L1R1&type=BA&year=2019",
"/courses/info/?id=12422&title=Economics+with+Management&code=L103&type=BA&year=2019",
"/courses/info/?id=12421&title=Economics+with+Management+with+Business+Placement&code=L104&type=BA&year=2019",
"/courses/info/?id=12413&title=Economics+with+Management+with+Study+Abroad&code=L105&type=BA&year=2019",
"/courses/info/?id=12478&title=Economics+with+Study+Abroad&code=L109&type=BA&year=2019",
"/courses/info/?id=11772&title=Education+Studies+-+English+Studies&code=X1Q3&type=BA&year=2019",
"/courses/info/?id=11772&title=Education+Studies+-+English+Studies&code=X1Q3&type=BA&year=2019",
"/courses/info/?id=11679&title=Education+Studies+-+Geography&code=X1F8&type=BA&year=2019",
"/courses/info/?id=11775&title=Education+Studies+-+History&code=X1V1&type=BA&year=2019",
"/courses/info/?id=11681&title=Education+Studies+-+Music&code=X1W3&type=BA&year=2019",
"/courses/info/?id=11749&title=Education+Studies+-+Philosophy&code=XV35&type=BA&year=2019",
"/courses/info/?id=11780&title=Education+Studies+-+Psychology&code=X1C8&type=BA&year=2019",
"/courses/info/?id=11643&title=Education+Studies+-+Sociology&code=XL33&type=BA&year=2019",
"/courses/info/?id=16337&title=Education+Studies+-+Theology+and+Religion&code=X1V6&type=BA&year=2019",
"/courses/info/?id=12253&title=Education+Studies+with+Foundation&code=X301&type=BA&year=2019",
"/courses/info/?id=11547&title=English+Literature&code=Q300&type=BA&year=2019",
"/courses/info/?id=11515&title=English+Literature+and+History&code=QV21&type=BA&year=2019",
"/courses/info/?id=11622&title=English+Literature+and+Philosophy&code=QV35&type=BA&year=2019",
"/courses/info/?id=12193&title=English+with+Foundation&code=Q301&type=BA&year=2019",
"/courses/info/?id=11614&title=Environmental+Geoscience&code=F630&type=BSC&year=2019",
"/courses/info/?id=11499&title=General+Engineering&code=H103&type=BENG&year=2019",
"/courses/info/?id=11559&title=General+Engineering&code=H100&type=MENG&year=2019",
"/courses/info/?id=11876&title=Engineering+with+Foundation&code=H104&type=BENG&year=2019",
"/courses/info/?id=11725&title=Economics+and+Mathematics&code=CFG0&type=BSC&year=2019",
"/courses/info/?id=11725&title=Economics+and+Psychology&code=CFG0&type=BSC&year=2019",
"/courses/info/?id=11725&title=Earth+Sciences+and+Mathematics&code=CFG0&type=BSC&year=2019",
"/courses/info/?id=12135&title=Primary+Education&code=X101&type=BAE&year=2019",
"/courses/info/?id=11875&title=Primary+Education+with+Foundation&code=X120&type=BA&year=2019",
"/courses/info/?id=12319&title=Finance&code=N305&type=BSC&year=2019",
"/courses/info/?id=12325&title=Finance+with+Business+Placement&code=N306&type=BSC&year=2019",
"/courses/info/?id=12506&title=Finance+with+Foundation&code=N308&type=BSC&year=2019",
"/courses/info/?id=12321&title=Finance+with+Study+Abroad&code=N307&type=BSC&year=2019",
"/courses/info/?id=11679&title=Education+Studies+-+Geography&code=X1F8&type=BA&year=2019",
"/courses/info/?id=11614&title=Environmental+Geoscience&code=F630&type=BSC&year=2019",
"/courses/info/?id=11499&title=General+Engineering&code=H103&type=BENG&year=2019",
"/courses/info/?id=11559&title=General+Engineering&code=H100&type=MENG&year=2019",
"/courses/info/?id=11876&title=General+Engineering+with+Foundation&code=H104&type=BENG&year=2019",
"/courses/info/?id=11619&title=Geography&code=F800&type=BSC&year=2019",
"/courses/info/?id=11624&title=Geography&code=L702&type=BA&year=2019",
"/courses/info/?id=11651&title=Geography+with+Foundation&code=L700&type=BA&year=2019",
"/courses/info/?id=11900&title=Geography+with+Foundation&code=F801&type=BSC&year=2019",
"/courses/info/?id=11610&title=Geology&code=F600&type=BSC&year=2019",
"/courses/info/?id=11872&title=Geology+with+Foundation&code=F602&type=BSC&year=2019",
"/courses/info/?id=11684&title=Geophysics+with+Geology&code=F662&type=BSC&year=2019",
"/courses/info/?id=12211&title=Geoscience&code=F643&type=BSC&year=2019",
"/courses/info/?id=11725&title=Geography+and+Earth+Sciences&code=CFG0&type=BSC&year=2019",
"/courses/info/?id=11725&title=Geography+and+Mathematics&code=CFG0&type=BSC&year=2019",
"/courses/info/?id=11725&title=Geography+and+Psychology&code=CFG0&type=BSC&year=2019",
"/courses/info/?id=11775&title=Education+Studies+-+History&code=X1V1&type=BA&year=2019",
"/courses/info/?id=11515&title=English+Literature+and+History&code=QV21&type=BA&year=2019",
"/courses/info/?id=11586&title=Health+and+Human+Sciences&code=B991&type=BSC&year=2019",
"/courses/info/?id=11861&title=Health+and+Human+Sciences+with+Foundation&code=L691&type=BSC&year=2019",
"/courses/info/?id=11522&title=History&code=V100&type=BA&year=2019",
"/courses/info/?id=12299&title=History+with+Foundation&code=V102&type=BA&year=2019",
"/courses/info/?id=12144&title=International+Relations&code=L250&type=BA&year=2019",
"/courses/info/?id=12279&title=Japanese+Studies+%28with+Year+Abroad%29+with+Foundation&code=T203&type=BA&year=2019",
"/courses/info/?id=12238&title=Japanese+Studies+with+Year+Abroad&code=T202&type=BA&year=2019",
"/courses/info/?id=11731&title=Law&code=M101&type=LLB&year=2019",
"/courses/info/?id=11983&title=Law+with+Foundation&code=M102&type=LLB&year=2019",
"/courses/info/?id=12358&title=Liberal+Arts&code=LA01&type=BA&year=2019",
"/courses/info/?id=12276&title=Liberal+Arts+with+Foundation&code=LA00&type=BA&year=2019",
"/courses/info/?id=12292&title=Management+and+Business+with+Foundation&code=NN21&type=BA&year=2019",
"/courses/info/?id=11681&title=Education+Studies+-+Music&code=X1W3&type=BA&year=2019",
"/courses/info/?id=16655&title=Marketing+and+Management&code=N509&type=BA&year=2019",
"/courses/info/?id=16663&title=Marketing+and+Management+with+Business+Placement&code=N510&type=BA&year=2019",
"/courses/info/?id=16834&title=Marketing+and+Management+with+Foundation&code=N512&type=BA&year=2019",
"/courses/info/?id=16659&title=Marketing+and+Management+with+Study+Abroad&code=N511&type=BA&year=2019",
"/courses/info/?id=11549&title=Mathematics&code=G100&type=BSC&year=2019",
"/courses/info/?id=11554&title=Mathematics&code=G103&type=MMATH&year=2019",
"/courses/info/?id=12298&title=Mathematics+with+Foundation&code=G107&type=BSC&year=2019",
"/courses/info/?id=12441&title=Modern+European+Languages+and+History+with+Year+Abroad&code=RV92&type=BA&year=2019",
"/courses/info/?id=12374&title=Modern+Languages+and+Cultures+with+Year+Abroad&code=R002&type=BA&year=2019",
"/courses/info/?id=11535&title=Music&code=W300&type=BA&year=2019",
"/courses/info/?id=12265&title=Music+and+Philosophy&code=WV53&type=BA&year=2019",
"/courses/info/?id=12405&title=Music+with+Foundation&code=W301&type=BA&year=2019",
"/courses/info/?id=11725&title=Mathematics+and+Philosophy&code=CFG0&type=BSC&year=2019",
"/courses/info/?id=11725&title=Mathematics+and+Physics&code=CFG0&type=BSC&year=2019",
"/courses/info/?id=11725&title=Mathematics+and+Psychology&code=CFG0&type=BSC&year=2019",
"/courses/info/?id=11745&title=Maths+and+Physics&code=FGC0&type=MSCI&year=2019",
"/courses/info/?id=11725&title=Natural+Sciences&code=CFG0&type=BSC&year=2019",
"/courses/info/?id=11745&title=Natural+Sciences&code=FGC0&type=MSCI&year=2019",
"/courses/info/?id=11780&title=Education+Studies+-+Psychology&code=X1C8&type=BA&year=2019",
"/courses/info/?id=11622&title=English+Literature+and+Philosophy&code=QV35&type=BA&year=2019",
"/courses/info/?id=12265&title=Music+and+Philosophy&code=WV53&type=BA&year=2019",
"/courses/info/?id=11725&title=Philosophy+and+Physics&code=CFG0&type=BSC&year=2019",
"/courses/info/?id=11725&title=Psychology+and+Economics&code=CFG0&type=BSC&year=2019",
"/courses/info/?id=11632&title=Philosophy&code=V500&type=BA&year=2019",
"/courses/info/?id=11659&title=Philosophy+and+Politics&code=LV25&type=BA&year=2019",
"/courses/info/?id=11659&title=Philosophy+and+Politics&code=LV25&type=BA&year=2019",
"/courses/info/?id=11663&title=Philosophy+and+Psychology&code=CV85&type=BA&year=2019",
"/courses/info/?id=11663&title=Philosophy+and+Psychology&code=CV85&type=BA&year=2019",
"/courses/info/?id=11734&title=Philosophy+and+Theology&code=VV56&type=BA&year=2019",
"/courses/info/?id=11638&title=Philosophy+with+Foundation&code=V501&type=BA&year=2019",
"/courses/info/?id=11778&title=Philosophy%2C+Politics+and+Economics&code=VL52&type=BA&year=2019",
"/courses/info/?id=11602&title=Physics&code=F300&type=BSC&year=2019",
"/courses/info/?id=11811&title=Physics&code=F301&type=MPHYS&year=2019",
"/courses/info/?id=11816&title=Physics+and+Astronomy&code=FF3N&type=MPHYS&year=2019",
"/courses/info/?id=11987&title=Physics+with+Foundation&code=F302&type=BSC&year=2019",
"/courses/info/?id=11727&title=Politics&code=L200&type=BA&year=2019",
"/courses/info/?id=11894&title=Politics+with+Foundation&code=L201&type=BA&year=2019",
"/courses/info/?id=12448&title=Politics+with+Year+Abroad&code=L202&type=BA&year=2019",
"/courses/info/?id=12135&title=Primary+Education&code=X101&type=BAE&year=2019",
"/courses/info/?id=11875&title=Primary+Education+with+Foundation&code=X120&type=BA&year=2019",
"/courses/info/?id=11593&title=Psychology&code=C800&type=BSC&year=2019",
"/courses/info/?id=16861&title=Psychology+with+Foundation&code=C819&type=BSC&year=2019",
"/courses/info/?id=11814&title=Theoretical+Physics&code=F344&type=MPHYS&year=2019",
"/courses/info/?id=11540&title=Anthropology+and+Sociology&code=LL36&type=BA&year=2019",
"/courses/info/?id=11572&title=Sociology&code=L300&type=BA&year=2019",
"/courses/info/?id=11864&title=Sociology+with+Foundation&code=L301&type=BA&year=2019",
"/courses/info/?id=12286&title=Sport%2C+Exercise+and+Physical+Activity&code=C603&type=BA&year=2019",
"/courses/info/?id=12288&title=Sport%2C+Exercise+and+Physical+Activity+with+Foundation&code=C604&type=BA&year=2019",
"/courses/info/?id=16337&title=Education+Studies+-+Theology+and+Religion&code=X1V6&type=BA&year=2019",
"/courses/info/?id=11734&title=Philosophy+and+Theology&code=VV56&type=BA&year=2019",
"/courses/info/?id=12397&title=Theology+and+Religion&code=V614&type=BA&year=2019",
"/courses/info/?id=16836&title=Theology+and+Religion+Foundation&code=V616&type=BA&year=2019",
"/courses/info/?id=11814&title=Theoretical+Physics&code=F344&type=MPHYS&year=2019", ]
# print(len(lis))
# print(list(set(lis)))
# print(len(list(set(lis))))
























