# -*- coding: utf-8 -*-
import scrapy
import re
from scrapy.spiders import CrawlSpider, Rule
from scrapy.linkextractors import LinkExtractor
from scrapySchool_England_Ben.clearSpace import clear_space, clear_lianxu_space
from scrapySchool_England_Ben.getItem import get_item
from scrapySchool_England_Ben.getTuition_fee import getTuition_fee
from scrapySchool_England_Ben.items import ScrapyschoolEnglandBenItem
import requests
from lxml import etree
from scrapySchool_England_Ben.getIELTS import get_ielts, get_toefl
from scrapySchool_England_Ben.getStartDate import getStartDate
from scrapySchool_England_Ben.remove_tags import remove_class
from scrapySchool_England_Ben.getDuration import getIntDuration


class LoughboroughUniversity_USpider(scrapy.Spider):
    name = "LoughboroughUniversity_U"
    # 研究领域链接
    start_urls = ["http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-artificial-intelligence-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-artificial-intelligence-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-mathematics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/communication-and-media-studies/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-mathematics-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-artificial-intelligence-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-artificial-intelligence-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-mathematics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/civil-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/civil-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/user-centred-design/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computing-and-management-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/textiles-innovation-and-design/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/systems-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/systems-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sports-technology-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/user-centred-design/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computing-and-management-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/textiles-innovation-and-design/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/systems-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/systems-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sports-technology-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/transport-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-coaching-and-physical-education/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/transport-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-coaching-and-physical-education/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/robotics-mechatronics-and-control-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-and-exercise-psychology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sociology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/social-psychology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/robotics-mechatronics-and-control-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/robotics-mechatronics-and-control-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-and-exercise-psychology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sociology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/social-psychology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/robotics-mechatronics-and-control-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-and-exercise-science/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sociology-with-criminology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-and-exercise-science/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sociology-with-criminology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/psychology-with-communication/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/psychology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/product-design-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/product-design-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/psychology-with-communication/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/psychology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/product-design-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/product-design-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/retailing-marketing-and-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/psychology-with-criminology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/product-design-and-technology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-history-and-international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/psychology-with-criminology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/product-design-and-technology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-history-and-international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-and-international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-with-theoretical-physics-mphys/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-with-theoretical-physics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-with-international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-mphys/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-with-history/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-with-economics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-and-international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-with-theoretical-physics-mphys/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-with-theoretical-physics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-with-international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-mphys/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-with-history/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-with-economics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/natural-sciences-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/natural-sciences-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/medicinal-and-pharmaceutical-chemistry-mchem/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mechanical-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/medicinal-and-pharmaceutical-chemistry-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mechanical-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-with-statistics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/natural-sciences-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/natural-sciences-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/medicinal-and-pharmaceutical-chemistry-mchem/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mechanical-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/medicinal-and-pharmaceutical-chemistry-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mechanical-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-with-statistics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-with-economics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-with-economics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-and-sport-science/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-and-physics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-and-physics-mphys/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-accounting-and-financial-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/materials-science-and-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-and-sport-science/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-and-physics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-and-physics-mphys/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-accounting-and-financial-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/materials-science-and-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/manufacturing-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/manufacturing-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/management-sciences/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/information-technology-management-for-business/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/information-technology-management-for-business-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/manufacturing-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/manufacturing-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/information-technology-management-for-business/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/information-technology-management-for-business-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/materials-science-and-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/international-business/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/materials-science-and-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/history-and-international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/information-management-and-business/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/industrial-design-and-technology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/human-biology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/graphic-communication-and-illustration/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-with-economics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/history/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/history-and-politics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/history-and-international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/information-management-and-business/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/industrial-design-and-technology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/human-biology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/graphic-communication-and-illustration/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-with-economics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/history/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/history-and-politics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/finance-and-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-with-digital-humanities/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-with-digital-humanities/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-ba/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-and-sport-science/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/fine-art/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-and-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/financial-mathematics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-ba/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-and-sport-science/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/fine-art/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-and-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/financial-mathematics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-and-sport-science/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/engineering-physics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-with-creative-writing/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-with-business-studies/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-and-sport-science/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/engineering-physics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-with-creative-writing/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-with-business-studies/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-literature/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-and-drama/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/engineering-physics-mphys/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-literature/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-and-drama/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/engineering-physics-mphys/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/engineering-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-electrical-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/engineering-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/economics-and-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-electrical-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-electrical-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/economics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/drama-with-english/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-computer-systems-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-computer-systems-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/economics-and-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-electrical-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/economics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/drama-with-english/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-computer-systems-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-computer-systems-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/civil-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemistry-mchem/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/civil-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemistry-mchem/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemistry-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemical-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemical-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/business-psychology-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/business-economics-and-finance-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biomaterials-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemistry-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemical-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemical-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/business-psychology-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/business-economics-and-finance-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biomaterials-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biological-sciences-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biomaterials-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/bioengineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/bioengineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biological-sciences-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biological-sciences-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biomaterials-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/bioengineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/bioengineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biological-sciences-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biochemistry-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biochemistry-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-materials-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biochemistry-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biochemistry-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-materials-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-materials-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/architecture-barch/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/air-transport-management-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/architectural-engineering-and-design-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-materials-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/air-transport-management-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/architectural-engineering-and-design-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/aeronautical-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/aeronautical-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/aeronautical-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/aeronautical-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/accounting-and-financial-management-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/construction-engineering-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computing-and-management-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/criminology-and-social-policy/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/drama/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computing-and-management-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/drama-with-business-studies/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/criminology-and-social-policy/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/drama/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/drama-with-business-studies/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/communication-and-media-studies/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-mathematics-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/commercial-management-and-quantity-surveying/", ]
    # print(len(start_urls))
    start_urls = list(set(start_urls))
    # print(len(start_urls))

    def parse(self, response):
        links = ["http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-artificial-intelligence-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-artificial-intelligence-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-mathematics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/communication-and-media-studies/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-mathematics-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-artificial-intelligence-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-artificial-intelligence-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-mathematics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/civil-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/civil-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/user-centred-design/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computing-and-management-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/textiles-innovation-and-design/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/systems-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/systems-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sports-technology-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/user-centred-design/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computing-and-management-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/textiles-innovation-and-design/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/systems-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/systems-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sports-technology-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/transport-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-coaching-and-physical-education/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/transport-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-coaching-and-physical-education/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/robotics-mechatronics-and-control-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-and-exercise-psychology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sociology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/social-psychology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/robotics-mechatronics-and-control-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/robotics-mechatronics-and-control-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-and-exercise-psychology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sociology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/social-psychology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/robotics-mechatronics-and-control-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-and-exercise-science/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sociology-with-criminology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-and-exercise-science/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sociology-with-criminology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/psychology-with-communication/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/psychology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/product-design-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/product-design-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/psychology-with-communication/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/psychology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/product-design-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/product-design-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/retailing-marketing-and-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/psychology-with-criminology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/product-design-and-technology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-history-and-international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/psychology-with-criminology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/product-design-and-technology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-history-and-international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-and-international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-with-theoretical-physics-mphys/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-with-theoretical-physics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-with-international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-mphys/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-with-history/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-with-economics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-and-international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-with-theoretical-physics-mphys/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-with-theoretical-physics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-with-international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-mphys/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-with-history/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-with-economics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/natural-sciences-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/natural-sciences-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/medicinal-and-pharmaceutical-chemistry-mchem/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mechanical-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/medicinal-and-pharmaceutical-chemistry-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mechanical-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-with-statistics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/natural-sciences-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/natural-sciences-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/medicinal-and-pharmaceutical-chemistry-mchem/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mechanical-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/medicinal-and-pharmaceutical-chemistry-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mechanical-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-with-statistics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-with-economics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-with-economics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-and-sport-science/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-and-physics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-and-physics-mphys/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-accounting-and-financial-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/materials-science-and-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-and-sport-science/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-and-physics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-and-physics-mphys/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-accounting-and-financial-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/materials-science-and-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/manufacturing-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/manufacturing-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/management-sciences/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/information-technology-management-for-business/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/information-technology-management-for-business-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/manufacturing-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/manufacturing-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/information-technology-management-for-business/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/information-technology-management-for-business-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/materials-science-and-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/international-business/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/materials-science-and-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/history-and-international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/information-management-and-business/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/industrial-design-and-technology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/human-biology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/graphic-communication-and-illustration/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-with-economics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/history/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/history-and-politics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/history-and-international-relations/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/information-management-and-business/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/industrial-design-and-technology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/human-biology/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/graphic-communication-and-illustration/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-with-economics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/history/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/history-and-politics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/finance-and-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-with-digital-humanities/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-with-digital-humanities/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-ba/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-and-sport-science/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/fine-art/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-and-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/financial-mathematics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-ba/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-and-sport-science/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/fine-art/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-and-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/financial-mathematics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-and-sport-science/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/engineering-physics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-with-creative-writing/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-with-business-studies/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-and-sport-science/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/engineering-physics-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-with-creative-writing/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-with-business-studies/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-literature/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-and-drama/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/engineering-physics-mphys/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-literature/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-and-drama/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/engineering-physics-mphys/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/engineering-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-electrical-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/engineering-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/economics-and-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-electrical-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-electrical-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/economics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/drama-with-english/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-computer-systems-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-computer-systems-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/economics-and-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-electrical-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/economics/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/drama-with-english/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-computer-systems-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-computer-systems-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/civil-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemistry-mchem/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/civil-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemistry-mchem/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemistry-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemical-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemical-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/business-psychology-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/business-economics-and-finance-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biomaterials-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemistry-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemical-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemical-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/business-psychology-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/business-economics-and-finance-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biomaterials-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biological-sciences-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biomaterials-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/bioengineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/bioengineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biological-sciences-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biological-sciences-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biomaterials-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/bioengineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/bioengineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biological-sciences-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biochemistry-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biochemistry-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-materials-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biochemistry-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biochemistry-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-materials-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-materials-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/architecture-barch/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/air-transport-management-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/architectural-engineering-and-design-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-materials-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/air-transport-management-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/architectural-engineering-and-design-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/aeronautical-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/aeronautical-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/aeronautical-engineering-meng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/aeronautical-engineering-beng/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/accounting-and-financial-management-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/construction-engineering-management/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computing-and-management-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/criminology-and-social-policy/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/drama/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computing-and-management-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/drama-with-business-studies/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/criminology-and-social-policy/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/drama/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/drama-with-business-studies/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-bsc/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/communication-and-media-studies/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-mathematics-msci/",
"http://www.lboro.ac.uk/study/undergraduate/courses/a-z/commercial-management-and-quantity-surveying/", ]
        # urls = {
        #     1436: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/accounting-and-financial-management-bsc/",
        #     1432: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/aeronautical-engineering-beng/",
        #     1435: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/aeronautical-engineering-beng/",
        #     1431: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/aeronautical-engineering-meng/",
        #     1434: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/aeronautical-engineering-meng/",
        #     1424: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/air-transport-management-bsc/",
        #     1428: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/air-transport-management-bsc/",
        #     1425: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/architectural-engineering-and-design-management/",
        #     1429: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/architectural-engineering-and-design-management/",
        #     1423: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/architecture-barch/",
        #     1430: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-engineering-beng/",
        #     1433: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-engineering-beng/",
        #     1422: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-engineering-meng/",
        #     1427: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-engineering-meng/",
        #     1421: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-materials-beng/",
        #     1426: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-materials-beng/",
        #     1417: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-materials-meng/",
        #     1420: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-materials-meng/",
        #     1416: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biochemistry-bsc/",
        #     1419: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biochemistry-bsc/",
        #     1415: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biochemistry-msci/",
        #     1418: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biochemistry-msci/",
        #     1408: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/bioengineering-beng/",
        #     1413: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/bioengineering-beng/",
        #     1407: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/bioengineering-meng/",
        #     1412: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/bioengineering-meng/",
        #     1405: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biological-sciences-bsc/",
        #     1410: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biological-sciences-bsc/",
        #     1409: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biological-sciences-msci/",
        #     1414: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biological-sciences-msci/",
        #     1406: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biomaterials-engineering-beng/",
        #     1411: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biomaterials-engineering-beng/",
        #     1398: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biomaterials-engineering-meng/",
        #     1404: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biomaterials-engineering-meng/",
        #     1397: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/business-economics-and-finance-bsc/",
        #     1403: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/business-economics-and-finance-bsc/",
        #     1396: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/business-psychology-bsc/",
        #     1402: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/business-psychology-bsc/",
        #     1395: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemical-engineering-beng/",
        #     1401: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemical-engineering-beng/",
        #     1394: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemical-engineering-meng/",
        #     1400: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemical-engineering-meng/",
        #     1393: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemistry-bsc/",
        #     1399: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemistry-bsc/",
        #     1390: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemistry-mchem/",
        #     1392: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemistry-mchem/",
        #     1389: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/civil-engineering-beng/",
        #     1391: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/civil-engineering-beng/",
        #     1215: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/civil-engineering-meng/",
        #     1216: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/civil-engineering-meng/",
        #     1452: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/commercial-management-and-quantity-surveying/",
        #     1450: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/communication-and-media-studies/",
        #     1210: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/communication-and-media-studies/",
        #     1207: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-artificial-intelligence-bsc/",
        #     1212: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-artificial-intelligence-bsc/",
        #     1208: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-artificial-intelligence-msci/",
        #     1213: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-artificial-intelligence-msci/",
        #     1209: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-mathematics-bsc/",
        #     1214: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-mathematics-bsc/",
        #     1451: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-mathematics-msci/",
        #     1211: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-mathematics-msci/",
        #     1447: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-bsc/",
        #     1449: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-bsc/",
        #     1438: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-msci/",
        #     1442: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-msci/",
        #     1218: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computing-and-management-bsc/",
        #     1224: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computing-and-management-bsc/",
        #     1439: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computing-and-management-msci/",
        #     1443: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computing-and-management-msci/",
        #     1437: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/construction-engineering-management/",
        #     1440: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/criminology-and-social-policy/",
        #     1445: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/criminology-and-social-policy/",
        #     1444: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/drama-with-business-studies/",
        #     1448: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/drama-with-business-studies/",
        #     1380: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/drama-with-english/",
        #     1386: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/drama-with-english/",
        #     1441: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/drama/",
        #     1446: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/drama/",
        #     1376: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/economics-and-management/",
        #     1383: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/economics-and-management/",
        #     1379: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/economics/",
        #     1385: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/economics/",
        #     1382: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-computer-systems-engineering-beng/",
        #     1388: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-computer-systems-engineering-beng/",
        #     1381: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-computer-systems-engineering-meng/",
        #     1387: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-computer-systems-engineering-meng/",
        #     1374: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-electrical-engineering-beng/",
        #     1377: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-electrical-engineering-beng/",
        #     1378: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-electrical-engineering-meng/",
        #     1384: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-electrical-engineering-meng/",
        #     1373: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/engineering-management/",
        #     1375: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/engineering-management/",
        #     1359: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/engineering-physics-bsc/",
        #     1364: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/engineering-physics-bsc/",
        #     1369: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/engineering-physics-mphys/",
        #     1372: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/engineering-physics-mphys/",
        #     1368: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-and-drama/",
        #     1371: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-and-drama/",
        #     1358: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-and-sport-science/",
        #     1363: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-and-sport-science/",
        #     1367: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-literature/",
        #     1370: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-literature/",
        #     1361: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-with-business-studies/",
        #     1366: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-with-business-studies/",
        #     1360: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-with-creative-writing/",
        #     1365: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-with-creative-writing/",
        #     1343: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-with-digital-humanities/",
        #     1344: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-with-digital-humanities/",
        #     1357: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english/",
        #     1362: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english/",
        #     1342: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/finance-and-management/",
        #     1350: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/financial-mathematics/",
        #     1356: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/financial-mathematics/",
        #     1348: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/fine-art/",
        #     1354: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/fine-art/",
        #     1349: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-and-management/",
        #     1355: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-and-management/",
        #     1347: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-and-sport-science/",
        #     1353: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-and-sport-science/",
        #     1346: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-ba/",
        #     1352: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-ba/",
        #     1345: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-bsc/",
        #     1351: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-bsc/",
        #     1331: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-with-economics/",
        #     1339: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-with-economics/",
        #     1330: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/graphic-communication-and-illustration/",
        #     1338: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/graphic-communication-and-illustration/",
        #     1326: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/history-and-international-relations/",
        #     1334: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/history-and-international-relations/",
        #     1333: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/history-and-politics/",
        #     1341: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/history-and-politics/",
        #     1332: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/history/",
        #     1340: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/history/",
        #     1329: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/human-biology/",
        #     1337: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/human-biology/",
        #     1328: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/industrial-design-and-technology/",
        #     1336: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/industrial-design-and-technology/",
        #     1327: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/information-management-and-business/",
        #     1335: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/information-management-and-business/",
        #     1316: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/information-technology-management-for-business-bsc/",
        #     1320: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/information-technology-management-for-business-bsc/",
        #     1315: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/information-technology-management-for-business/",
        #     1319: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/information-technology-management-for-business/",
        #     1323: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/international-business/",
        #     1322: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/international-relations/",
        #     1325: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/international-relations/",
        #     1314: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/management-sciences/",
        #     1313: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/manufacturing-engineering-beng/",
        #     1318: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/manufacturing-engineering-beng/",
        #     1312: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/manufacturing-engineering-meng/",
        #     1317: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/manufacturing-engineering-meng/",
        #     1321: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/materials-science-and-engineering-beng/",
        #     1324: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/materials-science-and-engineering-beng/",
        #     1304: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/materials-science-and-engineering-meng/",
        #     1311: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/materials-science-and-engineering-meng/",
        #     1303: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-accounting-and-financial-management/",
        #     1310: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-accounting-and-financial-management/",
        #     1301: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-and-physics-bsc/",
        #     1308: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-and-physics-bsc/",
        #     1302: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-and-physics-mphys/",
        #     1309: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-and-physics-mphys/",
        #     1300: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-and-sport-science/",
        #     1307: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-and-sport-science/",
        #     1299: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-bsc/",
        #     1306: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-bsc/",
        #     1296: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-with-economics/",
        #     1297: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-with-economics/",
        #     1288: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-with-statistics/",
        #     1295: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-with-statistics/",
        #     1298: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics/",
        #     1305: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics/",
        #     1287: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mechanical-engineering-beng/",
        #     1294: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mechanical-engineering-beng/",
        #     1285: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mechanical-engineering-meng/",
        #     1292: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mechanical-engineering-meng/",
        #     1286: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/medicinal-and-pharmaceutical-chemistry-bsc/",
        #     1293: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/medicinal-and-pharmaceutical-chemistry-bsc/",
        #     1284: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/medicinal-and-pharmaceutical-chemistry-mchem/",
        #     1291: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/medicinal-and-pharmaceutical-chemistry-mchem/",
        #     1283: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/natural-sciences-bsc/",
        #     1290: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/natural-sciences-bsc/",
        #     1282: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/natural-sciences-msci/",
        #     1289: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/natural-sciences-msci/",
        #     1280: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-bsc/",
        #     1281: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-bsc/",
        #     1268: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-mphys/",
        #     1276: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-mphys/",
        #     1266: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-with-theoretical-physics-bsc/",
        #     1274: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-with-theoretical-physics-bsc/",
        #     1265: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-with-theoretical-physics-mphys/",
        #     1273: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-with-theoretical-physics-mphys/",
        #     1264: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-and-international-relations/",
        #     1272: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-and-international-relations/",
        #     1260: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-history-and-international-relations/",
        #     1263: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-history-and-international-relations/",
        #     1270: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-with-economics/",
        #     1278: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-with-economics/",
        #     1269: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-with-history/",
        #     1277: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-with-history/",
        #     1267: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-with-international-relations/",
        #     1275: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-with-international-relations/",
        #     1271: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics/",
        #     1279: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics/",
        #     1259: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/product-design-and-technology/",
        #     1262: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/product-design-and-technology/",
        #     1251: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/product-design-engineering-beng/",
        #     1255: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/product-design-engineering-beng/",
        #     1252: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/product-design-engineering-meng/",
        #     1256: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/product-design-engineering-meng/",
        #     1249: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/psychology-with-communication/",
        #     1253: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/psychology-with-communication/",
        #     1258: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/psychology-with-criminology/",
        #     1261: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/psychology-with-criminology/",
        #     1250: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/psychology/",
        #     1254: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/psychology/",
        #     1257: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/retailing-marketing-and-management/",
        #     1234: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/robotics-mechatronics-and-control-engineering-beng/",
        #     1240: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/robotics-mechatronics-and-control-engineering-beng/",
        #     1238: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/robotics-mechatronics-and-control-engineering-meng/",
        #     1244: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/robotics-mechatronics-and-control-engineering-meng/",
        #     1237: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/social-psychology/",
        #     1243: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/social-psychology/",
        #     1246: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sociology-with-criminology/",
        #     1248: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sociology-with-criminology/",
        #     1236: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sociology/",
        #     1242: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sociology/",
        #     1235: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-and-exercise-psychology/",
        #     1241: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-and-exercise-psychology/",
        #     1245: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-and-exercise-science/",
        #     1247: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-and-exercise-science/",
        #     1230: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-coaching-and-physical-education/",
        #     1232: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-coaching-and-physical-education/",
        #     1233: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-management/",
        #     1239: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-management/",
        #     1222: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sports-technology-beng/",
        #     1228: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sports-technology-beng/",
        #     1221: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/systems-engineering-beng/",
        #     1227: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/systems-engineering-beng/",
        #     1220: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/systems-engineering-meng/",
        #     1226: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/systems-engineering-meng/",
        #     1219: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/textiles-innovation-and-design/",
        #     1225: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/textiles-innovation-and-design/",
        #     1229: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/transport-management/",
        #     1231: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/transport-management/",
        #     1217: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/user-centred-design/",
        #     1223: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/user-centred-design/"
        # }
        # keys = urls.keys()
        # for key in keys:
        #     # print(key)
        #     # print(urls[key])
        for url in links:
            yield scrapy.Request(url, callback=self.parse_data, meta={'url': url})

    def parse_data(self, response):
        item = get_item(ScrapyschoolEnglandBenItem)
        item['university'] = "Loughborough University"
        # item['country'] = 'England'
        # item['website'] = 'http://www.lboro.ac.uk/'
        item['url'] = response.meta['url']
        # 学位类型
        item['degree_type'] = 1
        print("===========================")
        print(response.url)
        print(response.meta['url'])

        urls = {
            1436: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/accounting-and-financial-management-bsc/",
            1432: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/aeronautical-engineering-beng/",
            1435: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/aeronautical-engineering-beng/",
            1431: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/aeronautical-engineering-meng/",
            1434: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/aeronautical-engineering-meng/",
            1424: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/air-transport-management-bsc/",
            1428: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/air-transport-management-bsc/",
            1425: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/architectural-engineering-and-design-management/",
            1429: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/architectural-engineering-and-design-management/",
            1423: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/architecture-barch/",
            1430: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-engineering-beng/",
            1433: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-engineering-beng/",
            1422: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-engineering-meng/",
            1427: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-engineering-meng/",
            1421: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-materials-beng/",
            1426: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-materials-beng/",
            1417: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-materials-meng/",
            1420: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/automotive-materials-meng/",
            1416: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biochemistry-bsc/",
            1419: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biochemistry-bsc/",
            1415: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biochemistry-msci/",
            1418: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biochemistry-msci/",
            1408: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/bioengineering-beng/",
            1413: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/bioengineering-beng/",
            1407: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/bioengineering-meng/",
            1412: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/bioengineering-meng/",
            1405: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biological-sciences-bsc/",
            1410: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biological-sciences-bsc/",
            1409: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biological-sciences-msci/",
            1414: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biological-sciences-msci/",
            1406: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biomaterials-engineering-beng/",
            1411: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biomaterials-engineering-beng/",
            1398: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biomaterials-engineering-meng/",
            1404: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/biomaterials-engineering-meng/",
            1397: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/business-economics-and-finance-bsc/",
            1403: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/business-economics-and-finance-bsc/",
            1396: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/business-psychology-bsc/",
            1402: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/business-psychology-bsc/",
            1395: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemical-engineering-beng/",
            1401: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemical-engineering-beng/",
            1394: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemical-engineering-meng/",
            1400: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemical-engineering-meng/",
            1393: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemistry-bsc/",
            1399: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemistry-bsc/",
            1390: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemistry-mchem/",
            1392: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/chemistry-mchem/",
            1389: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/civil-engineering-beng/",
            1391: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/civil-engineering-beng/",
            1215: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/civil-engineering-meng/",
            1216: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/civil-engineering-meng/",
            1452: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/commercial-management-and-quantity-surveying/",
            1450: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/communication-and-media-studies/",
            1210: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/communication-and-media-studies/",
            1207: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-artificial-intelligence-bsc/",
            1212: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-artificial-intelligence-bsc/",
            1208: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-artificial-intelligence-msci/",
            1213: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-artificial-intelligence-msci/",
            1209: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-mathematics-bsc/",
            1214: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-mathematics-bsc/",
            1451: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-mathematics-msci/",
            1211: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-and-mathematics-msci/",
            1447: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-bsc/",
            1449: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-bsc/",
            1438: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-msci/",
            1442: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computer-science-msci/",
            1218: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computing-and-management-bsc/",
            1224: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computing-and-management-bsc/",
            1439: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computing-and-management-msci/",
            1443: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/computing-and-management-msci/",
            1437: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/construction-engineering-management/",
            1440: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/criminology-and-social-policy/",
            1445: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/criminology-and-social-policy/",
            1444: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/drama-with-business-studies/",
            1448: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/drama-with-business-studies/",
            1380: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/drama-with-english/",
            1386: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/drama-with-english/",
            1441: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/drama/",
            1446: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/drama/",
            1376: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/economics-and-management/",
            1383: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/economics-and-management/",
            1379: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/economics/",
            1385: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/economics/",
            1382: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-computer-systems-engineering-beng/",
            1388: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-computer-systems-engineering-beng/",
            1381: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-computer-systems-engineering-meng/",
            1387: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-computer-systems-engineering-meng/",
            1374: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-electrical-engineering-beng/",
            1377: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-electrical-engineering-beng/",
            1378: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-electrical-engineering-meng/",
            1384: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/electronic-and-electrical-engineering-meng/",
            1373: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/engineering-management/",
            1375: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/engineering-management/",
            1359: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/engineering-physics-bsc/",
            1364: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/engineering-physics-bsc/",
            1369: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/engineering-physics-mphys/",
            1372: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/engineering-physics-mphys/",
            1368: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-and-drama/",
            1371: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-and-drama/",
            1358: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-and-sport-science/",
            1363: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-and-sport-science/",
            1367: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-literature/",
            1370: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-literature/",
            1361: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-with-business-studies/",
            1366: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-with-business-studies/",
            1360: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-with-creative-writing/",
            1365: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-with-creative-writing/",
            1343: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-with-digital-humanities/",
            1344: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english-with-digital-humanities/",
            1357: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english/",
            1362: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/english/",
            1342: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/finance-and-management/",
            1350: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/financial-mathematics/",
            1356: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/financial-mathematics/",
            1348: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/fine-art/",
            1354: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/fine-art/",
            1349: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-and-management/",
            1355: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-and-management/",
            1347: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-and-sport-science/",
            1353: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-and-sport-science/",
            1346: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-ba/",
            1352: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-ba/",
            1345: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-bsc/",
            1351: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-bsc/",
            1331: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-with-economics/",
            1339: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/geography-with-economics/",
            1330: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/graphic-communication-and-illustration/",
            1338: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/graphic-communication-and-illustration/",
            1326: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/history-and-international-relations/",
            1334: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/history-and-international-relations/",
            1333: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/history-and-politics/",
            1341: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/history-and-politics/",
            1332: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/history/",
            1340: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/history/",
            1329: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/human-biology/",
            1337: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/human-biology/",
            1328: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/industrial-design-and-technology/",
            1336: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/industrial-design-and-technology/",
            1327: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/information-management-and-business/",
            1335: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/information-management-and-business/",
            1316: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/information-technology-management-for-business-bsc/",
            1320: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/information-technology-management-for-business-bsc/",
            1315: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/information-technology-management-for-business/",
            1319: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/information-technology-management-for-business/",
            1323: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/international-business/",
            1322: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/international-relations/",
            1325: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/international-relations/",
            1314: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/management-sciences/",
            1313: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/manufacturing-engineering-beng/",
            1318: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/manufacturing-engineering-beng/",
            1312: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/manufacturing-engineering-meng/",
            1317: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/manufacturing-engineering-meng/",
            1321: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/materials-science-and-engineering-beng/",
            1324: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/materials-science-and-engineering-beng/",
            1304: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/materials-science-and-engineering-meng/",
            1311: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/materials-science-and-engineering-meng/",
            1303: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-accounting-and-financial-management/",
            1310: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-accounting-and-financial-management/",
            1301: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-and-physics-bsc/",
            1308: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-and-physics-bsc/",
            1302: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-and-physics-mphys/",
            1309: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-and-physics-mphys/",
            1300: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-and-sport-science/",
            1307: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-and-sport-science/",
            1299: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-bsc/",
            1306: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-bsc/",
            1296: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-with-economics/",
            1297: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-with-economics/",
            1288: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-with-statistics/",
            1295: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics-with-statistics/",
            1298: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics/",
            1305: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mathematics/",
            1287: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mechanical-engineering-beng/",
            1294: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mechanical-engineering-beng/",
            1285: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mechanical-engineering-meng/",
            1292: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/mechanical-engineering-meng/",
            1286: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/medicinal-and-pharmaceutical-chemistry-bsc/",
            1293: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/medicinal-and-pharmaceutical-chemistry-bsc/",
            1284: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/medicinal-and-pharmaceutical-chemistry-mchem/",
            1291: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/medicinal-and-pharmaceutical-chemistry-mchem/",
            1283: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/natural-sciences-bsc/",
            1290: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/natural-sciences-bsc/",
            1282: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/natural-sciences-msci/",
            1289: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/natural-sciences-msci/",
            1280: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-bsc/",
            1281: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-bsc/",
            1268: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-mphys/",
            1276: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-mphys/",
            1266: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-with-theoretical-physics-bsc/",
            1274: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-with-theoretical-physics-bsc/",
            1265: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-with-theoretical-physics-mphys/",
            1273: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/physics-with-theoretical-physics-mphys/",
            1264: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-and-international-relations/",
            1272: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-and-international-relations/",
            1260: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-history-and-international-relations/",
            1263: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-history-and-international-relations/",
            1270: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-with-economics/",
            1278: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-with-economics/",
            1269: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-with-history/",
            1277: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-with-history/",
            1267: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-with-international-relations/",
            1275: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics-with-international-relations/",
            1271: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics/",
            1279: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/politics/",
            1259: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/product-design-and-technology/",
            1262: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/product-design-and-technology/",
            1251: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/product-design-engineering-beng/",
            1255: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/product-design-engineering-beng/",
            1252: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/product-design-engineering-meng/",
            1256: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/product-design-engineering-meng/",
            1249: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/psychology-with-communication/",
            1253: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/psychology-with-communication/",
            1258: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/psychology-with-criminology/",
            1261: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/psychology-with-criminology/",
            1250: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/psychology/",
            1254: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/psychology/",
            1257: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/retailing-marketing-and-management/",
            1234: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/robotics-mechatronics-and-control-engineering-beng/",
            1240: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/robotics-mechatronics-and-control-engineering-beng/",
            1238: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/robotics-mechatronics-and-control-engineering-meng/",
            1244: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/robotics-mechatronics-and-control-engineering-meng/",
            1237: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/social-psychology/",
            1243: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/social-psychology/",
            1246: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sociology-with-criminology/",
            1248: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sociology-with-criminology/",
            1236: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sociology/",
            1242: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sociology/",
            1235: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-and-exercise-psychology/",
            1241: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-and-exercise-psychology/",
            1245: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-and-exercise-science/",
            1247: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-and-exercise-science/",
            1230: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-coaching-and-physical-education/",
            1232: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-coaching-and-physical-education/",
            1233: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-management/",
            1239: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sport-management/",
            1222: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sports-technology-beng/",
            1228: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/sports-technology-beng/",
            1221: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/systems-engineering-beng/",
            1227: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/systems-engineering-beng/",
            1220: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/systems-engineering-meng/",
            1226: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/systems-engineering-meng/",
            1219: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/textiles-innovation-and-design/",
            1225: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/textiles-innovation-and-design/",
            1229: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/transport-management/",
            1231: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/transport-management/",
            1217: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/user-centred-design/",
            1223: "http://www.lboro.ac.uk/study/undergraduate/courses/a-z/user-centred-design/"
        }
        keys = urls.keys()
        tmp_keys = []
        for key in keys:
            # print(key)
            # print(urls[key])
            if response.meta['url'] == urls[key]:
                tmp_keys.append(key)
        print("tmp_keys: ", tmp_keys)


        try:
            # 学位名称
            # degree_name = response.xpath(
            #     "//span[@class='course-info__qualification course-info__qualification--default active']//text()").extract()
            # # print("degree_name: ", degree_name)
            # item['degree_name'] = ''.join(degree_name).replace(', PG certificate', '').strip()
            # print("item['degree_name']: ", item['degree_name'])
            #
            # # 专业
            # programme_en = response.xpath(
            #     "//h1[@class='course-info__heading']/text()").extract()
            # clear_space(programme_en)
            # item['programme_en'] = ''.join(programme_en).strip()
            # print("item['programme_en']: ", item['programme_en'])


            alevel = response.xpath(
                "//dt[@class='list__item list__item--term'][contains(text(),'A-Level')]/following-sibling::dd//text()").extract()
            # alevel = response.xpath(
            #     "//span[@class='list__text'][contains(text(),'Typical offer')]/../following-sibling::dd//text()").extract()
            clear_space(alevel)
            if len(alevel) > 0:
                item['alevel'] = ''.join(alevel[0]).strip()
            print("item['alevel'] = ", item['alevel'])

            ib = response.xpath(
                "//dt[@class='list__item list__item--term'][contains(text(),'IB')]/following-sibling::dd//text()").extract()
            item['ib'] = ''.join(ib).strip()
            print("item['ib'] = ", item['ib'])

            yield item
        except Exception as e:
            with open("scrapySchool_England_Ben/error/"+item['university']+str(item['degree_type'])+".txt", 'a', encoding="utf-8") as f:
                f.write(str(e) + "\n" + response.url + "\n========================\n")
            print("异常：", str(e))
            print("报错url：", response.url)