# -*- coding: utf-8 -*-
import scrapy
import re
from scrapySchool_England_Ben.clearSpace import clear_space, clear_lianxu_space
from scrapySchool_England_Ben.getItem import get_item
from scrapySchool_England_Ben.getTuition_fee import getTuition_fee
from scrapySchool_England_Ben.items import ScrapyschoolEnglandBenItem
from scrapySchool_England_Ben.getIELTS import get_ielts, get_toefl
from scrapySchool_England_Ben.getStartDate import getStartDate
from scrapySchool_England_Ben.remove_tags import remove_class
from scrapySchool_England_Ben.getDuration import getIntDuration
import requests
from w3lib.html import remove_tags
import json

class NewcastleUniversity_USpider(scrapy.Spider):
    name = "NewcastleUniversity_U"
    start_urls = ["https://www.ncl.ac.uk/undergraduate/degrees/#a-z"]


    def parse(self, response):
        links = ["https://www.ncl.ac.uk/undergraduate/degrees/n402/",
"https://www.ncl.ac.uk/undergraduate/degrees/n402/",
"https://www.ncl.ac.uk/undergraduate/degrees/n400/",
"https://www.ncl.ac.uk/undergraduate/degrees/n400/",
"https://www.ncl.ac.uk/undergraduate/degrees/n280/",
"https://www.ncl.ac.uk/undergraduate/degrees/d400/",
"https://www.ncl.ac.uk/undergraduate/degrees/d444/",
"https://www.ncl.ac.uk/undergraduate/degrees/d422/",
"https://www.ncl.ac.uk/undergraduate/degrees/d402/",
"https://www.ncl.ac.uk/undergraduate/degrees/v110/",
"https://www.ncl.ac.uk/undergraduate/degrees/vv14/",
"https://www.ncl.ac.uk/undergraduate/degrees/c305/",
"https://www.ncl.ac.uk/undergraduate/degrees/c211/",
"https://www.ncl.ac.uk/undergraduate/degrees/v400/",
"https://www.ncl.ac.uk/undergraduate/degrees/k100/",
"https://www.ncl.ac.uk/undergraduate/degrees/k190/",
"https://www.ncl.ac.uk/undergraduate/degrees/h660/",
"https://www.ncl.ac.uk/undergraduate/degrees/h661/",
"https://www.ncl.ac.uk/undergraduate/degrees/c700/",
"https://www.ncl.ac.uk/undergraduate/degrees/c701/",
"https://www.ncl.ac.uk/undergraduate/degrees/c100/",
"https://www.ncl.ac.uk/undergraduate/degrees/c103/",
"https://www.ncl.ac.uk/undergraduate/degrees/c1c7/",
"https://www.ncl.ac.uk/undergraduate/degrees/c7c1/",
"https://www.ncl.ac.uk/undergraduate/degrees/c182/",
"https://www.ncl.ac.uk/undergraduate/degrees/c183/",
"https://www.ncl.ac.uk/undergraduate/degrees/b901/",
"https://www.ncl.ac.uk/undergraduate/degrees/b903/",
"https://www.ncl.ac.uk/undergraduate/degrees/b940/",
"https://www.ncl.ac.uk/undergraduate/degrees/b900/",
"https://www.ncl.ac.uk/undergraduate/degrees/nn14/",
"https://www.ncl.ac.uk/undergraduate/degrees/n200/",
"https://www.ncl.ac.uk/undergraduate/degrees/h810/",
"https://www.ncl.ac.uk/undergraduate/degrees/h813/",
"https://www.ncl.ac.uk/undergraduate/degrees/h831/",
"https://www.ncl.ac.uk/undergraduate/degrees/h814/",
"https://www.ncl.ac.uk/undergraduate/degrees/h816/",
"https://www.ncl.ac.uk/undergraduate/degrees/h815/",
"https://www.ncl.ac.uk/undergraduate/degrees/h830/",
"https://www.ncl.ac.uk/undergraduate/degrees/hh82/",
"https://www.ncl.ac.uk/undergraduate/degrees/f100/",
"https://www.ncl.ac.uk/undergraduate/degrees/f103/",
"https://www.ncl.ac.uk/undergraduate/degrees/f106/",
"https://www.ncl.ac.uk/undergraduate/degrees/f102/",
"https://www.ncl.ac.uk/undergraduate/degrees/f107/",
"https://www.ncl.ac.uk/undergraduate/degrees/f151/",
"https://www.ncl.ac.uk/undergraduate/degrees/f123/",
"https://www.ncl.ac.uk/undergraduate/degrees/f122/",
"https://www.ncl.ac.uk/undergraduate/degrees/f124/",
"https://www.ncl.ac.uk/undergraduate/degrees/f156/",
"https://www.ncl.ac.uk/undergraduate/degrees/tt12/",
"https://www.ncl.ac.uk/undergraduate/degrees/h242/",
"https://www.ncl.ac.uk/undergraduate/degrees/h210/",
"https://www.ncl.ac.uk/undergraduate/degrees/h206/",
"https://www.ncl.ac.uk/undergraduate/degrees/h296/",
"https://www.ncl.ac.uk/undergraduate/degrees/h290/",
"https://www.ncl.ac.uk/undergraduate/degrees/h200/",
"https://www.ncl.ac.uk/undergraduate/degrees/h201/",
"https://www.ncl.ac.uk/undergraduate/degrees/h295/",
"https://www.ncl.ac.uk/undergraduate/degrees/h205/",
"https://www.ncl.ac.uk/undergraduate/degrees/q810/",
"https://www.ncl.ac.uk/undergraduate/degrees/qq83/",
"https://www.ncl.ac.uk/undergraduate/degrees/q800/",
"https://www.ncl.ac.uk/undergraduate/degrees/y001/",
"https://www.ncl.ac.uk/undergraduate/degrees/g405/",
"https://www.ncl.ac.uk/undergraduate/degrees/g400/",
"https://www.ncl.ac.uk/undergraduate/degrees/i520/",
"https://www.ncl.ac.uk/undergraduate/degrees/i522/",
"https://www.ncl.ac.uk/undergraduate/degrees/g450/",
"https://www.ncl.ac.uk/undergraduate/degrees/i610/",
"https://www.ncl.ac.uk/undergraduate/degrees/i140/",
"https://www.ncl.ac.uk/undergraduate/degrees/i120/",
"https://www.ncl.ac.uk/undergraduate/degrees/g420/",
"https://www.ncl.ac.uk/undergraduate/degrees/i192/",
"https://www.ncl.ac.uk/undergraduate/degrees/i190/",
"https://www.ncl.ac.uk/undergraduate/degrees/g600/",
"https://www.ncl.ac.uk/undergraduate/degrees/g406/",
"https://www.ncl.ac.uk/undergraduate/degrees/i100/",
"https://www.ncl.ac.uk/undergraduate/degrees/g401/",
"https://www.ncl.ac.uk/undergraduate/degrees/i524/",
"https://www.ncl.ac.uk/undergraduate/degrees/i521/",
"https://www.ncl.ac.uk/undergraduate/degrees/i612/",
"https://www.ncl.ac.uk/undergraduate/degrees/g451/",
"https://www.ncl.ac.uk/undergraduate/degrees/i141/",
"https://www.ncl.ac.uk/undergraduate/degrees/i122/",
"https://www.ncl.ac.uk/undergraduate/degrees/g421/",
"https://www.ncl.ac.uk/undergraduate/degrees/i194/",
"https://www.ncl.ac.uk/undergraduate/degrees/i191/",
"https://www.ncl.ac.uk/undergraduate/degrees/g603/",
"https://www.ncl.ac.uk/undergraduate/degrees/w301/",
"https://www.ncl.ac.uk/undergraduate/degrees/d455/",
"https://www.ncl.ac.uk/undergraduate/degrees/a206/",
"https://www.ncl.ac.uk/undergraduate/degrees/h990/",
"https://www.ncl.ac.uk/undergraduate/degrees/h991/",
"https://www.ncl.ac.uk/undergraduate/degrees/f641/",
"https://www.ncl.ac.uk/undergraduate/degrees/f640/",
"https://www.ncl.ac.uk/undergraduate/degrees/f645/",
"https://www.ncl.ac.uk/undergraduate/degrees/f646/",
"https://www.ncl.ac.uk/undergraduate/degrees/l100/",
"https://www.ncl.ac.uk/undergraduate/degrees/ln12/",
"https://www.ncl.ac.uk/undergraduate/degrees/l161/",
"https://www.ncl.ac.uk/undergraduate/degrees/x390/",
"https://www.ncl.ac.uk/undergraduate/degrees/h607/",
"https://www.ncl.ac.uk/undergraduate/degrees/h606/",
"https://www.ncl.ac.uk/undergraduate/degrees/h604/",
"https://www.ncl.ac.uk/undergraduate/degrees/h605/",
"https://www.ncl.ac.uk/undergraduate/degrees/h623/",
"https://www.ncl.ac.uk/undergraduate/degrees/h622/",
"https://www.ncl.ac.uk/undergraduate/degrees/h640/",
"https://www.ncl.ac.uk/undergraduate/degrees/h621/",
"https://www.ncl.ac.uk/undergraduate/degrees/h652/",
"https://www.ncl.ac.uk/undergraduate/degrees/h654/",
"https://www.ncl.ac.uk/undergraduate/degrees/h101/",
"https://www.ncl.ac.uk/undergraduate/degrees/h103/",
"https://www.ncl.ac.uk/undergraduate/degrees/q302/",
"https://www.ncl.ac.uk/undergraduate/degrees/q300/",
"https://www.ncl.ac.uk/undergraduate/degrees/q306/",
"https://www.ncl.ac.uk/undergraduate/degrees/qv31/",
"https://www.ncl.ac.uk/undergraduate/degrees/qw38/",
"https://www.ncl.ac.uk/undergraduate/degrees/f850/",
"https://www.ncl.ac.uk/undergraduate/degrees/f851/",
"https://www.ncl.ac.uk/undergraduate/degrees/f8d4/",
"https://www.ncl.ac.uk/undergraduate/degrees/fd84/",
"https://www.ncl.ac.uk/undergraduate/degrees/f8h8/",
"https://www.ncl.ac.uk/undergraduate/degrees/fh88/",
"https://www.ncl.ac.uk/undergraduate/degrees/f8c1/",
"https://www.ncl.ac.uk/undergraduate/degrees/fc81/",
"https://www.ncl.ac.uk/undergraduate/degrees/f8f6/",
"https://www.ncl.ac.uk/undergraduate/degrees/ff86/",
"https://www.ncl.ac.uk/undergraduate/degrees/p303/",
"https://www.ncl.ac.uk/undergraduate/degrees/p313/",
"https://www.ncl.ac.uk/undergraduate/degrees/w150/",
"https://www.ncl.ac.uk/undergraduate/degrees/w344/",
"https://www.ncl.ac.uk/undergraduate/degrees/b46d/",
"https://www.ncl.ac.uk/undergraduate/degrees/b4d6/",
"https://www.ncl.ac.uk/undergraduate/degrees/nd61/",
"https://www.ncl.ac.uk/undergraduate/degrees/f862/",
"https://www.ncl.ac.uk/undergraduate/degrees/f867/",
"https://www.ncl.ac.uk/undergraduate/degrees/f800/",
"https://www.ncl.ac.uk/undergraduate/degrees/l701/",
"https://www.ncl.ac.uk/undergraduate/degrees/lk74/",
"https://www.ncl.ac.uk/undergraduate/degrees/l241/",
"https://www.ncl.ac.uk/undergraduate/degrees/v100/",
"https://www.ncl.ac.uk/undergraduate/degrees/vv41/",
"https://www.ncl.ac.uk/undergraduate/degrees/n122/",
"https://www.ncl.ac.uk/undergraduate/degrees/n120/",
"https://www.ncl.ac.uk/undergraduate/degrees/n120/",
"https://www.ncl.ac.uk/undergraduate/degrees/n122/",
"https://www.ncl.ac.uk/undergraduate/degrees/n5n2/",
"https://www.ncl.ac.uk/undergraduate/degrees/n5n2/",
"https://www.ncl.ac.uk/undergraduate/degrees/p500/",
"https://www.ncl.ac.uk/undergraduate/degrees/m101/",
"https://www.ncl.ac.uk/undergraduate/degrees/q100/",
"https://www.ncl.ac.uk/undergraduate/degrees/q1t4/",
"https://www.ncl.ac.uk/undergraduate/degrees/q1r1/",
"https://www.ncl.ac.uk/undergraduate/degrees/q1r2/",
"https://www.ncl.ac.uk/undergraduate/degrees/q1r4/",
"https://www.ncl.ac.uk/undergraduate/degrees/h270/",
"https://www.ncl.ac.uk/undergraduate/degrees/h271/",
"https://www.ncl.ac.uk/undergraduate/degrees/c161/",
"https://www.ncl.ac.uk/undergraduate/degrees/cf17/",
"https://www.ncl.ac.uk/undergraduate/degrees/j615/",
"https://www.ncl.ac.uk/undergraduate/degrees/j616/",
"https://www.ncl.ac.uk/undergraduate/degrees/h504/",
"https://www.ncl.ac.uk/undergraduate/degrees/h501/",
"https://www.ncl.ac.uk/undergraduate/degrees/h503/",
"https://www.ncl.ac.uk/undergraduate/degrees/h502/",
"https://www.ncl.ac.uk/undergraduate/degrees/h355/",
"https://www.ncl.ac.uk/undergraduate/degrees/h356/",
"https://www.ncl.ac.uk/undergraduate/degrees/h520/",
"https://www.ncl.ac.uk/undergraduate/degrees/h524/",
"https://www.ncl.ac.uk/undergraduate/degrees/c350/",
"https://www.ncl.ac.uk/undergraduate/degrees/n500/",
"https://www.ncl.ac.uk/undergraduate/degrees/nn52/",
"https://www.ncl.ac.uk/undergraduate/degrees/b62m/",
"https://www.ncl.ac.uk/undergraduate/degrees/g101/",
"https://www.ncl.ac.uk/undergraduate/degrees/g100/",
"https://www.ncl.ac.uk/undergraduate/degrees/g103/",
"https://www.ncl.ac.uk/undergraduate/degrees/ng41/",
"https://www.ncl.ac.uk/undergraduate/degrees/gl11/",
"https://www.ncl.ac.uk/undergraduate/degrees/ggc3/",
"https://www.ncl.ac.uk/undergraduate/degrees/gg13/",
"https://www.ncl.ac.uk/undergraduate/degrees/g1n3/",
"https://www.ncl.ac.uk/undergraduate/degrees/g1n2/",
"https://www.ncl.ac.uk/undergraduate/degrees/hh37/",
"https://www.ncl.ac.uk/undergraduate/degrees/h300/",
"https://www.ncl.ac.uk/undergraduate/degrees/h301/",
"https://www.ncl.ac.uk/undergraduate/degrees/h3h8/",
"https://www.ncl.ac.uk/undergraduate/degrees/h3h2/",
"https://www.ncl.ac.uk/undergraduate/degrees/h305/",
"https://www.ncl.ac.uk/undergraduate/degrees/h304/",
"https://www.ncl.ac.uk/undergraduate/degrees/h3h6/",
"https://www.ncl.ac.uk/undergraduate/degrees/pql0/",
"https://www.ncl.ac.uk/undergraduate/degrees/b902/",
"https://www.ncl.ac.uk/undergraduate/degrees/a100/",
"https://www.ncl.ac.uk/undergraduate/degrees/h611/",
"https://www.ncl.ac.uk/undergraduate/degrees/h612/",
"https://www.ncl.ac.uk/undergraduate/degrees/t901/",
"https://www.ncl.ac.uk/undergraduate/degrees/tn92/",
"https://www.ncl.ac.uk/undergraduate/degrees/qt19/",
"https://www.ncl.ac.uk/undergraduate/degrees/r9q9/",
"https://www.ncl.ac.uk/undergraduate/degrees/w300/",
"https://www.ncl.ac.uk/undergraduate/degrees/w304/",
"https://www.ncl.ac.uk/undergraduate/degrees/bd46/",
"https://www.ncl.ac.uk/undergraduate/degrees/bd64/",
"https://www.ncl.ac.uk/undergraduate/degrees/a207/",
"https://www.ncl.ac.uk/undergraduate/degrees/b210/",
"https://www.ncl.ac.uk/undergraduate/degrees/b230/",
"https://www.ncl.ac.uk/undergraduate/degrees/v500/",
"https://www.ncl.ac.uk/undergraduate/degrees/fh82/",
"https://www.ncl.ac.uk/undergraduate/degrees/f303/",
"https://www.ncl.ac.uk/undergraduate/degrees/f300/",
"https://www.ncl.ac.uk/undergraduate/degrees/f304/",
"https://www.ncl.ac.uk/undergraduate/degrees/f305/",
"https://www.ncl.ac.uk/undergraduate/degrees/b100/",
"https://www.ncl.ac.uk/undergraduate/degrees/k400/",
"https://www.ncl.ac.uk/undergraduate/degrees/l200/",
"https://www.ncl.ac.uk/undergraduate/degrees/ll21/",
"https://www.ncl.ac.uk/undergraduate/degrees/vl12/",
"https://www.ncl.ac.uk/undergraduate/degrees/ll32/",
"https://www.ncl.ac.uk/undergraduate/degrees/c800/",
"https://www.ncl.ac.uk/undergraduate/degrees/c8c1/",
"https://www.ncl.ac.uk/undergraduate/degrees/c8g1/",
"https://www.ncl.ac.uk/undergraduate/degrees/c8b4/",
"https://www.ncl.ac.uk/undergraduate/degrees/c8c6/",
"https://www.ncl.ac.uk/undergraduate/degrees/d452/",
"https://www.ncl.ac.uk/undergraduate/degrees/l300/",
"https://www.ncl.ac.uk/undergraduate/degrees/rt47/",
"https://www.ncl.ac.uk/undergraduate/degrees/b621/",
"https://www.ncl.ac.uk/undergraduate/degrees/c600/",
"https://www.ncl.ac.uk/undergraduate/degrees/g300/",
"https://www.ncl.ac.uk/undergraduate/degrees/h244/",
"https://www.ncl.ac.uk/undergraduate/degrees/h249/",
"https://www.ncl.ac.uk/undergraduate/degrees/h392/",
"https://www.ncl.ac.uk/undergraduate/degrees/f345/",
"https://www.ncl.ac.uk/undergraduate/degrees/f344/",
"https://www.ncl.ac.uk/undergraduate/degrees/k421/",
"https://www.ncl.ac.uk/undergraduate/degrees/c301/",
"https://www.ncl.ac.uk/undergraduate/degrees/c300/", ]
        print(len(links))
        links = list(set(links))
        print(len(links))

        for url in links:
            yield scrapy.Request(url, callback=self.parse_data, meta={'url':url})


    def parse_data(self, response):
        item = get_item(ScrapyschoolEnglandBenItem)
        item['university'] = "Newcastle University"
        item['url'] = response.meta['url']
        print("===========================")
        print(response.url)
        print(response.meta['url'])
        try:
            alevel = response.xpath(
                "//h3[@class='expandable-is-set'][contains(text(),'A Levels')]/../../div")
            print(alevel)
            if len(alevel) > 0:
                item['alevel'] = clear_lianxu_space(alevel[0].xpath("..//text()").extract())
            print("item['alevel'] = ", item['alevel'])

            ib = response.xpath(
                "//h3[@class='expandable-is-set'][contains(text(),'International Baccalaureate')]/../../div//text()").extract()
            item['ib'] = clear_lianxu_space(ib)
            print("item['ib'] = ", item['ib'])

            yield item
        except Exception as e:
            with open("scrapySchool_England_Ben/error/" + item['university']+str(item['degree_type'])+".txt", 'a', encoding="utf-8") as f:
                f.write(str(e) + "\n" + response.url + "\n========================\n")
            print("异常：", str(e))
            print("报错url：", response.url)
