# -*- coding: utf-8 -*-
import scrapy
from scrapy.spiders import CrawlSpider, Rule
from scrapy.linkextractors import LinkExtractor
import re
from scrapySchool_England_Ben.clearSpace import clear_space, clear_lianxu_space
from scrapySchool_England_Ben.getItem import get_item
from scrapySchool_England_Ben.getTuition_fee import getTuition_fee
from scrapySchool_England_Ben.items import ScrapyschoolEnglandBenItem
from scrapySchool_England_Ben.getIELTS import get_ielts, get_toefl
from scrapySchool_England_Ben.getStartDate import getStartDate
from scrapySchool_England_Ben.remove_tags import remove_class
from scrapySchool_England_Ben.getDuration import getIntDuration, getTeachTime


class SouthamptonSolentUniversity_USpider(scrapy.Spider):
    name = "SouthamptonSolentUniversity_U"
    # start_urls = ["https://www.solent.ac.uk/courses?course-level=Postgraduate&p=0&viewType=grid"]
    start_urls = ["https://www.solent.ac.uk/courses?course-level=Undergraduate&keywords=&viewType=grid&p=0"]


    def parse(self, response):
        links = ["https://www.solent.ac.uk/courses/undergraduate/applied-human-nutrition-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/yacht-design-and-production-beng?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/accountancy-and-finance-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/yacht-design-and-production-beng?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/applied-human-nutrition-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/yacht-and-powercraft-design-beng?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/accountancy-and-finance-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/yacht-and-powercraft-design-beng?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/applied-human-nutrition-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/television-and-video-production-ba",
"https://www.solent.ac.uk/courses/undergraduate/accountancy-and-finance-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/television-and-video-production-ba",
"https://www.solent.ac.uk/courses/undergraduate/accountancy-and-finance-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/accountancy-and-finance-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/architectural-design-and-visualisation-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/acting-and-performance-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/animation-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/applied-sport-science-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/accountancy-and-finance-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/acting-and-performance-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/animation-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/architectural-design-and-technology-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/beauty-promotion-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/audio-and-acoustic-engineering-beng?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/audio-engineering-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/biomedical-science-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/audio-and-acoustic-engineering-beng?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/audio-engineering-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/audio-and-acoustic-engineering-beng?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/business-management-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/computer-games-design-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/business-information-technology-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/computer-games-indie-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/business-management-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/computer-games-design-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/business-information-technology-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/computer-games-indie-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/business-management-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/business-information-technology-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/computer-games-indie-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/business-management-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/computer-games-art-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/business-information-technology-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/computer-games-indie-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/business-management-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/computer-games-art-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/business-management-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/computer-networks-and-web-design-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/computer-networks-and-web-design-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/computer-games-software-development-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/computer-generated-imagery-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/computer-systems-and-networks-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/computing-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/computer-networks-and-web-design-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/computer-games-software-development-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/computer-generated-imagery-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/computer-systems-and-networks-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/computing-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/computer-networks-and-web-design-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/computer-games-software-development-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/computer-systems-and-networks-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/computing-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/computer-games-software-development-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/construction-management-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/computing-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/digital-music-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/digital-music-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/digital-animation-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/criminology-and-psychology-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/cyber-security-management-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/criminology-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/digital-animation-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/criminology-and-psychology-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/cyber-security-management-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/criminology-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/criminology-and-psychology-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/cyber-security-management-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/criminology-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/criminology-and-psychology-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/criminal-investigation-with-psychology-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/cyber-security-management-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/criminology-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/criminal-investigation-with-psychology-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/criminal-investigation-with-psychology-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/criminal-investigation-with-psychology-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/electronic-engineering-beng?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/electronic-engineering-beng?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/fashion-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/fashion-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/english-and-media-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/english-and-public-relations-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/engineering-design-and-manufacture-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/english-and-creative-writing-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/english-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/english-and-media-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/english-and-public-relations-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/engineering-design-and-manufacture-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/english-and-creative-writing-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/english-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/english-and-media-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/english-and-public-relations-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/english-and-creative-writing-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/english-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/english-and-film-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/english-and-media-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/english-and-public-relations-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/english-and-creative-writing-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/english-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/english-and-film-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/events-management-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/english-and-film-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/events-management-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/english-and-film-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/events-management-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/events-management-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/events-management-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/events-management-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/fashion-promotion-and-communication-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/fashion-promotion-and-communication-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/fashion-buying-and-merchandising-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/fashion-media-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/fashion-management-with-marketing-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/fashion-journalism-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/fashion-photography-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/fashion-media-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/fashion-management-with-marketing-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/fashion-journalism-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/fashion-photography-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/fashion-management-with-marketing-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/fashion-graphics-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/film-production-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/film-production-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/film-and-television-production-technology-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/film-and-television-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/fashion-styling-and-creative-direction-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/festival-and-event-management-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/film-and-television-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/fashion-styling-and-creative-direction-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/festival-and-event-management-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/film-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/festival-and-event-management-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/film-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/health-and-fitness-management-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/fine-art-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/football-business-management-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/fitness-and-personal-training-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/football-studies-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/international-air-travel-and-tourism-management-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/international-air-travel-and-tourism-management-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/interior-design-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/international-air-travel-and-tourism-management-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/interior-design-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/health-nutrition-and-exercise-science-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/football-science-msci?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/film-visual-effects-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/graphic-design-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/health-nutrition-and-exercise-science-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/graphic-design-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/health-nutrition-and-exercise-science-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/interior-design-decoration-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/information-technology-management-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/health-nutrition-and-exercise-science-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/interior-design-decoration-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/information-technology-management-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/illustration-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/illustration-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/llb-hons?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/llb-hons?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/llb-hons?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/make-up-and-hair-design-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/journalism-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/international-tourism-management-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/live-sound-technology-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/llb-hons?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/make-up-and-hair-design-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/journalism-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/international-tourism-management-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/live-sound-technology-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/journalism-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/international-tourism-management-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/journalism-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/maritime-law-and-business-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/marketing-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/maritime-transport-and-international-logistics-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/maritime-business-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/maritime-transport-and-international-logistics-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/maritime-transport-and-international-logistics-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/maritime-transport-and-international-logistics-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/media-production-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/media-production-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/musical-theatre-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/mechanical-engineering-beng?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/media-culture-and-production-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/musical-theatre-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/mechanical-engineering-beng?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/mental-health-and-psychological-wellbeing-msci?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/media-culture-and-production-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/marketing-with-advertising-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/marketing-with-sport-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/music-management-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/photography-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/photography-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/popular-music-journalism-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/physical-education-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/popular-music-journalism-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/psychology-child-development-and-education-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/music-promotion-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/popular-music-performance-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/popular-music-performance-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/popular-music-performance-and-production-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/popular-music-performance-and-production-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/product-design-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/product-design-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/popular-music-production-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/psychology-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/popular-music-production-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/renewable-energy-engineering-beng?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/shipping-and-port-management-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/social-work-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/renewable-energy-engineering-beng?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/psychology-counselling-and-mental-health-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/public-relations-and-communications-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/psychology-forensic-and-psychopathology-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/public-relations-and-communications-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/software-engineering-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/software-engineering-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/software-engineering-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/software-engineering-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/sport-coaching-and-sport-development-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/sound-for-film-tv-and-games-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/sustainability-science-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/sport-and-exercise-therapy-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/sport-performance-coaching-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/sport-management-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/special-effects-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/sport-and-exercise-therapy-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/sport-journalism-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/sport-journalism-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/post-production-for-film-and-television-ba",
"https://www.solent.ac.uk/courses/undergraduate/sport-and-exercise-psychology-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/television-and-video-production-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/television-post-production-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/sustainability-science-msci?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/television-studio-production-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/television-post-production-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/television-studio-production-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/vehicle-engineering-beng?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/trend-forecasting-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/trend-forecasting-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/video-and-streaming-technology-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/web-design-and-development-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/virtual-and-augmented-reality-design-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/virtual-and-augmented-reality-software-development-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/web-design-and-development-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/virtual-and-augmented-reality-design-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/virtual-and-augmented-reality-software-development-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/web-design-and-development-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/adult-nursing-practice-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/virtual-and-augmented-reality-design-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/adventure-and-outdoor-management-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/virtual-and-augmented-reality-software-development-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/adventure-and-outdoor-management-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/virtual-and-augmented-reality-design-ba?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/applied-human-nutrition-bsc?year=2019",
"https://www.solent.ac.uk/courses/undergraduate/virtual-and-augmented-reality-software-development-bsc?year=2019", ]
        print(len(links))
        links = list(set(links))
        print(len(links))

        for url in links:
            yield scrapy.Request(url, callback=self.parse_data, meta={'url': url})

    def parse_data(self, response):
        item = get_item(ScrapyschoolEnglandBenItem)
        item['university'] = "Southampton Solent University"
        item['url'] = response.meta['url']
        print("===========================")
        print(response.url)
        print(response.meta['url'])
        try:
            item['alevel'] =  None
            alevel = response.xpath(
                "//h4[contains(text(),'UCAS tariff points from A-levels')]//text()|"
                "//li[contains(text(), 'A-level')]//text()|//li[contains(text(), 'A Level')]//text()").extract()
            item['alevel'] = clear_lianxu_space(alevel)
            print("item['alevel']: ", item['alevel'])
            if item['alevel'] == "":
                print("****111")


            yield item
        except Exception as e:
            with open("scrapySchool_England_Ben/error/" + item['university'] + str(item['degree_type']) + ".txt", 'a', encoding="utf-8") as f:
                f.write(str(e) + "\n" + response.url + "\n========================\n")
            print("异常：", str(e))
            print("报错url：", response.url)

