# -*- coding: utf-8 -*-
import scrapy
import re
from scrapySchool_England_Ben.clearSpace import clear_space, clear_lianxu_space, clear_space_str
from scrapySchool_England_Ben.getItem import get_item
from scrapySchool_England_Ben.getTuition_fee import getTuition_fee
from scrapySchool_England_Ben.items import ScrapyschoolEnglandBenItem
import requests
from lxml import etree
from scrapySchool_England_Ben.getIELTS import get_ielts, get_toefl
from scrapySchool_England_Ben.remove_tags import remove_class
from scrapySchool_England_Ben.getStartDate import getStartDate
from scrapySchool_England_Ben.getDuration import getIntDuration

class TheUniversityofEdinburgh_USpider(scrapy.Spider):
    name = "TheUniversityofEdinburgh_U"
    start_urls = ["https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=degreeList"]
    headers = {"user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"}

    def parse(self, response):
        links = ["https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=NN14",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=NN43",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=W380",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=D401",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=D402",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=D403",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=D404",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=C183",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=V190",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=V110",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=VV14",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=VQ17",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=VQ16",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=VV41",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=W615",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=G120",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=C610",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=T620",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=QQK7",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=TN61",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=TL61",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=TR61",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=TV61",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=TV63",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=T621",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=TL62",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=R4T8",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=LT66",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=TR64",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=V400",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=VV1A",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=VL46",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=VVH4",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=VV31",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=K100",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=W100",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=G700",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=GG47",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=F510",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=F361",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=C100",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=C700",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=J700",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=C130",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=C140",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=C180",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=C182",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=C400",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=C550",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=C720",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=C440",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=C200",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=C300",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=C1N1",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=C190",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=NL11",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=NL17",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=NM11",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=N100",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=NN12",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=N1N2",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=N1N6",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=N1N5",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=N1L1",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=Q500",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=QV54",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=QQ53",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=QQH5",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=QR51",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=QR52",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=QQ15",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=QR56",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=QV52",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=Q590",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=H804",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=H800",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=F333",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=F334",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=F100",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=F104",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=T100",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=TL11",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=BR31",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=BR32",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=TV11",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=TR13",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=TQ11",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=BR37",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=BR34",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=H203",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=H200",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=QT86",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=QV84",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=VQ46",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=Q810",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=Q800",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=QQ83",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=QQ81",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=C859",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=C851",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=X320",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=F355",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=F343",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=G400",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=G401",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=GN42",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=GG14",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=GF43",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=V600",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=VQ68",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=CF17",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=CN12",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=V300",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=L100",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=LN14",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=LG11",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=LL12",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=LL13",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=LG13",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=L1F9",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=L1N3",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=L1N2",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=HH36",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=HHH6",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=GHK6",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=GH60",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=H601",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=H600",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=H100",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=QQ32",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=Q302",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=Q300",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=Q306",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=QQ38",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=QVH1",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=F630",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=W230",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=P390",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=NN13",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=W150",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=R120",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RN11",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=QR81",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=QR31",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RQ13",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RR12",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RV11",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RV13",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RR13",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RQ11",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RV15",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RL12",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RR15",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RR17",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RR16",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RQ15",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RL14",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RR14",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=L700",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=F800",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=LV74",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=LL71",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=LL72",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=LL76",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=LL74",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=LL73",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=F640",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=F600",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=FF6V",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=FF68",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=F660",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=M7G6",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=L3R7",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=F690",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=L5T6",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=FFP8",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=K7T8",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=K8T9",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=U9H6",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=R220",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RN21",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=QR82",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=QR32",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RQ23",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RV21",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RV23",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RR23",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RQ21",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RV25",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RL22",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RR25",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RR27",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RR26",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RQ25",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RL24",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RR24",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=L230",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=L231",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=W210",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=Q700",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=2D45",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=V100",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=VV1K",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=VQ18",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=V200",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=VV13",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=LV21",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=VV12",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=V350",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=V360",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=TV13",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=VQ33",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=VW33",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=VQ35",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=W220",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=C590",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=W250",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=W900",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=N120",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=N1T6",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=N1T1",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=N1R1",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=N1R2",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=N1R3",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=N1T2",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=N1R7",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=N1R4",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=L250",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=LM29",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=2W3A",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=V622",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=R310",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RN31",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=QR83",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=QR33",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RQH3",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RV31",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RV33",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RQ31",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RV35",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=LR23",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RR35",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RRH7",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RR36",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RQ39",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RL34",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RR34",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=T210",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=TQ21",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=W721",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=4J22",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=Q600",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=M114",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=MN14",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=MN11",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=MQ15",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=ML11",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=MR11",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=MR12",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=MV11",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=ML1F",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=ML12",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=M1L6",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=ML14",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=ML13",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=MR14",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=Q100",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=QQ31",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=QL16",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=F326",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=F325",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=G101",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=G102",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=G100",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=B64Z",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=GN11",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=GW13",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=GF13",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=GG13",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=G1N2",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=H300",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=H303",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=B100",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=FC1R",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=FC17",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=A100",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=T600",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=W302",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=B140",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=B700",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=A900",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=W120",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=W451",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=T6Q3",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=T63H",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=LT26",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=TL66",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=T633",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=B210",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=V500",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=VL51",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=VQM3",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=VQ53",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=QV75",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=VQ51",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=VG51",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=VL52",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=VC58",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=VQ55",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=VV56",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=W640",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=XC61",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=F303",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=F300",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=W2S4",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=9W23",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=F304",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=B120",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=L200",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=8M9D",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=R500",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RN51",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RQ53",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RQM3",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RV51",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RV53",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RQ51",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RV55",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RLM2",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RR57",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RR56",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RQ59",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RL54",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=3T59",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=3R67",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=W240",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=C802",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=CN81",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=CZ81",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=CQ81",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=V627",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=VQ63",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=V6Q3",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=C142",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=R700",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RN71",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RQ78",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=QR37",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RQ73",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RV71",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RV73",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RQ71",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RV75",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=LR27",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RR76",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RQ79",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RL74",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RR74",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=R600",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=QR86",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=QR36",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RQ63",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RV61",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RQ61",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RV65",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RL62",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RQ69",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RL64",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RR64",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=V910",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=VV94",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=VQ95",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=VQ93",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=VQX3",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=VR96",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=VV92",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=VQ92",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=Q531",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=QQH8",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=QVJ1",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=QV22",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=Q501",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=W130",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=L600",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=LL62",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=LL64",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=LL69",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=LL41",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=LM41",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=LL42",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=LL43",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=4T6H",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=L500",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=L300",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=LL32",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=LC38",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=LL36",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=5S9K",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=G600",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=R410",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RN41",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RQ48",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=QR34",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RQ43",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RV41",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RV43",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RQ41",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RV45",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RL42",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RR45",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RQ49",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=RL44",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=N230",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=HHF1",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=HH21",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=H2KC",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=H2K1",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=HL23",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=J420",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=QVV6",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=F306",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=F302",
"https://www.ed.ac.uk/studying/undergraduate/degrees/index.php?action=programme&code=D100", ]
        print(len(links))
        links = list(set(links))
        print(len(links))

        for url in links:
            yield scrapy.Request(url, callback=self.parse_data, meta={'url':url})

    def parse_data(self, response):
        item = get_item(ScrapyschoolEnglandBenItem)
        item['university'] = "The University of Edinburgh"
        item['url'] = response.meta['url']
        print("===========================")
        print(response.url)
        print(response.meta['url'])

        try:
            alevel = response.xpath(
                "//div[@id='proxy_collapseEntry']//li[contains(text(),'A Levels:')]//text()|//div[@id='proxy_collapseEntry']//p[contains(text(),'A levels:')]//text()").extract()
            clear_space(alevel)
            if len(alevel) > 0:
                item['alevel'] = ''.join(alevel[-1]).strip()
            print("item['alevel'] = ", item['alevel'])

            # ib = response.xpath(
            #     "//html//ul[1]/li[3]/abbr[contains(text(),'IB')]/..//text()|//p[contains(text(),'IB:')]//text()").extract()
            ib = response.xpath("//html//ul[3]/li[3]/abbr[contains(text(),'IB')]/..//text()|//div[@id='proxy_collapseEntry']//p[contains(text(),'IB:')]//text()").extract()
            clear_space(ib)
            if len(ib) > 0:
                item['ib'] = ''.join(ib).strip()
            print("item['ib'] = ", item['ib'])

            yield item
        except Exception as e:
            with open("scrapySchool_England_Ben/error/"+item['university']+str(item['degree_type'])+".txt", 'a', encoding="utf-8") as f:
                f.write(str(e) + "\n" + response.url + "\n========================")
            print("异常：", str(e))
            print("报错url：", response.url)
