import scrapy
import re
import json
from scrapy.spiders import CrawlSpider, Rule
from scrapy.linkextractors import LinkExtractor
from scrapySchool_England_Ben.clearSpace import clear_space, clear_lianxu_space, clear_space_str
from scrapySchool_England_Ben.items import ScrapyschoolEnglandBenItem
from scrapySchool_England_Ben.getItem import get_item
from scrapySchool_England_Ben.getTuition_fee import getTuition_fee
from scrapySchool_England_Ben.getIELTS import get_ielts, get_toefl
from scrapySchool_England_Ben.getStartDate import getStartDate
from scrapySchool_England_Ben.remove_tags import remove_class
from scrapySchool_England_Ben.getDuration import getIntDuration, getTeachTime
import requests
from lxml import etree

class UniversityOfReading_USpider(scrapy.Spider):
    name = "UniversityOfReading_U"
    start_urls = ["https://www.reading.ac.uk/"]
    headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3472.3 Safari/537.36"}

    def parse(self, response):
        links = ["http://www.reading.ac.uk/ready-to-study/study/subject-area/business-and-management-accounting-and-finance-ug/ba-accounting-and-business.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/business-and-management-accounting-and-finance-ug/bsc-accounting-and-finance.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/business-and-management-accounting-and-finance-ug/bsc-accounting-and-finance-with-placement-experience.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/business-and-management-accounting-and-finance-ug/ba-accounting-and-management.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/business-and-management-accounting-and-finance-ug/ba-accounting-and-management-with-placement-experience.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/agriculture-ug/bsc-agricultural-business-management.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/agriculture-ug/bsc-agricultural-business-management-with-placement-year.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/agriculture-ug/bsc-agriculture.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/agriculture-ug/bsc-agriculture-with-industrial-training.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/ancient-history-ug/ba-ancient-history.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/ancient-history-ug/ba-ancient-history-and-archaeology.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/ancient-history-ug/ba-ancient-history-and-archaeology-with-placement-and-study-abroad.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/archaeology-ug/ba-ancient-history-and-archaeology-with-placement-and-study-abroad.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/ancient-history-ug/ba-ancient-history-and-archaeology-with-professional-placement.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/archaeology-ug/ba-ancient-history-and-archaeology-with-professional-experience.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/ancient-history-ug/ba-ancient-history-and-archaeology-with-study-year-abroad.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/archaeology-ug/ba-ancient-history-and-archaeology-with-study-year-abroad.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/ancient-history-ug/ba-ancient-history-and-history.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/animal-science-ug/bsc-animal-science.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/animal-science-ug/bsc-animal-science-with-industrial-training.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/psychology-ug/msci-applied-psychology-clinical.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/archaeology-ug/bsc-archaeological-science.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/archaeology-ug/bsc-archaeological-science-with-placement-and-study-abroad.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/archaeology-ug/bsc-archaeological-science-with-professional-experience.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/archaeology-ug/bsc-archaeological-science-with-study-year-abroad.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/archaeology-ug/ba-archaeology.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/archaeology-ug/ba-archaeology-and-classical-studies.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/archaeology-ug/ba-archaeology-and-classical-studies-with-placement-and-study-abroad.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/classics-ug/ba-archaeology-and-classical-studies-with-professional-experience.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/archaeology-ug/ba-archaeology-and-classical-studies-with-professional-experience.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/classics-ug/ba-archaeology-and-classical-studies-with-placement-and-study-abroad.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/classics-ug/ba-archaeology-and-classical-studies-with-study-year-abroad.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/archaeology-ug/ba-archaeology-and-classical-studies-with-study-year-abroad.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/archaeology-ug/ba-archaeology-and-history.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/history-ug/ba-archaeology-and-history-with-placement-and-study-abroad.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/archaeology-ug/ba-archaeology-and-history-with-placement-and-study-abroad.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/history-ug/ba-archaeology-and-history-with-professional-experience.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/archaeology-ug/ba-archaeology-and-history-with-professional-experience.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/archaeology-ug/ba-archaeology-and-history-with-study-year-abroad.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/history-ug/ba-archaeology-and-history-with-study-year-abroad.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/archaeology-ug/ba-archaeology-with-placement-and-study-abroad.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/archaeology-ug/ba-archaeology-with-professional-experience.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/archaeology-ug/ba-archaeology-with-study-abroad-year.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/architecture-ug/bsc-architecture.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/art-ug/ba-art.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/art-ug/ba-art-and-english-literature.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/art-ug/ba-art-and-film.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/art-ug/ba-art-and-film-and-theatre.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/art-ug/ba-art-and-history-of-art.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/art-ug/ba-art-and-philosophy.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/art-ug/ba-art-and-psychology.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/art-ug/ba-art-and-theatre.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/biological-sciences-ug/bsc-biochemistry.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/biological-sciences-ug/bsc-biochemistry-with-foundation.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/biological-sciences-ug/bsc-biochemistry-with-professional-experience.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/biological-sciences-ug/bsc-biological-sciences.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/biological-sciences-ug/bsc-biological-sciences-with-foundation.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/biological-sciences-ug/bsc-biological-sciences-with-industrial-experience.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/biomedical-engineering-ug/beng-biomedical-engineering.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/biomedical-engineering-ug/meng-biomedical-engineering.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/biological-sciences-ug/bsc-biomedical-sciences.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/biological-sciences-ug/bsc-biomedical-sciences-with-foundation.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/biological-sciences-ug/bsc-biomedical-sciences-with-professional-experience.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/surveying-and-construction-ug/bsc-building-surveying.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/business-and-management-accounting-and-finance-ug/ba-business-and-management.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/economics-ug/bsc-business-economics.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/economics-ug/bsc-business-economics-with-placement-year.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/chemistry-ug/mchem-chemistry.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/chemistry-ug/bsc-chemistry.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/chemistry-ug/mchem-chemistry-with-a-year-in-industry-research.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/chemistry-ug/bsc-chemistry-with-a-year-in-industry-research.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/chemistry-ug/bsc-chemistry-with-foundation.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/classics-ug/ba-classical-studies.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/classics-ug/ba-classical-studies-and-english-literature.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/classics-ug/ba-classical-and-medieval-studies.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/classics-ug/ba-classics.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/computer-science-ug/bsc-computational-mathematics.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/mathematics-ug/bsc-computational-mathematics.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/computer-science-ug/bsc-computational-mathematics-with-a-placement-year.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/mathematics-ug/bsc-computational-mathematics-with-a-placement-year.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/computer-science-ug/bsc-computer-science.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/computer-science-ug/bsc-computer-science-with-industrial-year.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/surveying-and-construction-ug/bsc-construction-management.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/surveying-and-construction-ug/bsc-construction-management-and-surveying.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/marketing-ug/bsc-consumer-behaviour-and-marketing.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/marketing-ug/bsc-consumer-behaviour-and-marketing-with-placement-year.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/environment-ug/bsc-ecology-and-wildlife-conservation.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/environment-ug/bsc-ecology-and-wildlife-conservation-with-foundation.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/environment-ug/bsc-ecology-and-wildlife-conservation-with-professional-experience.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/economics-ug/ba-economics.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/economics-ug/bsc-economics.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/economics-ug/bsc-economics-and-econometrics.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/economics-ug/bsc-economics-and-econometrics-with-placement-year.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/economics-ug/bsc-economics-and-finance.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/economics-ug/bsc-economics-with-placement-year.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/economics-ug/ba-economics-with-placement-year.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/education-ug/ba-education-studies.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/english-literature-ug/ba-english-and-comparative-literature.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/english-language-and-applied-linguistics-ug/ba-english-language-and-linguistics.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/english-language-and-applied-linguistics-ug/ba-english-language-and-literature.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/english-literature-ug/ba-english-literature.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/english-literature-ug/ba-english-literature-and-film.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/english-literature-ug/ba-english-literature-and-film-and-theatre.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/english-literature-ug/ba-english-literature-and-german.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/english-literature-ug/ba-english-literature-and-international-relations.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/english-literature-ug/ba-english-literature-and-italian.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/english-literature-ug/ba-english-literature-and-politics.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/english-literature-ug/ba-english-literature-and-theatre.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/english-literature-ug/ba-english-literature-with-french.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/business-and-management-accounting-and-finance-ug/ba-entrepreneurship.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/business-and-management-accounting-and-finance-ug/ba-entrepreneurship-and-management.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/business-and-management-accounting-and-finance-ug/ba-entrepreneurship-and-management-with-placement-experience.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/business-and-management-accounting-and-finance-ug/ba-entrepreneurship-with-placement-experience.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/environment-ug/bsc-environmental-management.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/environment-ug/bsc-environmental-management-with-professional-experience.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/physics-ug/bsc-environmental-physics.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/environment-ug/bsc-environmental-physics.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/environment-ug/bsc-environmental-physics-with-professional-experience.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/environment-ug/menvsci-environmental-science.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/environment-ug/bsc-environmental-science.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/environment-ug/menvsci-environmental-science-with-professional-experience.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/environment-ug/bsc-environmental-science-with-professional-experience.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/philosophy-ug/ba-ethics-value-and-philosophy.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/film-theatre-and-television-ug/ba-film.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/film-theatre-and-television-ug/ba-film-and-theatre.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/business-and-management-accounting-and-finance-ug/bsc-finance-and-investment-banking.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/business-and-management-accounting-and-finance-ug/bsc-finance-and-management-venice.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/art-ug/ba-fine-art.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/marketing-ug/bsc-food-marketing-and-business-economics.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/marketing-ug/bsc-food-marketing-and-business-economics-with-placement-year.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/nutrition-ug/bsc-food-science.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/food-and-nutrition-ug/bsc-food-science.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/food-and-nutrition-ug/bsc-food-science-with-business.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/food-and-nutrition-ug/bsc-food-science-with-business-with-a-year-in-industry.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/nutrition-ug/bsc-food-science-with-foundation.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/food-and-nutrition-ug/bsc-food-science-with-foundation.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/nutrition-ug/bsc-food-science-with-industrial-training.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/food-and-nutrition-ug/bsc-food-science-with-industrial-training.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/food-and-nutrition-ug/bsc-food-technology-with-bioprocessing-with-industrial-training.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/food-and-nutrition-ug/bsc-food-technology-with-bioprocessing.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/modern-languages-and-european-studies-ug/ba-french.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/modern-languages-and-european-studies-ug/ba-french-and-economics.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/modern-languages-and-european-studies-ug/ba-french-and-english-literature.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/modern-languages-and-european-studies-ug/ba-french-and-german.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/modern-languages-and-european-studies-ug/ba-french-and-history.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/modern-languages-and-european-studies-ug/ba-french-and-international-relations.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/modern-languages-and-european-studies-ug/ba-french-and-italian.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/modern-languages-and-european-studies-ug/ba-french-and-management.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/modern-languages-and-european-studies-ug/ba-french-and-spanish.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/french-ug/ba-french-studies-and-comparative-literature.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/modern-languages-and-european-studies-ug/ba-french-studies-and-english-language.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/geography-ug/bsc-human-and-physical-geography.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/geography-ug/bsc-human-and-physical-geography-with-professional-experience.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/geography-ug/bsc-human-geography.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/geography-ug/bsc-human-geography-with-professional-experience.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/geography-ug/bsc-physical-geography.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/geography-ug/bsc-physical-geography-with-professional-experience.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/geography-ug/bsc-geography-and-economics-regional-science.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/geography-ug/bsc-geography-and-economics-regional-science-with-professional-experience.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/modern-languages-and-european-studies-ug/ba-german.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/modern-languages-and-european-studies-ug/ba-german-and-economics.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/modern-languages-and-european-studies-ug/ba-german-and-history.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/modern-languages-and-european-studies-ug/ba-german-and-international-relations.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/modern-languages-and-european-studies-ug/ba-german-and-italian.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/modern-languages-and-european-studies-ug/ba-german-and-management.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/german-ug/ba-german-studies-and-comparative-literature.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/modern-languages-and-european-studies-ug/ba-german-and-english-language.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/graphic-communication-ug/ba-graphic-communication.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/history-ug/ba-history.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/history-ug/ba-history-and-economics.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/history-ug/ba-history-and-english-literature.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/history-ug/ba-history-and-international-relations.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/history-ug/ba-history-and-philosophy.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/history-ug/ba-history-and-politics.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/business-and-management-accounting-and-finance-ug/bsc-international-business-and-finance.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/business-and-management-accounting-and-finance-ug/ba-international-business-and-management.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/international-development-ug/bsc-international-development.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/international-development-ug/bsc-international-development-with-placement-year.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/business-and-management-accounting-and-finance-ug/ba-international-management-business-administration-french.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/business-and-management-accounting-and-finance-ug/ba-international-management-business-administration-german.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/business-and-management-accounting-and-finance-ug/ba-international-management-business-administration-italian.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/business-and-management-accounting-and-finance-ug/ba-international-management-business-administration-spanish.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/politics-and-international-relations-ug/ba-international-relations-and-economics.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/real-estate-and-planning-ug/bsc-investment-and-finance-in-property.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/modern-languages-and-european-studies-ug/ba-italian.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/modern-languages-and-european-studies-ug/ba-italian-and-classical-studies.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/modern-languages-and-european-studies-ug/ba-italian-and-economics.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/modern-languages-and-european-studies-ug/ba-italian-and-history.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/modern-languages-and-european-studies-ug/ba-italian-and-international-relations.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/modern-languages-and-european-studies-ug/ba-italian-and-management.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/modern-languages-and-european-studies-ug/ba-italian-and-spanish.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/italian-ug/ba-italian-studies-and-comparative-literature.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/modern-languages-and-european-studies-ug/ba-italian-and-english-language.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/speech-and-language-therapy-ug/bsc-language-sciences-and-psychology.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/law-ug/llb-law.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/law-ug/llb-law-international-foundation-year.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/business-and-management-accounting-and-finance-ug/ba-management-and-business.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/business-and-management-accounting-and-finance-ug/bsc-management-with-information-technology.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/mathematics-ug/bsc-mathematics.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/mathematics-ug/mmath-mathematics.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/mathematics-ug/bsc-mathematics-and-economics.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/mathematics-ug/bsc-mathematics-and-economics-with-a-placement-year.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/mathematics-ug/bsc-mathematics-and-meteorology.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/mathematics-ug/mmath-mathematics-and-meteorology.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/mathematics-ug/mmath-mathematics-and-meteorology-with-a-placement-year.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/mathematics-ug/bsc-mathematics-and-meteorology-with-a-placement-year.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/mathematics-ug/bsc-mathematics-and-psychology.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/mathematics-ug/bsc-mathematics-and-psychology-with-placement-year.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/mathematics-ug/bsc-mathematics-and-statistics.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/mathematics-ug/bsc-mathematics-and-statistics-with-placement-year.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/mathematics-ug/bsc-mathematics-with-a-placement-year.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/mathematics-ug/mmath-mathematics-with-a-placement-year.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/computer-science-ug/bsc-mathematics-with-computer-science.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/mathematics-ug/bsc-mathematics-with-computer-science.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/computer-science-ug/bsc-mathematics-with-computer-science-with-a-placement-year.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/mathematics-ug/bsc-mathematics-with-computer-science-with-a-placement-year.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/mathematics-ug/bsc-mathematics-with-finance-and-investment-banking.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/mathematics-ug/bsc-mathematics-with-finance-and-investment-banking-with-a-placement-year.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/meteorology-and-climate-ug/bsc-meteorology-and-climate.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/meteorology-and-climate-ug/mmet-meteorology-and-climate-with-a-year-in-oklahoma.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/biological-sciences-ug/bsc-microbiology.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/biological-sciences-ug/bsc-microbiology-with-foundation.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/biological-sciences-ug/bsc-microbiology-with-professional-experience.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/museum-studies-ug/ba-museum-and-classical-studies.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/archaeology-ug/ba-museum-studies-and-archaeology.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/museum-studies-ug/ba-museum-studies-and-archaeology-with-placement-and-study-abroad.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/archaeology-ug/ba-museum-studies-and-archaeology-with-placement-and-study-abroad.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/museum-studies-ug/ba-museum-studies-and-archaeology-with-professional-experience.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/archaeology-ug/ba-museum-studies-and-archaeology-with-professional-experience.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/museum-studies-ug/ba-museum-studies-and-archaeology-with-study-year-abroad.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/archaeology-ug/ba-museum-studies-and-archaeology-with-study-year-abroad.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/food-and-nutrition-ug/bsc-nutrition-and-food-science.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/food-and-nutrition-ug/bsc-nutrition-and-food-science-with-professional-training.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/food-and-nutrition-ug/bsc-nutrition-with-food-consumer-sciences.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/food-and-nutrition-ug/bsc-nutrition-with-food-consumer-sciences-with-professional-training.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/pharmacy-ug/mpharm-pharmacy.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/pharmacy-ug/mpharm-pharmacy-with-foundation.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/philosophy-ug/ba-philosophy.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/philosophy-ug/ba-philosophy-and-classical-studies.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/philosophy-ug/ba-philosophy-and-english-literature.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/philosophy-ug/ba-philosophy-and-international-relations.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/philosophy-ug/ba-philosophy-and-politics.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/philosophy-ug/ba-ppe-philosophy-politics-and-economics.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/physics-ug/bsc-physics-of-the-environment.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/environment-ug/bsc-physics-of-the-environment.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/physics-ug/bsc-physics-of-the-environment-with-placement-year.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/environment-ug/bsc-physics-of-the-environment-with-placement-year.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/economics-ug/ba-politics-and-economics.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/politics-and-international-relations-ug/ba-politics-and-international-relations.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/teaching-ug/ba-qts-primary-education-with-art-specialism.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/education-ug/ba-qts-primary-education-with-art-specialism.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/education-ug/ba-qts-primary-education-with-english-specialism.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/education-ug/ba-qts-primary-education-with-mathematics-specialism.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/education-ug/ba-qts-primary-education-with-music-specialism.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/psychology-ug/bsc-psychology.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/psychology-ug/ba-psychology-and-philosophy.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/philosophy-ug/ba-psychology-and-philosophy.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/psychology-ug/bsc-psychology-with-neuroscience.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/psychology-ug/bsc-psychology-with-professional-placement.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/surveying-and-construction-ug/bsc-quantity-surveying.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/real-estate-and-planning-ug/bsc-real-estate.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/real-estate-and-planning-ug/bsc-real-estate-with-msc-diploma-in-urban-planning-and-development.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/modern-languages-and-european-studies-ug/ba-spanish.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/modern-languages-and-european-studies-ug/ba-spanish-and-economics.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/modern-languages-and-european-studies-ug/ba-spanish-and-english-literature.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/modern-languages-and-european-studies-ug/ba-german-and-spanish.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/modern-languages-and-european-studies-ug/ba-spanish-and-history.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/spanish-ug/copy-of-ba-spanish-and-international-development.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/modern-languages-and-european-studies-ug/ba-spanish-and-international-relations.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/modern-languages-and-european-studies-ug/ba-spanish-and-management-studies.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/spanish-ug/ba-spanish-studies-and-comparative-literature.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/modern-languages-and-european-studies-ug/ba-spanish-studies-and-english-language.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/speech-and-language-therapy-ug/msci-speech-and-language-therapy.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/linguistics-ug/msci-speech-and-language-therapy.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/film-theatre-and-television-ug/ba-theatre.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/politics-and-international-relations-ug/ba-war-peace-and-international-relations.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/zoology-ug/bsc-zoology.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/zoology-ug/bsc-zoology-with-foundation.aspx",
"http://www.reading.ac.uk/ready-to-study/study/subject-area/zoology-ug/bsc-zoology-with-professional-experience.aspx", ]
        print(len(links))
        links = list(set(links))
        print(len(links))

        for url in links:
            yield scrapy.Request(url, callback=self.parse_data, meta={'url': url})


    def parse_data(self, response):
        item = get_item(ScrapyschoolEnglandBenItem)
        item['university'] = "University of Reading"
        item['url'] = response.meta['url']
        print("===========================")
        print(response.url)
        print(response.meta['url'])
        try:
            alevel = response.xpath(
                "//strong[contains(text(),'International Baccalaureate')]/../preceding-sibling::*[position()<last()]//text()").extract()
            if len(alevel) == 0:
                alevel = response.xpath("//h4[contains(text(),'Typical')]/following-sibling::*[1]//text()|//h4[contains(text(),'A level')]/following-sibling::*[1]//text()").extract()
            item['alevel'] = ''.join(alevel).strip()
            if item['alevel'] == "":
                print("alevel 为空")
            print("item['alevel']: ", item['alevel'])

            ib = response.xpath(
                "//h4[contains(text(),'International Baccalaureate')]/following-sibling::*[1]//text()|"
                "//strong[contains(text(),'International Baccalaureate')]/../following-sibling::*[1]//text()").extract()
            item['ib'] = ''.join(ib).strip()
            # if item['ib'] == "":
            #     print("ib 为空")
            print("item['ib']: ", item['ib'])

            yield item
        except Exception as e:
            with open("scrapySchool_England_Ben/error/" + item['university'] + str(item['degree_type']) + ".txt", 'a+',
                      encoding="utf-8") as f:
                f.write(str(e) + "\n" + response.url + "\n========================\n")
            print("异常：", str(e))
            print("报错url：", response.url)

